; Generated 09/02/2023 GMT

; 
; Copyright © 2023, Microchip Technology Inc. and its subsidiaries ("Microchip")
; All rights reserved.
; 
; This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
; 
; Redistribution and use in source and binary forms, with or without modification, are
; permitted provided that the following conditions are met:
; 
;     1. Redistributions of source code must retain the above copyright notice, this list of
;        conditions and the following disclaimer.
; 
;     2. Redistributions in binary form must reproduce the above copyright notice, this list
;        of conditions and the following disclaimer in the documentation and/or other
;        materials provided with the distribution. Publication is not required when
;        this file is used in an embedded application.
; 
;     3. Microchip's name may not be used to endorse or promote products derived from this
;        software without specific prior written permission.
; 
; THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
; INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
; PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
; INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
; INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
; LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
; THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
; 


; 
; Code-generator required, PIC18F26K42 Definitions
; 
; SFR Addresses
bsr equ 03FE0h
fsr0 equ 03FE9h
fsr0h equ 03FEAh
fsr0l equ 03FE9h
fsr1 equ 03FE1h
fsr1h equ 03FE2h
fsr1l equ 03FE1h
fsr2 equ 03FD9h
fsr2h equ 03FDAh
fsr2l equ 03FD9h
indf0 equ 03FEFh
indf1 equ 03FE7h
indf2 equ 03FDFh
intcon equ 03FD2h
nvmcon equ 039E5h
pcl equ 03FF9h
pclath equ 03FFAh
pclatu equ 03FFBh
plusw0 equ 03FEBh
plusw1 equ 03FE3h
plusw2 equ 03FDBh
postdec0 equ 03FEDh
postdec1 equ 03FE5h
postdec2 equ 03FDDh
postinc0 equ 03FEEh
postinc1 equ 03FE6h
postinc2 equ 03FDEh
preinc0 equ 03FECh
preinc1 equ 03FE4h
preinc2 equ 03FDCh
prod equ 03FF3h
prodh equ 03FF4h
prodl equ 03FF3h
status equ 03FD8h
tablat equ 03FF5h
tblptr equ 03FF6h
tblptrh equ 03FF7h
tblptrl equ 03FF6h
tblptru equ 03FF8h
tosl equ 03FFDh
wreg equ 03FE8h

