; Generated 09/02/2023 GMT

; 
; Copyright © 2023, Microchip Technology Inc. and its subsidiaries ("Microchip")
; All rights reserved.
; 
; This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
; 
; Redistribution and use in source and binary forms, with or without modification, are
; permitted provided that the following conditions are met:
; 
;     1. Redistributions of source code must retain the above copyright notice, this list of
;        conditions and the following disclaimer.
; 
;     2. Redistributions in binary form must reproduce the above copyright notice, this list
;        of conditions and the following disclaimer in the documentation and/or other
;        materials provided with the distribution. Publication is not required when
;        this file is used in an embedded application.
; 
;     3. Microchip's name may not be used to endorse or promote products derived from this
;        software without specific prior written permission.
; 
; THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
; INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
; PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
; INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
; INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
; LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
; THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
; 


; 
; Code-generator required, PIC18F57Q43 Definitions
; 
; SFR Addresses
bsr equ 04E0h
fsr0 equ 04E9h
fsr0h equ 04EAh
fsr0l equ 04E9h
fsr1 equ 04E1h
fsr1h equ 04E2h
fsr1l equ 04E1h
fsr2 equ 04D9h
fsr2h equ 04DAh
fsr2l equ 04D9h
indf0 equ 04EFh
indf1 equ 04E7h
indf2 equ 04DFh
intcon equ 04D6h
nvmcon equ 041h
pcl equ 04F9h
pclath equ 04FAh
pclatu equ 04FBh
plusw0 equ 04EBh
plusw1 equ 04E3h
plusw2 equ 04DBh
postdec0 equ 04EDh
postdec1 equ 04E5h
postdec2 equ 04DDh
postinc0 equ 04EEh
postinc1 equ 04E6h
postinc2 equ 04DEh
preinc0 equ 04ECh
preinc1 equ 04E4h
preinc2 equ 04DCh
prod equ 04F3h
prodh equ 04F4h
prodl equ 04F3h
status equ 04D8h
tablat equ 04F5h
tblptr equ 04F6h
tblptrh equ 04F7h
tblptrl equ 04F6h
tblptru equ 04F8h
tosl equ 04FDh
wreg equ 04E8h

