; Generated 09/02/2023 GMT

; 
; Copyright © 2023, Microchip Technology Inc. and its subsidiaries ("Microchip")
; All rights reserved.
; 
; This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
; 
; Redistribution and use in source and binary forms, with or without modification, are
; permitted provided that the following conditions are met:
; 
;     1. Redistributions of source code must retain the above copyright notice, this list of
;        conditions and the following disclaimer.
; 
;     2. Redistributions in binary form must reproduce the above copyright notice, this list
;        of conditions and the following disclaimer in the documentation and/or other
;        materials provided with the distribution. Publication is not required when
;        this file is used in an embedded application.
; 
;     3. Microchip's name may not be used to endorse or promote products derived from this
;        software without specific prior written permission.
; 
; THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
; INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
; PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
; INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
; INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
; LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
; THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
; 


; 
; Code-generator required, PIC18LF2580 Definitions
; 
; SFR Addresses
bsr equ 0FE0h
fsr0 equ 0FE9h
fsr0h equ 0FEAh
fsr0l equ 0FE9h
fsr1 equ 0FE1h
fsr1h equ 0FE2h
fsr1l equ 0FE1h
fsr2 equ 0FD9h
fsr2h equ 0FDAh
fsr2l equ 0FD9h
indf0 equ 0FEFh
indf1 equ 0FE7h
indf2 equ 0FDFh
intcon equ 0FF2h
nvmcon equ 00h
pcl equ 0FF9h
pclath equ 0FFAh
pclatu equ 0FFBh
plusw0 equ 0FEBh
plusw1 equ 0FE3h
plusw2 equ 0FDBh
postdec0 equ 0FEDh
postdec1 equ 0FE5h
postdec2 equ 0FDDh
postinc0 equ 0FEEh
postinc1 equ 0FE6h
postinc2 equ 0FDEh
preinc0 equ 0FECh
preinc1 equ 0FE4h
preinc2 equ 0FDCh
prod equ 0FF3h
prodh equ 0FF4h
prodl equ 0FF3h
status equ 0FD8h
tablat equ 0FF5h
tblptr equ 0FF6h
tblptrh equ 0FF7h
tblptrl equ 0FF6h
tblptru equ 0FF8h
tosl equ 0FFDh
wreg equ 0FE8h

