// Generated 09/02/2023 GMT

/*
 * Copyright © 2023, Microchip Technology Inc. and its subsidiaries ("Microchip")
 * All rights reserved.
 * 
 * This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 *     1. Redistributions of source code must retain the above copyright notice, this list of
 *        conditions and the following disclaimer.
 * 
 *     2. Redistributions in binary form must reproduce the above copyright notice, this list
 *        of conditions and the following disclaimer in the documentation and/or other
 *        materials provided with the distribution. Publication is not required when
 *        this file is used in an embedded application.
 * 
 *     3. Microchip's name may not be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _PIC18F1330_INC_
#define _PIC18F1330_INC_

/*
 * Assembly Header file for the Microchip PIC Microcontroller
 * PIC18F1330
 */

/*
 * Device Registers
 */

// Register: PORTA
#define PORTA PORTA
PORTA                                    equ 0F80h
// bitfield definitions
PORTA_RA0_POSN                           equ 0000h
PORTA_RA0_POSITION                       equ 0000h
PORTA_RA0_SIZE                           equ 0001h
PORTA_RA0_LENGTH                         equ 0001h
PORTA_RA0_MASK                           equ 0001h
PORTA_RA1_POSN                           equ 0001h
PORTA_RA1_POSITION                       equ 0001h
PORTA_RA1_SIZE                           equ 0001h
PORTA_RA1_LENGTH                         equ 0001h
PORTA_RA1_MASK                           equ 0002h
PORTA_RA2_POSN                           equ 0002h
PORTA_RA2_POSITION                       equ 0002h
PORTA_RA2_SIZE                           equ 0001h
PORTA_RA2_LENGTH                         equ 0001h
PORTA_RA2_MASK                           equ 0004h
PORTA_RA3_POSN                           equ 0003h
PORTA_RA3_POSITION                       equ 0003h
PORTA_RA3_SIZE                           equ 0001h
PORTA_RA3_LENGTH                         equ 0001h
PORTA_RA3_MASK                           equ 0008h
PORTA_RA4_POSN                           equ 0004h
PORTA_RA4_POSITION                       equ 0004h
PORTA_RA4_SIZE                           equ 0001h
PORTA_RA4_LENGTH                         equ 0001h
PORTA_RA4_MASK                           equ 0010h
PORTA_RA5_POSN                           equ 0005h
PORTA_RA5_POSITION                       equ 0005h
PORTA_RA5_SIZE                           equ 0001h
PORTA_RA5_LENGTH                         equ 0001h
PORTA_RA5_MASK                           equ 0020h
PORTA_RA6_POSN                           equ 0006h
PORTA_RA6_POSITION                       equ 0006h
PORTA_RA6_SIZE                           equ 0001h
PORTA_RA6_LENGTH                         equ 0001h
PORTA_RA6_MASK                           equ 0040h
PORTA_RA7_POSN                           equ 0007h
PORTA_RA7_POSITION                       equ 0007h
PORTA_RA7_SIZE                           equ 0001h
PORTA_RA7_LENGTH                         equ 0001h
PORTA_RA7_MASK                           equ 0080h
PORTA_AN0_POSN                           equ 0000h
PORTA_AN0_POSITION                       equ 0000h
PORTA_AN0_SIZE                           equ 0001h
PORTA_AN0_LENGTH                         equ 0001h
PORTA_AN0_MASK                           equ 0001h
PORTA_AN1_POSN                           equ 0001h
PORTA_AN1_POSITION                       equ 0001h
PORTA_AN1_SIZE                           equ 0001h
PORTA_AN1_LENGTH                         equ 0001h
PORTA_AN1_MASK                           equ 0002h
PORTA_TX_POSN                            equ 0002h
PORTA_TX_POSITION                        equ 0002h
PORTA_TX_SIZE                            equ 0001h
PORTA_TX_LENGTH                          equ 0001h
PORTA_TX_MASK                            equ 0004h
PORTA_RX_POSN                            equ 0003h
PORTA_RX_POSITION                        equ 0003h
PORTA_RX_SIZE                            equ 0001h
PORTA_RX_LENGTH                          equ 0001h
PORTA_RX_MASK                            equ 0008h
PORTA_AN2_POSN                           equ 0004h
PORTA_AN2_POSITION                       equ 0004h
PORTA_AN2_SIZE                           equ 0001h
PORTA_AN2_LENGTH                         equ 0001h
PORTA_AN2_MASK                           equ 0010h
PORTA_MCLR_POSN                          equ 0005h
PORTA_MCLR_POSITION                      equ 0005h
PORTA_MCLR_SIZE                          equ 0001h
PORTA_MCLR_LENGTH                        equ 0001h
PORTA_MCLR_MASK                          equ 0020h
PORTA_OSC2_POSN                          equ 0006h
PORTA_OSC2_POSITION                      equ 0006h
PORTA_OSC2_SIZE                          equ 0001h
PORTA_OSC2_LENGTH                        equ 0001h
PORTA_OSC2_MASK                          equ 0040h
PORTA_OSC1_POSN                          equ 0007h
PORTA_OSC1_POSITION                      equ 0007h
PORTA_OSC1_SIZE                          equ 0001h
PORTA_OSC1_LENGTH                        equ 0001h
PORTA_OSC1_MASK                          equ 0080h
PORTA_INT0_POSN                          equ 0000h
PORTA_INT0_POSITION                      equ 0000h
PORTA_INT0_SIZE                          equ 0001h
PORTA_INT0_LENGTH                        equ 0001h
PORTA_INT0_MASK                          equ 0001h
PORTA_INT1_POSN                          equ 0001h
PORTA_INT1_POSITION                      equ 0001h
PORTA_INT1_SIZE                          equ 0001h
PORTA_INT1_LENGTH                        equ 0001h
PORTA_INT1_MASK                          equ 0002h
PORTA_CK_POSN                            equ 0002h
PORTA_CK_POSITION                        equ 0002h
PORTA_CK_SIZE                            equ 0001h
PORTA_CK_LENGTH                          equ 0001h
PORTA_CK_MASK                            equ 0004h
PORTA_DT_POSN                            equ 0003h
PORTA_DT_POSITION                        equ 0003h
PORTA_DT_SIZE                            equ 0001h
PORTA_DT_LENGTH                          equ 0001h
PORTA_DT_MASK                            equ 0008h
PORTA_T0CKI_POSN                         equ 0004h
PORTA_T0CKI_POSITION                     equ 0004h
PORTA_T0CKI_SIZE                         equ 0001h
PORTA_T0CKI_LENGTH                       equ 0001h
PORTA_T0CKI_MASK                         equ 0010h
PORTA_CLKO_POSN                          equ 0006h
PORTA_CLKO_POSITION                      equ 0006h
PORTA_CLKO_SIZE                          equ 0001h
PORTA_CLKO_LENGTH                        equ 0001h
PORTA_CLKO_MASK                          equ 0040h
PORTA_CLKI_POSN                          equ 0007h
PORTA_CLKI_POSITION                      equ 0007h
PORTA_CLKI_SIZE                          equ 0001h
PORTA_CLKI_LENGTH                        equ 0001h
PORTA_CLKI_MASK                          equ 0080h
PORTA_KBI0_POSN                          equ 0000h
PORTA_KBI0_POSITION                      equ 0000h
PORTA_KBI0_SIZE                          equ 0001h
PORTA_KBI0_LENGTH                        equ 0001h
PORTA_KBI0_MASK                          equ 0001h
PORTA_KBI1_POSN                          equ 0001h
PORTA_KBI1_POSITION                      equ 0001h
PORTA_KBI1_SIZE                          equ 0001h
PORTA_KBI1_LENGTH                        equ 0001h
PORTA_KBI1_MASK                          equ 0002h
PORTA_VREFP_POSN                         equ 0004h
PORTA_VREFP_POSITION                     equ 0004h
PORTA_VREFP_SIZE                         equ 0001h
PORTA_VREFP_LENGTH                       equ 0001h
PORTA_VREFP_MASK                         equ 0010h
PORTA_T1OSO_POSN                         equ 0006h
PORTA_T1OSO_POSITION                     equ 0006h
PORTA_T1OSO_SIZE                         equ 0001h
PORTA_T1OSO_LENGTH                       equ 0001h
PORTA_T1OSO_MASK                         equ 0040h
PORTA_T1OSI_POSN                         equ 0007h
PORTA_T1OSI_POSITION                     equ 0007h
PORTA_T1OSI_SIZE                         equ 0001h
PORTA_T1OSI_LENGTH                       equ 0001h
PORTA_T1OSI_MASK                         equ 0080h
PORTA_NOT_MCLR_POSN                      equ 0005h
PORTA_NOT_MCLR_POSITION                  equ 0005h
PORTA_NOT_MCLR_SIZE                      equ 0001h
PORTA_NOT_MCLR_LENGTH                    equ 0001h
PORTA_NOT_MCLR_MASK                      equ 0020h
PORTA_CMP0_POSN                          equ 0000h
PORTA_CMP0_POSITION                      equ 0000h
PORTA_CMP0_SIZE                          equ 0001h
PORTA_CMP0_LENGTH                        equ 0001h
PORTA_CMP0_MASK                          equ 0001h
PORTA_nMCLR_POSN                         equ 0005h
PORTA_nMCLR_POSITION                     equ 0005h
PORTA_nMCLR_SIZE                         equ 0001h
PORTA_nMCLR_LENGTH                       equ 0001h
PORTA_nMCLR_MASK                         equ 0020h
PORTA_AN3_POSN                           equ 0006h
PORTA_AN3_POSITION                       equ 0006h
PORTA_AN3_SIZE                           equ 0001h
PORTA_AN3_LENGTH                         equ 0001h
PORTA_AN3_MASK                           equ 0040h
PORTA_T1CKI_POSN                         equ 0006h
PORTA_T1CKI_POSITION                     equ 0006h
PORTA_T1CKI_SIZE                         equ 0001h
PORTA_T1CKI_LENGTH                       equ 0001h
PORTA_T1CKI_MASK                         equ 0040h
PORTA_ULPWUIN_POSN                       equ 0000h
PORTA_ULPWUIN_POSITION                   equ 0000h
PORTA_ULPWUIN_SIZE                       equ 0001h
PORTA_ULPWUIN_LENGTH                     equ 0001h
PORTA_ULPWUIN_MASK                       equ 0001h
PORTA_LVDIN_POSN                         equ 0005h
PORTA_LVDIN_POSITION                     equ 0005h
PORTA_LVDIN_SIZE                         equ 0001h
PORTA_LVDIN_LENGTH                       equ 0001h
PORTA_LVDIN_MASK                         equ 0020h
PORTA_RJPU_POSN                          equ 0007h
PORTA_RJPU_POSITION                      equ 0007h
PORTA_RJPU_SIZE                          equ 0001h
PORTA_RJPU_LENGTH                        equ 0001h
PORTA_RJPU_MASK                          equ 0080h

// Register: PORTB
#define PORTB PORTB
PORTB                                    equ 0F81h
// bitfield definitions
PORTB_RB0_POSN                           equ 0000h
PORTB_RB0_POSITION                       equ 0000h
PORTB_RB0_SIZE                           equ 0001h
PORTB_RB0_LENGTH                         equ 0001h
PORTB_RB0_MASK                           equ 0001h
PORTB_RB1_POSN                           equ 0001h
PORTB_RB1_POSITION                       equ 0001h
PORTB_RB1_SIZE                           equ 0001h
PORTB_RB1_LENGTH                         equ 0001h
PORTB_RB1_MASK                           equ 0002h
PORTB_RB2_POSN                           equ 0002h
PORTB_RB2_POSITION                       equ 0002h
PORTB_RB2_SIZE                           equ 0001h
PORTB_RB2_LENGTH                         equ 0001h
PORTB_RB2_MASK                           equ 0004h
PORTB_RB3_POSN                           equ 0003h
PORTB_RB3_POSITION                       equ 0003h
PORTB_RB3_SIZE                           equ 0001h
PORTB_RB3_LENGTH                         equ 0001h
PORTB_RB3_MASK                           equ 0008h
PORTB_RB4_POSN                           equ 0004h
PORTB_RB4_POSITION                       equ 0004h
PORTB_RB4_SIZE                           equ 0001h
PORTB_RB4_LENGTH                         equ 0001h
PORTB_RB4_MASK                           equ 0010h
PORTB_RB5_POSN                           equ 0005h
PORTB_RB5_POSITION                       equ 0005h
PORTB_RB5_SIZE                           equ 0001h
PORTB_RB5_LENGTH                         equ 0001h
PORTB_RB5_MASK                           equ 0020h
PORTB_RB6_POSN                           equ 0006h
PORTB_RB6_POSITION                       equ 0006h
PORTB_RB6_SIZE                           equ 0001h
PORTB_RB6_LENGTH                         equ 0001h
PORTB_RB6_MASK                           equ 0040h
PORTB_RB7_POSN                           equ 0007h
PORTB_RB7_POSITION                       equ 0007h
PORTB_RB7_SIZE                           equ 0001h
PORTB_RB7_LENGTH                         equ 0001h
PORTB_RB7_MASK                           equ 0080h
PORTB_PWM0_POSN                          equ 0000h
PORTB_PWM0_POSITION                      equ 0000h
PORTB_PWM0_SIZE                          equ 0001h
PORTB_PWM0_LENGTH                        equ 0001h
PORTB_PWM0_MASK                          equ 0001h
PORTB_PWM1_POSN                          equ 0001h
PORTB_PWM1_POSITION                      equ 0001h
PORTB_PWM1_SIZE                          equ 0001h
PORTB_PWM1_LENGTH                        equ 0001h
PORTB_PWM1_MASK                          equ 0002h
PORTB_INT2_POSN                          equ 0002h
PORTB_INT2_POSITION                      equ 0002h
PORTB_INT2_SIZE                          equ 0001h
PORTB_INT2_LENGTH                        equ 0001h
PORTB_INT2_MASK                          equ 0004h
PORTB_INT3_POSN                          equ 0003h
PORTB_INT3_POSITION                      equ 0003h
PORTB_INT3_SIZE                          equ 0001h
PORTB_INT3_LENGTH                        equ 0001h
PORTB_INT3_MASK                          equ 0008h
PORTB_PWM2_POSN                          equ 0004h
PORTB_PWM2_POSITION                      equ 0004h
PORTB_PWM2_SIZE                          equ 0001h
PORTB_PWM2_LENGTH                        equ 0001h
PORTB_PWM2_MASK                          equ 0010h
PORTB_PWM3_POSN                          equ 0005h
PORTB_PWM3_POSITION                      equ 0005h
PORTB_PWM3_SIZE                          equ 0001h
PORTB_PWM3_LENGTH                        equ 0001h
PORTB_PWM3_MASK                          equ 0020h
PORTB_PWM4_POSN                          equ 0006h
PORTB_PWM4_POSITION                      equ 0006h
PORTB_PWM4_SIZE                          equ 0001h
PORTB_PWM4_LENGTH                        equ 0001h
PORTB_PWM4_MASK                          equ 0040h
PORTB_PWM5_POSN                          equ 0007h
PORTB_PWM5_POSITION                      equ 0007h
PORTB_PWM5_SIZE                          equ 0001h
PORTB_PWM5_LENGTH                        equ 0001h
PORTB_PWM5_MASK                          equ 0080h
PORTB_KBI2_POSN                          equ 0002h
PORTB_KBI2_POSITION                      equ 0002h
PORTB_KBI2_SIZE                          equ 0001h
PORTB_KBI2_LENGTH                        equ 0001h
PORTB_KBI2_MASK                          equ 0004h
PORTB_KBI3_POSN                          equ 0003h
PORTB_KBI3_POSITION                      equ 0003h
PORTB_KBI3_SIZE                          equ 0001h
PORTB_KBI3_LENGTH                        equ 0001h
PORTB_KBI3_MASK                          equ 0008h
PORTB_PGC_POSN                           equ 0006h
PORTB_PGC_POSITION                       equ 0006h
PORTB_PGC_SIZE                           equ 0001h
PORTB_PGC_LENGTH                         equ 0001h
PORTB_PGC_MASK                           equ 0040h
PORTB_PGD_POSN                           equ 0007h
PORTB_PGD_POSITION                       equ 0007h
PORTB_PGD_SIZE                           equ 0001h
PORTB_PGD_LENGTH                         equ 0001h
PORTB_PGD_MASK                           equ 0080h
PORTB_CMP2_POSN                          equ 0002h
PORTB_CMP2_POSITION                      equ 0002h
PORTB_CMP2_SIZE                          equ 0001h
PORTB_CMP2_LENGTH                        equ 0001h
PORTB_CMP2_MASK                          equ 0004h
PORTB_CMP1_POSN                          equ 0003h
PORTB_CMP1_POSITION                      equ 0003h
PORTB_CMP1_SIZE                          equ 0001h
PORTB_CMP1_LENGTH                        equ 0001h
PORTB_CMP1_MASK                          equ 0008h
PORTB_T1OSO_POSN                         equ 0002h
PORTB_T1OSO_POSITION                     equ 0002h
PORTB_T1OSO_SIZE                         equ 0001h
PORTB_T1OSO_LENGTH                       equ 0001h
PORTB_T1OSO_MASK                         equ 0004h
PORTB_T1OSI_POSN                         equ 0003h
PORTB_T1OSI_POSITION                     equ 0003h
PORTB_T1OSI_SIZE                         equ 0001h
PORTB_T1OSI_LENGTH                       equ 0001h
PORTB_T1OSI_MASK                         equ 0008h
PORTB_T1CKI_POSN                         equ 0002h
PORTB_T1CKI_POSITION                     equ 0002h
PORTB_T1CKI_SIZE                         equ 0001h
PORTB_T1CKI_LENGTH                       equ 0001h
PORTB_T1CKI_MASK                         equ 0004h
PORTB_CCP2_PA2_POSN                      equ 0003h
PORTB_CCP2_PA2_POSITION                  equ 0003h
PORTB_CCP2_PA2_SIZE                      equ 0001h
PORTB_CCP2_PA2_LENGTH                    equ 0001h
PORTB_CCP2_PA2_MASK                      equ 0008h

// Register: OVDCONS
#define OVDCONS OVDCONS
OVDCONS                                  equ 0F82h
// bitfield definitions
OVDCONS_POUT_POSN                        equ 0000h
OVDCONS_POUT_POSITION                    equ 0000h
OVDCONS_POUT_SIZE                        equ 0006h
OVDCONS_POUT_LENGTH                      equ 0006h
OVDCONS_POUT_MASK                        equ 003Fh
OVDCONS_POUT0_POSN                       equ 0000h
OVDCONS_POUT0_POSITION                   equ 0000h
OVDCONS_POUT0_SIZE                       equ 0001h
OVDCONS_POUT0_LENGTH                     equ 0001h
OVDCONS_POUT0_MASK                       equ 0001h
OVDCONS_POUT1_POSN                       equ 0001h
OVDCONS_POUT1_POSITION                   equ 0001h
OVDCONS_POUT1_SIZE                       equ 0001h
OVDCONS_POUT1_LENGTH                     equ 0001h
OVDCONS_POUT1_MASK                       equ 0002h
OVDCONS_POUT2_POSN                       equ 0002h
OVDCONS_POUT2_POSITION                   equ 0002h
OVDCONS_POUT2_SIZE                       equ 0001h
OVDCONS_POUT2_LENGTH                     equ 0001h
OVDCONS_POUT2_MASK                       equ 0004h
OVDCONS_POUT3_POSN                       equ 0003h
OVDCONS_POUT3_POSITION                   equ 0003h
OVDCONS_POUT3_SIZE                       equ 0001h
OVDCONS_POUT3_LENGTH                     equ 0001h
OVDCONS_POUT3_MASK                       equ 0008h
OVDCONS_POUT4_POSN                       equ 0004h
OVDCONS_POUT4_POSITION                   equ 0004h
OVDCONS_POUT4_SIZE                       equ 0001h
OVDCONS_POUT4_LENGTH                     equ 0001h
OVDCONS_POUT4_MASK                       equ 0010h
OVDCONS_POUT5_POSN                       equ 0005h
OVDCONS_POUT5_POSITION                   equ 0005h
OVDCONS_POUT5_SIZE                       equ 0001h
OVDCONS_POUT5_LENGTH                     equ 0001h
OVDCONS_POUT5_MASK                       equ 0020h

// Register: OVDCOND
#define OVDCOND OVDCOND
OVDCOND                                  equ 0F83h
// bitfield definitions
OVDCOND_POVD_POSN                        equ 0000h
OVDCOND_POVD_POSITION                    equ 0000h
OVDCOND_POVD_SIZE                        equ 0006h
OVDCOND_POVD_LENGTH                      equ 0006h
OVDCOND_POVD_MASK                        equ 003Fh
OVDCOND_POVD0_POSN                       equ 0000h
OVDCOND_POVD0_POSITION                   equ 0000h
OVDCOND_POVD0_SIZE                       equ 0001h
OVDCOND_POVD0_LENGTH                     equ 0001h
OVDCOND_POVD0_MASK                       equ 0001h
OVDCOND_POVD1_POSN                       equ 0001h
OVDCOND_POVD1_POSITION                   equ 0001h
OVDCOND_POVD1_SIZE                       equ 0001h
OVDCOND_POVD1_LENGTH                     equ 0001h
OVDCOND_POVD1_MASK                       equ 0002h
OVDCOND_POVD2_POSN                       equ 0002h
OVDCOND_POVD2_POSITION                   equ 0002h
OVDCOND_POVD2_SIZE                       equ 0001h
OVDCOND_POVD2_LENGTH                     equ 0001h
OVDCOND_POVD2_MASK                       equ 0004h
OVDCOND_POVD3_POSN                       equ 0003h
OVDCOND_POVD3_POSITION                   equ 0003h
OVDCOND_POVD3_SIZE                       equ 0001h
OVDCOND_POVD3_LENGTH                     equ 0001h
OVDCOND_POVD3_MASK                       equ 0008h
OVDCOND_POVD4_POSN                       equ 0004h
OVDCOND_POVD4_POSITION                   equ 0004h
OVDCOND_POVD4_SIZE                       equ 0001h
OVDCOND_POVD4_LENGTH                     equ 0001h
OVDCOND_POVD4_MASK                       equ 0010h
OVDCOND_POVD5_POSN                       equ 0005h
OVDCOND_POVD5_POSITION                   equ 0005h
OVDCOND_POVD5_SIZE                       equ 0001h
OVDCOND_POVD5_LENGTH                     equ 0001h
OVDCOND_POVD5_MASK                       equ 0020h

// Register: DTCON
#define DTCON DTCON
DTCON                                    equ 0F84h
// bitfield definitions
DTCON_DTA_POSN                           equ 0000h
DTCON_DTA_POSITION                       equ 0000h
DTCON_DTA_SIZE                           equ 0006h
DTCON_DTA_LENGTH                         equ 0006h
DTCON_DTA_MASK                           equ 003Fh
DTCON_DTAPS_POSN                         equ 0006h
DTCON_DTAPS_POSITION                     equ 0006h
DTCON_DTAPS_SIZE                         equ 0002h
DTCON_DTAPS_LENGTH                       equ 0002h
DTCON_DTAPS_MASK                         equ 00C0h
DTCON_DT0_POSN                           equ 0000h
DTCON_DT0_POSITION                       equ 0000h
DTCON_DT0_SIZE                           equ 0001h
DTCON_DT0_LENGTH                         equ 0001h
DTCON_DT0_MASK                           equ 0001h
DTCON_DT1_POSN                           equ 0001h
DTCON_DT1_POSITION                       equ 0001h
DTCON_DT1_SIZE                           equ 0001h
DTCON_DT1_LENGTH                         equ 0001h
DTCON_DT1_MASK                           equ 0002h
DTCON_DT2_POSN                           equ 0002h
DTCON_DT2_POSITION                       equ 0002h
DTCON_DT2_SIZE                           equ 0001h
DTCON_DT2_LENGTH                         equ 0001h
DTCON_DT2_MASK                           equ 0004h
DTCON_DT3_POSN                           equ 0003h
DTCON_DT3_POSITION                       equ 0003h
DTCON_DT3_SIZE                           equ 0001h
DTCON_DT3_LENGTH                         equ 0001h
DTCON_DT3_MASK                           equ 0008h
DTCON_DT4_POSN                           equ 0004h
DTCON_DT4_POSITION                       equ 0004h
DTCON_DT4_SIZE                           equ 0001h
DTCON_DT4_LENGTH                         equ 0001h
DTCON_DT4_MASK                           equ 0010h
DTCON_DT5_POSN                           equ 0005h
DTCON_DT5_POSITION                       equ 0005h
DTCON_DT5_SIZE                           equ 0001h
DTCON_DT5_LENGTH                         equ 0001h
DTCON_DT5_MASK                           equ 0020h
DTCON_DTPS0_POSN                         equ 0006h
DTCON_DTPS0_POSITION                     equ 0006h
DTCON_DTPS0_SIZE                         equ 0001h
DTCON_DTPS0_LENGTH                       equ 0001h
DTCON_DTPS0_MASK                         equ 0040h
DTCON_DTPS1_POSN                         equ 0007h
DTCON_DTPS1_POSITION                     equ 0007h
DTCON_DTPS1_SIZE                         equ 0001h
DTCON_DTPS1_LENGTH                       equ 0001h
DTCON_DTPS1_MASK                         equ 0080h

// Register: PWMCON1
#define PWMCON1 PWMCON1
PWMCON1                                  equ 0F85h
// bitfield definitions
PWMCON1_OSYNC_POSN                       equ 0000h
PWMCON1_OSYNC_POSITION                   equ 0000h
PWMCON1_OSYNC_SIZE                       equ 0001h
PWMCON1_OSYNC_LENGTH                     equ 0001h
PWMCON1_OSYNC_MASK                       equ 0001h
PWMCON1_UDIS_POSN                        equ 0001h
PWMCON1_UDIS_POSITION                    equ 0001h
PWMCON1_UDIS_SIZE                        equ 0001h
PWMCON1_UDIS_LENGTH                      equ 0001h
PWMCON1_UDIS_MASK                        equ 0002h
PWMCON1_SEVTDIR_POSN                     equ 0003h
PWMCON1_SEVTDIR_POSITION                 equ 0003h
PWMCON1_SEVTDIR_SIZE                     equ 0001h
PWMCON1_SEVTDIR_LENGTH                   equ 0001h
PWMCON1_SEVTDIR_MASK                     equ 0008h
PWMCON1_SEVOPS_POSN                      equ 0004h
PWMCON1_SEVOPS_POSITION                  equ 0004h
PWMCON1_SEVOPS_SIZE                      equ 0004h
PWMCON1_SEVOPS_LENGTH                    equ 0004h
PWMCON1_SEVOPS_MASK                      equ 00F0h
PWMCON1_SEVOPS0_POSN                     equ 0004h
PWMCON1_SEVOPS0_POSITION                 equ 0004h
PWMCON1_SEVOPS0_SIZE                     equ 0001h
PWMCON1_SEVOPS0_LENGTH                   equ 0001h
PWMCON1_SEVOPS0_MASK                     equ 0010h
PWMCON1_SEVOPS1_POSN                     equ 0005h
PWMCON1_SEVOPS1_POSITION                 equ 0005h
PWMCON1_SEVOPS1_SIZE                     equ 0001h
PWMCON1_SEVOPS1_LENGTH                   equ 0001h
PWMCON1_SEVOPS1_MASK                     equ 0020h
PWMCON1_SEVOPS2_POSN                     equ 0006h
PWMCON1_SEVOPS2_POSITION                 equ 0006h
PWMCON1_SEVOPS2_SIZE                     equ 0001h
PWMCON1_SEVOPS2_LENGTH                   equ 0001h
PWMCON1_SEVOPS2_MASK                     equ 0040h
PWMCON1_SEVOPS3_POSN                     equ 0007h
PWMCON1_SEVOPS3_POSITION                 equ 0007h
PWMCON1_SEVOPS3_SIZE                     equ 0001h
PWMCON1_SEVOPS3_LENGTH                   equ 0001h
PWMCON1_SEVOPS3_MASK                     equ 0080h

// Register: PWMCON0
#define PWMCON0 PWMCON0
PWMCON0                                  equ 0F86h
// bitfield definitions
PWMCON0_PMOD_POSN                        equ 0000h
PWMCON0_PMOD_POSITION                    equ 0000h
PWMCON0_PMOD_SIZE                        equ 0003h
PWMCON0_PMOD_LENGTH                      equ 0003h
PWMCON0_PMOD_MASK                        equ 0007h
PWMCON0_PWMEN_POSN                       equ 0004h
PWMCON0_PWMEN_POSITION                   equ 0004h
PWMCON0_PWMEN_SIZE                       equ 0003h
PWMCON0_PWMEN_LENGTH                     equ 0003h
PWMCON0_PWMEN_MASK                       equ 0070h
PWMCON0_PMOD0_POSN                       equ 0000h
PWMCON0_PMOD0_POSITION                   equ 0000h
PWMCON0_PMOD0_SIZE                       equ 0001h
PWMCON0_PMOD0_LENGTH                     equ 0001h
PWMCON0_PMOD0_MASK                       equ 0001h
PWMCON0_PMOD1_POSN                       equ 0001h
PWMCON0_PMOD1_POSITION                   equ 0001h
PWMCON0_PMOD1_SIZE                       equ 0001h
PWMCON0_PMOD1_LENGTH                     equ 0001h
PWMCON0_PMOD1_MASK                       equ 0002h
PWMCON0_PMOD2_POSN                       equ 0002h
PWMCON0_PMOD2_POSITION                   equ 0002h
PWMCON0_PMOD2_SIZE                       equ 0001h
PWMCON0_PMOD2_LENGTH                     equ 0001h
PWMCON0_PMOD2_MASK                       equ 0004h
PWMCON0_PWMEN0_POSN                      equ 0004h
PWMCON0_PWMEN0_POSITION                  equ 0004h
PWMCON0_PWMEN0_SIZE                      equ 0001h
PWMCON0_PWMEN0_LENGTH                    equ 0001h
PWMCON0_PWMEN0_MASK                      equ 0010h
PWMCON0_PWMEN1_POSN                      equ 0005h
PWMCON0_PWMEN1_POSITION                  equ 0005h
PWMCON0_PWMEN1_SIZE                      equ 0001h
PWMCON0_PWMEN1_LENGTH                    equ 0001h
PWMCON0_PWMEN1_MASK                      equ 0020h
PWMCON0_PWMEN2_POSN                      equ 0006h
PWMCON0_PWMEN2_POSITION                  equ 0006h
PWMCON0_PWMEN2_SIZE                      equ 0001h
PWMCON0_PWMEN2_LENGTH                    equ 0001h
PWMCON0_PWMEN2_MASK                      equ 0040h

// Register: SEVTCMPH
#define SEVTCMPH SEVTCMPH
SEVTCMPH                                 equ 0F87h
// bitfield definitions
SEVTCMPH_SEVTCMPH_POSN                   equ 0000h
SEVTCMPH_SEVTCMPH_POSITION               equ 0000h
SEVTCMPH_SEVTCMPH_SIZE                   equ 0004h
SEVTCMPH_SEVTCMPH_LENGTH                 equ 0004h
SEVTCMPH_SEVTCMPH_MASK                   equ 000Fh

// Register: SEVTCMPL
#define SEVTCMPL SEVTCMPL
SEVTCMPL                                 equ 0F88h
// bitfield definitions
SEVTCMPL_SEVTCMPL_POSN                   equ 0000h
SEVTCMPL_SEVTCMPL_POSITION               equ 0000h
SEVTCMPL_SEVTCMPL_SIZE                   equ 0008h
SEVTCMPL_SEVTCMPL_LENGTH                 equ 0008h
SEVTCMPL_SEVTCMPL_MASK                   equ 00FFh

// Register: LATA
#define LATA LATA
LATA                                     equ 0F89h
// bitfield definitions
LATA_LATA0_POSN                          equ 0000h
LATA_LATA0_POSITION                      equ 0000h
LATA_LATA0_SIZE                          equ 0001h
LATA_LATA0_LENGTH                        equ 0001h
LATA_LATA0_MASK                          equ 0001h
LATA_LATA1_POSN                          equ 0001h
LATA_LATA1_POSITION                      equ 0001h
LATA_LATA1_SIZE                          equ 0001h
LATA_LATA1_LENGTH                        equ 0001h
LATA_LATA1_MASK                          equ 0002h
LATA_LATA2_POSN                          equ 0002h
LATA_LATA2_POSITION                      equ 0002h
LATA_LATA2_SIZE                          equ 0001h
LATA_LATA2_LENGTH                        equ 0001h
LATA_LATA2_MASK                          equ 0004h
LATA_LATA3_POSN                          equ 0003h
LATA_LATA3_POSITION                      equ 0003h
LATA_LATA3_SIZE                          equ 0001h
LATA_LATA3_LENGTH                        equ 0001h
LATA_LATA3_MASK                          equ 0008h
LATA_LATA4_POSN                          equ 0004h
LATA_LATA4_POSITION                      equ 0004h
LATA_LATA4_SIZE                          equ 0001h
LATA_LATA4_LENGTH                        equ 0001h
LATA_LATA4_MASK                          equ 0010h
LATA_LATA5_POSN                          equ 0005h
LATA_LATA5_POSITION                      equ 0005h
LATA_LATA5_SIZE                          equ 0001h
LATA_LATA5_LENGTH                        equ 0001h
LATA_LATA5_MASK                          equ 0020h
LATA_LATA6_POSN                          equ 0006h
LATA_LATA6_POSITION                      equ 0006h
LATA_LATA6_SIZE                          equ 0001h
LATA_LATA6_LENGTH                        equ 0001h
LATA_LATA6_MASK                          equ 0040h
LATA_LATA7_POSN                          equ 0007h
LATA_LATA7_POSITION                      equ 0007h
LATA_LATA7_SIZE                          equ 0001h
LATA_LATA7_LENGTH                        equ 0001h
LATA_LATA7_MASK                          equ 0080h
LATA_LA0_POSN                            equ 0000h
LATA_LA0_POSITION                        equ 0000h
LATA_LA0_SIZE                            equ 0001h
LATA_LA0_LENGTH                          equ 0001h
LATA_LA0_MASK                            equ 0001h
LATA_LA1_POSN                            equ 0001h
LATA_LA1_POSITION                        equ 0001h
LATA_LA1_SIZE                            equ 0001h
LATA_LA1_LENGTH                          equ 0001h
LATA_LA1_MASK                            equ 0002h
LATA_LA2_POSN                            equ 0002h
LATA_LA2_POSITION                        equ 0002h
LATA_LA2_SIZE                            equ 0001h
LATA_LA2_LENGTH                          equ 0001h
LATA_LA2_MASK                            equ 0004h
LATA_LA3_POSN                            equ 0003h
LATA_LA3_POSITION                        equ 0003h
LATA_LA3_SIZE                            equ 0001h
LATA_LA3_LENGTH                          equ 0001h
LATA_LA3_MASK                            equ 0008h
LATA_LA4_POSN                            equ 0004h
LATA_LA4_POSITION                        equ 0004h
LATA_LA4_SIZE                            equ 0001h
LATA_LA4_LENGTH                          equ 0001h
LATA_LA4_MASK                            equ 0010h
LATA_LA5_POSN                            equ 0005h
LATA_LA5_POSITION                        equ 0005h
LATA_LA5_SIZE                            equ 0001h
LATA_LA5_LENGTH                          equ 0001h
LATA_LA5_MASK                            equ 0020h
LATA_LA6_POSN                            equ 0006h
LATA_LA6_POSITION                        equ 0006h
LATA_LA6_SIZE                            equ 0001h
LATA_LA6_LENGTH                          equ 0001h
LATA_LA6_MASK                            equ 0040h
LATA_LA7_POSN                            equ 0007h
LATA_LA7_POSITION                        equ 0007h
LATA_LA7_SIZE                            equ 0001h
LATA_LA7_LENGTH                          equ 0001h
LATA_LA7_MASK                            equ 0080h

// Register: LATB
#define LATB LATB
LATB                                     equ 0F8Ah
// bitfield definitions
LATB_LATB0_POSN                          equ 0000h
LATB_LATB0_POSITION                      equ 0000h
LATB_LATB0_SIZE                          equ 0001h
LATB_LATB0_LENGTH                        equ 0001h
LATB_LATB0_MASK                          equ 0001h
LATB_LATB1_POSN                          equ 0001h
LATB_LATB1_POSITION                      equ 0001h
LATB_LATB1_SIZE                          equ 0001h
LATB_LATB1_LENGTH                        equ 0001h
LATB_LATB1_MASK                          equ 0002h
LATB_LATB2_POSN                          equ 0002h
LATB_LATB2_POSITION                      equ 0002h
LATB_LATB2_SIZE                          equ 0001h
LATB_LATB2_LENGTH                        equ 0001h
LATB_LATB2_MASK                          equ 0004h
LATB_LATB3_POSN                          equ 0003h
LATB_LATB3_POSITION                      equ 0003h
LATB_LATB3_SIZE                          equ 0001h
LATB_LATB3_LENGTH                        equ 0001h
LATB_LATB3_MASK                          equ 0008h
LATB_LATB4_POSN                          equ 0004h
LATB_LATB4_POSITION                      equ 0004h
LATB_LATB4_SIZE                          equ 0001h
LATB_LATB4_LENGTH                        equ 0001h
LATB_LATB4_MASK                          equ 0010h
LATB_LATB5_POSN                          equ 0005h
LATB_LATB5_POSITION                      equ 0005h
LATB_LATB5_SIZE                          equ 0001h
LATB_LATB5_LENGTH                        equ 0001h
LATB_LATB5_MASK                          equ 0020h
LATB_LATB6_POSN                          equ 0006h
LATB_LATB6_POSITION                      equ 0006h
LATB_LATB6_SIZE                          equ 0001h
LATB_LATB6_LENGTH                        equ 0001h
LATB_LATB6_MASK                          equ 0040h
LATB_LATB7_POSN                          equ 0007h
LATB_LATB7_POSITION                      equ 0007h
LATB_LATB7_SIZE                          equ 0001h
LATB_LATB7_LENGTH                        equ 0001h
LATB_LATB7_MASK                          equ 0080h
LATB_LB0_POSN                            equ 0000h
LATB_LB0_POSITION                        equ 0000h
LATB_LB0_SIZE                            equ 0001h
LATB_LB0_LENGTH                          equ 0001h
LATB_LB0_MASK                            equ 0001h
LATB_LB1_POSN                            equ 0001h
LATB_LB1_POSITION                        equ 0001h
LATB_LB1_SIZE                            equ 0001h
LATB_LB1_LENGTH                          equ 0001h
LATB_LB1_MASK                            equ 0002h
LATB_LB2_POSN                            equ 0002h
LATB_LB2_POSITION                        equ 0002h
LATB_LB2_SIZE                            equ 0001h
LATB_LB2_LENGTH                          equ 0001h
LATB_LB2_MASK                            equ 0004h
LATB_LB3_POSN                            equ 0003h
LATB_LB3_POSITION                        equ 0003h
LATB_LB3_SIZE                            equ 0001h
LATB_LB3_LENGTH                          equ 0001h
LATB_LB3_MASK                            equ 0008h
LATB_LB4_POSN                            equ 0004h
LATB_LB4_POSITION                        equ 0004h
LATB_LB4_SIZE                            equ 0001h
LATB_LB4_LENGTH                          equ 0001h
LATB_LB4_MASK                            equ 0010h
LATB_LB5_POSN                            equ 0005h
LATB_LB5_POSITION                        equ 0005h
LATB_LB5_SIZE                            equ 0001h
LATB_LB5_LENGTH                          equ 0001h
LATB_LB5_MASK                            equ 0020h
LATB_LB6_POSN                            equ 0006h
LATB_LB6_POSITION                        equ 0006h
LATB_LB6_SIZE                            equ 0001h
LATB_LB6_LENGTH                          equ 0001h
LATB_LB6_MASK                            equ 0040h
LATB_LB7_POSN                            equ 0007h
LATB_LB7_POSITION                        equ 0007h
LATB_LB7_SIZE                            equ 0001h
LATB_LB7_LENGTH                          equ 0001h
LATB_LB7_MASK                            equ 0080h

// Register: FLTCONFIG
#define FLTCONFIG FLTCONFIG
FLTCONFIG                                equ 0F8Bh
// bitfield definitions
FLTCONFIG_FLTAEN_POSN                    equ 0000h
FLTCONFIG_FLTAEN_POSITION                equ 0000h
FLTCONFIG_FLTAEN_SIZE                    equ 0001h
FLTCONFIG_FLTAEN_LENGTH                  equ 0001h
FLTCONFIG_FLTAEN_MASK                    equ 0001h
FLTCONFIG_FLTAMOD_POSN                   equ 0001h
FLTCONFIG_FLTAMOD_POSITION               equ 0001h
FLTCONFIG_FLTAMOD_SIZE                   equ 0001h
FLTCONFIG_FLTAMOD_LENGTH                 equ 0001h
FLTCONFIG_FLTAMOD_MASK                   equ 0002h
FLTCONFIG_FLTAS_POSN                     equ 0002h
FLTCONFIG_FLTAS_POSITION                 equ 0002h
FLTCONFIG_FLTAS_SIZE                     equ 0001h
FLTCONFIG_FLTAS_LENGTH                   equ 0001h
FLTCONFIG_FLTAS_MASK                     equ 0004h
FLTCONFIG_BRFEN_POSN                     equ 0007h
FLTCONFIG_BRFEN_POSITION                 equ 0007h
FLTCONFIG_BRFEN_SIZE                     equ 0001h
FLTCONFIG_BRFEN_LENGTH                   equ 0001h
FLTCONFIG_BRFEN_MASK                     equ 0080h

// Register: PDC2H
#define PDC2H PDC2H
PDC2H                                    equ 0F8Ch
// bitfield definitions
PDC2H_PDC2H_POSN                         equ 0000h
PDC2H_PDC2H_POSITION                     equ 0000h
PDC2H_PDC2H_SIZE                         equ 0006h
PDC2H_PDC2H_LENGTH                       equ 0006h
PDC2H_PDC2H_MASK                         equ 003Fh

// Register: PDC2L
#define PDC2L PDC2L
PDC2L                                    equ 0F8Dh
// bitfield definitions
PDC2L_PDC2L_POSN                         equ 0000h
PDC2L_PDC2L_POSITION                     equ 0000h
PDC2L_PDC2L_SIZE                         equ 0008h
PDC2L_PDC2L_LENGTH                       equ 0008h
PDC2L_PDC2L_MASK                         equ 00FFh

// Register: PDC1H
#define PDC1H PDC1H
PDC1H                                    equ 0F8Eh
// bitfield definitions
PDC1H_PDC1H_POSN                         equ 0000h
PDC1H_PDC1H_POSITION                     equ 0000h
PDC1H_PDC1H_SIZE                         equ 0006h
PDC1H_PDC1H_LENGTH                       equ 0006h
PDC1H_PDC1H_MASK                         equ 003Fh

// Register: PDC1L
#define PDC1L PDC1L
PDC1L                                    equ 0F8Fh
// bitfield definitions
PDC1L_PDC1L_POSN                         equ 0000h
PDC1L_PDC1L_POSITION                     equ 0000h
PDC1L_PDC1L_SIZE                         equ 0008h
PDC1L_PDC1L_LENGTH                       equ 0008h
PDC1L_PDC1L_MASK                         equ 00FFh

// Register: PDC0H
#define PDC0H PDC0H
PDC0H                                    equ 0F90h
// bitfield definitions
PDC0H_PDC0H_POSN                         equ 0000h
PDC0H_PDC0H_POSITION                     equ 0000h
PDC0H_PDC0H_SIZE                         equ 0006h
PDC0H_PDC0H_LENGTH                       equ 0006h
PDC0H_PDC0H_MASK                         equ 003Fh

// Register: PDC0L
#define PDC0L PDC0L
PDC0L                                    equ 0F91h
// bitfield definitions
PDC0L_PDC0L_POSN                         equ 0000h
PDC0L_PDC0L_POSITION                     equ 0000h
PDC0L_PDC0L_SIZE                         equ 0008h
PDC0L_PDC0L_LENGTH                       equ 0008h
PDC0L_PDC0L_MASK                         equ 00FFh

// Register: TRISA
#define TRISA TRISA
TRISA                                    equ 0F92h
// bitfield definitions
TRISA_TRISA0_POSN                        equ 0000h
TRISA_TRISA0_POSITION                    equ 0000h
TRISA_TRISA0_SIZE                        equ 0001h
TRISA_TRISA0_LENGTH                      equ 0001h
TRISA_TRISA0_MASK                        equ 0001h
TRISA_TRISA1_POSN                        equ 0001h
TRISA_TRISA1_POSITION                    equ 0001h
TRISA_TRISA1_SIZE                        equ 0001h
TRISA_TRISA1_LENGTH                      equ 0001h
TRISA_TRISA1_MASK                        equ 0002h
TRISA_TRISA2_POSN                        equ 0002h
TRISA_TRISA2_POSITION                    equ 0002h
TRISA_TRISA2_SIZE                        equ 0001h
TRISA_TRISA2_LENGTH                      equ 0001h
TRISA_TRISA2_MASK                        equ 0004h
TRISA_TRISA3_POSN                        equ 0003h
TRISA_TRISA3_POSITION                    equ 0003h
TRISA_TRISA3_SIZE                        equ 0001h
TRISA_TRISA3_LENGTH                      equ 0001h
TRISA_TRISA3_MASK                        equ 0008h
TRISA_TRISA4_POSN                        equ 0004h
TRISA_TRISA4_POSITION                    equ 0004h
TRISA_TRISA4_SIZE                        equ 0001h
TRISA_TRISA4_LENGTH                      equ 0001h
TRISA_TRISA4_MASK                        equ 0010h
TRISA_TRISA5_POSN                        equ 0005h
TRISA_TRISA5_POSITION                    equ 0005h
TRISA_TRISA5_SIZE                        equ 0001h
TRISA_TRISA5_LENGTH                      equ 0001h
TRISA_TRISA5_MASK                        equ 0020h
TRISA_TRISA6_POSN                        equ 0006h
TRISA_TRISA6_POSITION                    equ 0006h
TRISA_TRISA6_SIZE                        equ 0001h
TRISA_TRISA6_LENGTH                      equ 0001h
TRISA_TRISA6_MASK                        equ 0040h
TRISA_TRISA7_POSN                        equ 0007h
TRISA_TRISA7_POSITION                    equ 0007h
TRISA_TRISA7_SIZE                        equ 0001h
TRISA_TRISA7_LENGTH                      equ 0001h
TRISA_TRISA7_MASK                        equ 0080h
TRISA_RA0_POSN                           equ 0000h
TRISA_RA0_POSITION                       equ 0000h
TRISA_RA0_SIZE                           equ 0001h
TRISA_RA0_LENGTH                         equ 0001h
TRISA_RA0_MASK                           equ 0001h
TRISA_RA1_POSN                           equ 0001h
TRISA_RA1_POSITION                       equ 0001h
TRISA_RA1_SIZE                           equ 0001h
TRISA_RA1_LENGTH                         equ 0001h
TRISA_RA1_MASK                           equ 0002h
TRISA_RA2_POSN                           equ 0002h
TRISA_RA2_POSITION                       equ 0002h
TRISA_RA2_SIZE                           equ 0001h
TRISA_RA2_LENGTH                         equ 0001h
TRISA_RA2_MASK                           equ 0004h
TRISA_RA3_POSN                           equ 0003h
TRISA_RA3_POSITION                       equ 0003h
TRISA_RA3_SIZE                           equ 0001h
TRISA_RA3_LENGTH                         equ 0001h
TRISA_RA3_MASK                           equ 0008h
TRISA_RA4_POSN                           equ 0004h
TRISA_RA4_POSITION                       equ 0004h
TRISA_RA4_SIZE                           equ 0001h
TRISA_RA4_LENGTH                         equ 0001h
TRISA_RA4_MASK                           equ 0010h
TRISA_RA5_POSN                           equ 0005h
TRISA_RA5_POSITION                       equ 0005h
TRISA_RA5_SIZE                           equ 0001h
TRISA_RA5_LENGTH                         equ 0001h
TRISA_RA5_MASK                           equ 0020h
TRISA_RA6_POSN                           equ 0006h
TRISA_RA6_POSITION                       equ 0006h
TRISA_RA6_SIZE                           equ 0001h
TRISA_RA6_LENGTH                         equ 0001h
TRISA_RA6_MASK                           equ 0040h
TRISA_RA7_POSN                           equ 0007h
TRISA_RA7_POSITION                       equ 0007h
TRISA_RA7_SIZE                           equ 0001h
TRISA_RA7_LENGTH                         equ 0001h
TRISA_RA7_MASK                           equ 0080h

// Register: TRISB
#define TRISB TRISB
TRISB                                    equ 0F93h
// bitfield definitions
TRISB_TRISB0_POSN                        equ 0000h
TRISB_TRISB0_POSITION                    equ 0000h
TRISB_TRISB0_SIZE                        equ 0001h
TRISB_TRISB0_LENGTH                      equ 0001h
TRISB_TRISB0_MASK                        equ 0001h
TRISB_TRISB1_POSN                        equ 0001h
TRISB_TRISB1_POSITION                    equ 0001h
TRISB_TRISB1_SIZE                        equ 0001h
TRISB_TRISB1_LENGTH                      equ 0001h
TRISB_TRISB1_MASK                        equ 0002h
TRISB_TRISB2_POSN                        equ 0002h
TRISB_TRISB2_POSITION                    equ 0002h
TRISB_TRISB2_SIZE                        equ 0001h
TRISB_TRISB2_LENGTH                      equ 0001h
TRISB_TRISB2_MASK                        equ 0004h
TRISB_TRISB3_POSN                        equ 0003h
TRISB_TRISB3_POSITION                    equ 0003h
TRISB_TRISB3_SIZE                        equ 0001h
TRISB_TRISB3_LENGTH                      equ 0001h
TRISB_TRISB3_MASK                        equ 0008h
TRISB_TRISB4_POSN                        equ 0004h
TRISB_TRISB4_POSITION                    equ 0004h
TRISB_TRISB4_SIZE                        equ 0001h
TRISB_TRISB4_LENGTH                      equ 0001h
TRISB_TRISB4_MASK                        equ 0010h
TRISB_TRISB5_POSN                        equ 0005h
TRISB_TRISB5_POSITION                    equ 0005h
TRISB_TRISB5_SIZE                        equ 0001h
TRISB_TRISB5_LENGTH                      equ 0001h
TRISB_TRISB5_MASK                        equ 0020h
TRISB_TRISB6_POSN                        equ 0006h
TRISB_TRISB6_POSITION                    equ 0006h
TRISB_TRISB6_SIZE                        equ 0001h
TRISB_TRISB6_LENGTH                      equ 0001h
TRISB_TRISB6_MASK                        equ 0040h
TRISB_TRISB7_POSN                        equ 0007h
TRISB_TRISB7_POSITION                    equ 0007h
TRISB_TRISB7_SIZE                        equ 0001h
TRISB_TRISB7_LENGTH                      equ 0001h
TRISB_TRISB7_MASK                        equ 0080h
TRISB_RB0_POSN                           equ 0000h
TRISB_RB0_POSITION                       equ 0000h
TRISB_RB0_SIZE                           equ 0001h
TRISB_RB0_LENGTH                         equ 0001h
TRISB_RB0_MASK                           equ 0001h
TRISB_RB1_POSN                           equ 0001h
TRISB_RB1_POSITION                       equ 0001h
TRISB_RB1_SIZE                           equ 0001h
TRISB_RB1_LENGTH                         equ 0001h
TRISB_RB1_MASK                           equ 0002h
TRISB_RB2_POSN                           equ 0002h
TRISB_RB2_POSITION                       equ 0002h
TRISB_RB2_SIZE                           equ 0001h
TRISB_RB2_LENGTH                         equ 0001h
TRISB_RB2_MASK                           equ 0004h
TRISB_RB3_POSN                           equ 0003h
TRISB_RB3_POSITION                       equ 0003h
TRISB_RB3_SIZE                           equ 0001h
TRISB_RB3_LENGTH                         equ 0001h
TRISB_RB3_MASK                           equ 0008h
TRISB_RB4_POSN                           equ 0004h
TRISB_RB4_POSITION                       equ 0004h
TRISB_RB4_SIZE                           equ 0001h
TRISB_RB4_LENGTH                         equ 0001h
TRISB_RB4_MASK                           equ 0010h
TRISB_RB5_POSN                           equ 0005h
TRISB_RB5_POSITION                       equ 0005h
TRISB_RB5_SIZE                           equ 0001h
TRISB_RB5_LENGTH                         equ 0001h
TRISB_RB5_MASK                           equ 0020h
TRISB_RB6_POSN                           equ 0006h
TRISB_RB6_POSITION                       equ 0006h
TRISB_RB6_SIZE                           equ 0001h
TRISB_RB6_LENGTH                         equ 0001h
TRISB_RB6_MASK                           equ 0040h
TRISB_RB7_POSN                           equ 0007h
TRISB_RB7_POSITION                       equ 0007h
TRISB_RB7_SIZE                           equ 0001h
TRISB_RB7_LENGTH                         equ 0001h
TRISB_RB7_MASK                           equ 0080h

// Register: PTPERH
#define PTPERH PTPERH
PTPERH                                   equ 0F95h
// bitfield definitions
PTPERH_PTPERH_POSN                       equ 0000h
PTPERH_PTPERH_POSITION                   equ 0000h
PTPERH_PTPERH_SIZE                       equ 0004h
PTPERH_PTPERH_LENGTH                     equ 0004h
PTPERH_PTPERH_MASK                       equ 000Fh

// Register: PTPERL
#define PTPERL PTPERL
PTPERL                                   equ 0F96h
// bitfield definitions
PTPERL_PTPERL_POSN                       equ 0000h
PTPERL_PTPERL_POSITION                   equ 0000h
PTPERL_PTPERL_SIZE                       equ 0008h
PTPERL_PTPERL_LENGTH                     equ 0008h
PTPERL_PTPERL_MASK                       equ 00FFh

// Register: PTMRH
#define PTMRH PTMRH
PTMRH                                    equ 0F97h
// bitfield definitions
PTMRH_PTMRH_POSN                         equ 0000h
PTMRH_PTMRH_POSITION                     equ 0000h
PTMRH_PTMRH_SIZE                         equ 0004h
PTMRH_PTMRH_LENGTH                       equ 0004h
PTMRH_PTMRH_MASK                         equ 000Fh

// Register: PTMRL
#define PTMRL PTMRL
PTMRL                                    equ 0F98h
// bitfield definitions
PTMRL_PTMRL_POSN                         equ 0000h
PTMRL_PTMRL_POSITION                     equ 0000h
PTMRL_PTMRL_SIZE                         equ 0008h
PTMRL_PTMRL_LENGTH                       equ 0008h
PTMRL_PTMRL_MASK                         equ 00FFh

// Register: PTCON1
#define PTCON1 PTCON1
PTCON1                                   equ 0F99h
// bitfield definitions
PTCON1_PTDIR_POSN                        equ 0006h
PTCON1_PTDIR_POSITION                    equ 0006h
PTCON1_PTDIR_SIZE                        equ 0001h
PTCON1_PTDIR_LENGTH                      equ 0001h
PTCON1_PTDIR_MASK                        equ 0040h
PTCON1_PTEN_POSN                         equ 0007h
PTCON1_PTEN_POSITION                     equ 0007h
PTCON1_PTEN_SIZE                         equ 0001h
PTCON1_PTEN_LENGTH                       equ 0001h
PTCON1_PTEN_MASK                         equ 0080h

// Register: PTCON0
#define PTCON0 PTCON0
PTCON0                                   equ 0F9Ah
// bitfield definitions
PTCON0_PTMOD_POSN                        equ 0000h
PTCON0_PTMOD_POSITION                    equ 0000h
PTCON0_PTMOD_SIZE                        equ 0002h
PTCON0_PTMOD_LENGTH                      equ 0002h
PTCON0_PTMOD_MASK                        equ 0003h
PTCON0_PTCKPS_POSN                       equ 0002h
PTCON0_PTCKPS_POSITION                   equ 0002h
PTCON0_PTCKPS_SIZE                       equ 0002h
PTCON0_PTCKPS_LENGTH                     equ 0002h
PTCON0_PTCKPS_MASK                       equ 000Ch
PTCON0_PTOPS_POSN                        equ 0004h
PTCON0_PTOPS_POSITION                    equ 0004h
PTCON0_PTOPS_SIZE                        equ 0004h
PTCON0_PTOPS_LENGTH                      equ 0004h
PTCON0_PTOPS_MASK                        equ 00F0h
PTCON0_PTMOD0_POSN                       equ 0000h
PTCON0_PTMOD0_POSITION                   equ 0000h
PTCON0_PTMOD0_SIZE                       equ 0001h
PTCON0_PTMOD0_LENGTH                     equ 0001h
PTCON0_PTMOD0_MASK                       equ 0001h
PTCON0_PTMOD1_POSN                       equ 0001h
PTCON0_PTMOD1_POSITION                   equ 0001h
PTCON0_PTMOD1_SIZE                       equ 0001h
PTCON0_PTMOD1_LENGTH                     equ 0001h
PTCON0_PTMOD1_MASK                       equ 0002h
PTCON0_PTCKPS0_POSN                      equ 0002h
PTCON0_PTCKPS0_POSITION                  equ 0002h
PTCON0_PTCKPS0_SIZE                      equ 0001h
PTCON0_PTCKPS0_LENGTH                    equ 0001h
PTCON0_PTCKPS0_MASK                      equ 0004h
PTCON0_PTCKPS1_POSN                      equ 0003h
PTCON0_PTCKPS1_POSITION                  equ 0003h
PTCON0_PTCKPS1_SIZE                      equ 0001h
PTCON0_PTCKPS1_LENGTH                    equ 0001h
PTCON0_PTCKPS1_MASK                      equ 0008h
PTCON0_PTOPS0_POSN                       equ 0004h
PTCON0_PTOPS0_POSITION                   equ 0004h
PTCON0_PTOPS0_SIZE                       equ 0001h
PTCON0_PTOPS0_LENGTH                     equ 0001h
PTCON0_PTOPS0_MASK                       equ 0010h
PTCON0_PTOPS1_POSN                       equ 0005h
PTCON0_PTOPS1_POSITION                   equ 0005h
PTCON0_PTOPS1_SIZE                       equ 0001h
PTCON0_PTOPS1_LENGTH                     equ 0001h
PTCON0_PTOPS1_MASK                       equ 0020h
PTCON0_PTOPS2_POSN                       equ 0006h
PTCON0_PTOPS2_POSITION                   equ 0006h
PTCON0_PTOPS2_SIZE                       equ 0001h
PTCON0_PTOPS2_LENGTH                     equ 0001h
PTCON0_PTOPS2_MASK                       equ 0040h
PTCON0_PTOPS3_POSN                       equ 0007h
PTCON0_PTOPS3_POSITION                   equ 0007h
PTCON0_PTOPS3_SIZE                       equ 0001h
PTCON0_PTOPS3_LENGTH                     equ 0001h
PTCON0_PTOPS3_MASK                       equ 0080h

// Register: OSCTUNE
#define OSCTUNE OSCTUNE
OSCTUNE                                  equ 0F9Bh
// bitfield definitions
OSCTUNE_TUN_POSN                         equ 0000h
OSCTUNE_TUN_POSITION                     equ 0000h
OSCTUNE_TUN_SIZE                         equ 0005h
OSCTUNE_TUN_LENGTH                       equ 0005h
OSCTUNE_TUN_MASK                         equ 001Fh
OSCTUNE_PLLEN_POSN                       equ 0006h
OSCTUNE_PLLEN_POSITION                   equ 0006h
OSCTUNE_PLLEN_SIZE                       equ 0001h
OSCTUNE_PLLEN_LENGTH                     equ 0001h
OSCTUNE_PLLEN_MASK                       equ 0040h
OSCTUNE_INTSRC_POSN                      equ 0007h
OSCTUNE_INTSRC_POSITION                  equ 0007h
OSCTUNE_INTSRC_SIZE                      equ 0001h
OSCTUNE_INTSRC_LENGTH                    equ 0001h
OSCTUNE_INTSRC_MASK                      equ 0080h
OSCTUNE_TUN0_POSN                        equ 0000h
OSCTUNE_TUN0_POSITION                    equ 0000h
OSCTUNE_TUN0_SIZE                        equ 0001h
OSCTUNE_TUN0_LENGTH                      equ 0001h
OSCTUNE_TUN0_MASK                        equ 0001h
OSCTUNE_TUN1_POSN                        equ 0001h
OSCTUNE_TUN1_POSITION                    equ 0001h
OSCTUNE_TUN1_SIZE                        equ 0001h
OSCTUNE_TUN1_LENGTH                      equ 0001h
OSCTUNE_TUN1_MASK                        equ 0002h
OSCTUNE_TUN2_POSN                        equ 0002h
OSCTUNE_TUN2_POSITION                    equ 0002h
OSCTUNE_TUN2_SIZE                        equ 0001h
OSCTUNE_TUN2_LENGTH                      equ 0001h
OSCTUNE_TUN2_MASK                        equ 0004h
OSCTUNE_TUN3_POSN                        equ 0003h
OSCTUNE_TUN3_POSITION                    equ 0003h
OSCTUNE_TUN3_SIZE                        equ 0001h
OSCTUNE_TUN3_LENGTH                      equ 0001h
OSCTUNE_TUN3_MASK                        equ 0008h
OSCTUNE_TUN4_POSN                        equ 0004h
OSCTUNE_TUN4_POSITION                    equ 0004h
OSCTUNE_TUN4_SIZE                        equ 0001h
OSCTUNE_TUN4_LENGTH                      equ 0001h
OSCTUNE_TUN4_MASK                        equ 0010h

// Register: PIE1
#define PIE1 PIE1
PIE1                                     equ 0F9Dh
// bitfield definitions
PIE1_TMR1IE_POSN                         equ 0000h
PIE1_TMR1IE_POSITION                     equ 0000h
PIE1_TMR1IE_SIZE                         equ 0001h
PIE1_TMR1IE_LENGTH                       equ 0001h
PIE1_TMR1IE_MASK                         equ 0001h
PIE1_CMP0IE_POSN                         equ 0001h
PIE1_CMP0IE_POSITION                     equ 0001h
PIE1_CMP0IE_SIZE                         equ 0001h
PIE1_CMP0IE_LENGTH                       equ 0001h
PIE1_CMP0IE_MASK                         equ 0002h
PIE1_CMP1IE_POSN                         equ 0002h
PIE1_CMP1IE_POSITION                     equ 0002h
PIE1_CMP1IE_SIZE                         equ 0001h
PIE1_CMP1IE_LENGTH                       equ 0001h
PIE1_CMP1IE_MASK                         equ 0004h
PIE1_CMP2IE_POSN                         equ 0003h
PIE1_CMP2IE_POSITION                     equ 0003h
PIE1_CMP2IE_SIZE                         equ 0001h
PIE1_CMP2IE_LENGTH                       equ 0001h
PIE1_CMP2IE_MASK                         equ 0008h
PIE1_TXIE_POSN                           equ 0004h
PIE1_TXIE_POSITION                       equ 0004h
PIE1_TXIE_SIZE                           equ 0001h
PIE1_TXIE_LENGTH                         equ 0001h
PIE1_TXIE_MASK                           equ 0010h
PIE1_RCIE_POSN                           equ 0005h
PIE1_RCIE_POSITION                       equ 0005h
PIE1_RCIE_SIZE                           equ 0001h
PIE1_RCIE_LENGTH                         equ 0001h
PIE1_RCIE_MASK                           equ 0020h
PIE1_ADIE_POSN                           equ 0006h
PIE1_ADIE_POSITION                       equ 0006h
PIE1_ADIE_SIZE                           equ 0001h
PIE1_ADIE_LENGTH                         equ 0001h
PIE1_ADIE_MASK                           equ 0040h
PIE1_TX1IE_POSN                          equ 0004h
PIE1_TX1IE_POSITION                      equ 0004h
PIE1_TX1IE_SIZE                          equ 0001h
PIE1_TX1IE_LENGTH                        equ 0001h
PIE1_TX1IE_MASK                          equ 0010h
PIE1_RC1IE_POSN                          equ 0005h
PIE1_RC1IE_POSITION                      equ 0005h
PIE1_RC1IE_SIZE                          equ 0001h
PIE1_RC1IE_LENGTH                        equ 0001h
PIE1_RC1IE_MASK                          equ 0020h

// Register: PIR1
#define PIR1 PIR1
PIR1                                     equ 0F9Eh
// bitfield definitions
PIR1_TMR1IF_POSN                         equ 0000h
PIR1_TMR1IF_POSITION                     equ 0000h
PIR1_TMR1IF_SIZE                         equ 0001h
PIR1_TMR1IF_LENGTH                       equ 0001h
PIR1_TMR1IF_MASK                         equ 0001h
PIR1_CMP0IF_POSN                         equ 0001h
PIR1_CMP0IF_POSITION                     equ 0001h
PIR1_CMP0IF_SIZE                         equ 0001h
PIR1_CMP0IF_LENGTH                       equ 0001h
PIR1_CMP0IF_MASK                         equ 0002h
PIR1_CMP1IF_POSN                         equ 0002h
PIR1_CMP1IF_POSITION                     equ 0002h
PIR1_CMP1IF_SIZE                         equ 0001h
PIR1_CMP1IF_LENGTH                       equ 0001h
PIR1_CMP1IF_MASK                         equ 0004h
PIR1_CMP2IF_POSN                         equ 0003h
PIR1_CMP2IF_POSITION                     equ 0003h
PIR1_CMP2IF_SIZE                         equ 0001h
PIR1_CMP2IF_LENGTH                       equ 0001h
PIR1_CMP2IF_MASK                         equ 0008h
PIR1_TXIF_POSN                           equ 0004h
PIR1_TXIF_POSITION                       equ 0004h
PIR1_TXIF_SIZE                           equ 0001h
PIR1_TXIF_LENGTH                         equ 0001h
PIR1_TXIF_MASK                           equ 0010h
PIR1_RCIF_POSN                           equ 0005h
PIR1_RCIF_POSITION                       equ 0005h
PIR1_RCIF_SIZE                           equ 0001h
PIR1_RCIF_LENGTH                         equ 0001h
PIR1_RCIF_MASK                           equ 0020h
PIR1_ADIF_POSN                           equ 0006h
PIR1_ADIF_POSITION                       equ 0006h
PIR1_ADIF_SIZE                           equ 0001h
PIR1_ADIF_LENGTH                         equ 0001h
PIR1_ADIF_MASK                           equ 0040h
PIR1_TX1IF_POSN                          equ 0004h
PIR1_TX1IF_POSITION                      equ 0004h
PIR1_TX1IF_SIZE                          equ 0001h
PIR1_TX1IF_LENGTH                        equ 0001h
PIR1_TX1IF_MASK                          equ 0010h
PIR1_RC1IF_POSN                          equ 0005h
PIR1_RC1IF_POSITION                      equ 0005h
PIR1_RC1IF_SIZE                          equ 0001h
PIR1_RC1IF_LENGTH                        equ 0001h
PIR1_RC1IF_MASK                          equ 0020h

// Register: IPR1
#define IPR1 IPR1
IPR1                                     equ 0F9Fh
// bitfield definitions
IPR1_TMR1IP_POSN                         equ 0000h
IPR1_TMR1IP_POSITION                     equ 0000h
IPR1_TMR1IP_SIZE                         equ 0001h
IPR1_TMR1IP_LENGTH                       equ 0001h
IPR1_TMR1IP_MASK                         equ 0001h
IPR1_CMP0IP_POSN                         equ 0001h
IPR1_CMP0IP_POSITION                     equ 0001h
IPR1_CMP0IP_SIZE                         equ 0001h
IPR1_CMP0IP_LENGTH                       equ 0001h
IPR1_CMP0IP_MASK                         equ 0002h
IPR1_CMP1IP_POSN                         equ 0002h
IPR1_CMP1IP_POSITION                     equ 0002h
IPR1_CMP1IP_SIZE                         equ 0001h
IPR1_CMP1IP_LENGTH                       equ 0001h
IPR1_CMP1IP_MASK                         equ 0004h
IPR1_CMP2IP_POSN                         equ 0003h
IPR1_CMP2IP_POSITION                     equ 0003h
IPR1_CMP2IP_SIZE                         equ 0001h
IPR1_CMP2IP_LENGTH                       equ 0001h
IPR1_CMP2IP_MASK                         equ 0008h
IPR1_TXIP_POSN                           equ 0004h
IPR1_TXIP_POSITION                       equ 0004h
IPR1_TXIP_SIZE                           equ 0001h
IPR1_TXIP_LENGTH                         equ 0001h
IPR1_TXIP_MASK                           equ 0010h
IPR1_RCIP_POSN                           equ 0005h
IPR1_RCIP_POSITION                       equ 0005h
IPR1_RCIP_SIZE                           equ 0001h
IPR1_RCIP_LENGTH                         equ 0001h
IPR1_RCIP_MASK                           equ 0020h
IPR1_ADIP_POSN                           equ 0006h
IPR1_ADIP_POSITION                       equ 0006h
IPR1_ADIP_SIZE                           equ 0001h
IPR1_ADIP_LENGTH                         equ 0001h
IPR1_ADIP_MASK                           equ 0040h
IPR1_TX1IP_POSN                          equ 0004h
IPR1_TX1IP_POSITION                      equ 0004h
IPR1_TX1IP_SIZE                          equ 0001h
IPR1_TX1IP_LENGTH                        equ 0001h
IPR1_TX1IP_MASK                          equ 0010h
IPR1_RC1IP_POSN                          equ 0005h
IPR1_RC1IP_POSITION                      equ 0005h
IPR1_RC1IP_SIZE                          equ 0001h
IPR1_RC1IP_LENGTH                        equ 0001h
IPR1_RC1IP_MASK                          equ 0020h

// Register: PIE2
#define PIE2 PIE2
PIE2                                     equ 0FA0h
// bitfield definitions
PIE2_LVDIE_POSN                          equ 0002h
PIE2_LVDIE_POSITION                      equ 0002h
PIE2_LVDIE_SIZE                          equ 0001h
PIE2_LVDIE_LENGTH                        equ 0001h
PIE2_LVDIE_MASK                          equ 0004h
PIE2_EEIE_POSN                           equ 0004h
PIE2_EEIE_POSITION                       equ 0004h
PIE2_EEIE_SIZE                           equ 0001h
PIE2_EEIE_LENGTH                         equ 0001h
PIE2_EEIE_MASK                           equ 0010h
PIE2_OSCFIE_POSN                         equ 0007h
PIE2_OSCFIE_POSITION                     equ 0007h
PIE2_OSCFIE_SIZE                         equ 0001h
PIE2_OSCFIE_LENGTH                       equ 0001h
PIE2_OSCFIE_MASK                         equ 0080h

// Register: PIR2
#define PIR2 PIR2
PIR2                                     equ 0FA1h
// bitfield definitions
PIR2_LVDIF_POSN                          equ 0002h
PIR2_LVDIF_POSITION                      equ 0002h
PIR2_LVDIF_SIZE                          equ 0001h
PIR2_LVDIF_LENGTH                        equ 0001h
PIR2_LVDIF_MASK                          equ 0004h
PIR2_EEIF_POSN                           equ 0004h
PIR2_EEIF_POSITION                       equ 0004h
PIR2_EEIF_SIZE                           equ 0001h
PIR2_EEIF_LENGTH                         equ 0001h
PIR2_EEIF_MASK                           equ 0010h
PIR2_OSCFIF_POSN                         equ 0007h
PIR2_OSCFIF_POSITION                     equ 0007h
PIR2_OSCFIF_SIZE                         equ 0001h
PIR2_OSCFIF_LENGTH                       equ 0001h
PIR2_OSCFIF_MASK                         equ 0080h

// Register: IPR2
#define IPR2 IPR2
IPR2                                     equ 0FA2h
// bitfield definitions
IPR2_LVDIP_POSN                          equ 0002h
IPR2_LVDIP_POSITION                      equ 0002h
IPR2_LVDIP_SIZE                          equ 0001h
IPR2_LVDIP_LENGTH                        equ 0001h
IPR2_LVDIP_MASK                          equ 0004h
IPR2_EEIP_POSN                           equ 0004h
IPR2_EEIP_POSITION                       equ 0004h
IPR2_EEIP_SIZE                           equ 0001h
IPR2_EEIP_LENGTH                         equ 0001h
IPR2_EEIP_MASK                           equ 0010h
IPR2_OSCFIP_POSN                         equ 0007h
IPR2_OSCFIP_POSITION                     equ 0007h
IPR2_OSCFIP_SIZE                         equ 0001h
IPR2_OSCFIP_LENGTH                       equ 0001h
IPR2_OSCFIP_MASK                         equ 0080h

// Register: PIE3
#define PIE3 PIE3
PIE3                                     equ 0FA3h
// bitfield definitions
PIE3_PTIE_POSN                           equ 0004h
PIE3_PTIE_POSITION                       equ 0004h
PIE3_PTIE_SIZE                           equ 0001h
PIE3_PTIE_LENGTH                         equ 0001h
PIE3_PTIE_MASK                           equ 0010h
PIE3_TXB2IE_POSN                         equ 0004h
PIE3_TXB2IE_POSITION                     equ 0004h
PIE3_TXB2IE_SIZE                         equ 0001h
PIE3_TXB2IE_LENGTH                       equ 0001h
PIE3_TXB2IE_MASK                         equ 0010h
PIE3_TXBNIE_POSN                         equ 0004h
PIE3_TXBNIE_POSITION                     equ 0004h
PIE3_TXBNIE_SIZE                         equ 0001h
PIE3_TXBNIE_LENGTH                       equ 0001h
PIE3_TXBNIE_MASK                         equ 0010h

// Register: PIR3
#define PIR3 PIR3
PIR3                                     equ 0FA4h
// bitfield definitions
PIR3_PTIF_POSN                           equ 0004h
PIR3_PTIF_POSITION                       equ 0004h
PIR3_PTIF_SIZE                           equ 0001h
PIR3_PTIF_LENGTH                         equ 0001h
PIR3_PTIF_MASK                           equ 0010h
PIR3_TXBNIF_POSN                         equ 0004h
PIR3_TXBNIF_POSITION                     equ 0004h
PIR3_TXBNIF_SIZE                         equ 0001h
PIR3_TXBNIF_LENGTH                       equ 0001h
PIR3_TXBNIF_MASK                         equ 0010h

// Register: IPR3
#define IPR3 IPR3
IPR3                                     equ 0FA5h
// bitfield definitions
IPR3_PTIP_POSN                           equ 0004h
IPR3_PTIP_POSITION                       equ 0004h
IPR3_PTIP_SIZE                           equ 0001h
IPR3_PTIP_LENGTH                         equ 0001h
IPR3_PTIP_MASK                           equ 0010h
IPR3_TXBNIP_POSN                         equ 0004h
IPR3_TXBNIP_POSITION                     equ 0004h
IPR3_TXBNIP_SIZE                         equ 0001h
IPR3_TXBNIP_LENGTH                       equ 0001h
IPR3_TXBNIP_MASK                         equ 0010h

// Register: EECON1
#define EECON1 EECON1
EECON1                                   equ 0FA6h
// bitfield definitions
EECON1_RD_POSN                           equ 0000h
EECON1_RD_POSITION                       equ 0000h
EECON1_RD_SIZE                           equ 0001h
EECON1_RD_LENGTH                         equ 0001h
EECON1_RD_MASK                           equ 0001h
EECON1_WR_POSN                           equ 0001h
EECON1_WR_POSITION                       equ 0001h
EECON1_WR_SIZE                           equ 0001h
EECON1_WR_LENGTH                         equ 0001h
EECON1_WR_MASK                           equ 0002h
EECON1_WREN_POSN                         equ 0002h
EECON1_WREN_POSITION                     equ 0002h
EECON1_WREN_SIZE                         equ 0001h
EECON1_WREN_LENGTH                       equ 0001h
EECON1_WREN_MASK                         equ 0004h
EECON1_WRERR_POSN                        equ 0003h
EECON1_WRERR_POSITION                    equ 0003h
EECON1_WRERR_SIZE                        equ 0001h
EECON1_WRERR_LENGTH                      equ 0001h
EECON1_WRERR_MASK                        equ 0008h
EECON1_FREE_POSN                         equ 0004h
EECON1_FREE_POSITION                     equ 0004h
EECON1_FREE_SIZE                         equ 0001h
EECON1_FREE_LENGTH                       equ 0001h
EECON1_FREE_MASK                         equ 0010h
EECON1_CFGS_POSN                         equ 0006h
EECON1_CFGS_POSITION                     equ 0006h
EECON1_CFGS_SIZE                         equ 0001h
EECON1_CFGS_LENGTH                       equ 0001h
EECON1_CFGS_MASK                         equ 0040h
EECON1_EEPGD_POSN                        equ 0007h
EECON1_EEPGD_POSITION                    equ 0007h
EECON1_EEPGD_SIZE                        equ 0001h
EECON1_EEPGD_LENGTH                      equ 0001h
EECON1_EEPGD_MASK                        equ 0080h
EECON1_EEFS_POSN                         equ 0006h
EECON1_EEFS_POSITION                     equ 0006h
EECON1_EEFS_SIZE                         equ 0001h
EECON1_EEFS_LENGTH                       equ 0001h
EECON1_EEFS_MASK                         equ 0040h

// Register: EECON2
#define EECON2 EECON2
EECON2                                   equ 0FA7h

// Register: EEDATA
#define EEDATA EEDATA
EEDATA                                   equ 0FA8h

// Register: EEADR
#define EEADR EEADR
EEADR                                    equ 0FA9h

// Register: RCSTA
#define RCSTA RCSTA
RCSTA                                    equ 0FABh
// bitfield definitions
RCSTA_RX9D_POSN                          equ 0000h
RCSTA_RX9D_POSITION                      equ 0000h
RCSTA_RX9D_SIZE                          equ 0001h
RCSTA_RX9D_LENGTH                        equ 0001h
RCSTA_RX9D_MASK                          equ 0001h
RCSTA_OERR_POSN                          equ 0001h
RCSTA_OERR_POSITION                      equ 0001h
RCSTA_OERR_SIZE                          equ 0001h
RCSTA_OERR_LENGTH                        equ 0001h
RCSTA_OERR_MASK                          equ 0002h
RCSTA_FERR_POSN                          equ 0002h
RCSTA_FERR_POSITION                      equ 0002h
RCSTA_FERR_SIZE                          equ 0001h
RCSTA_FERR_LENGTH                        equ 0001h
RCSTA_FERR_MASK                          equ 0004h
RCSTA_ADEN_POSN                          equ 0003h
RCSTA_ADEN_POSITION                      equ 0003h
RCSTA_ADEN_SIZE                          equ 0001h
RCSTA_ADEN_LENGTH                        equ 0001h
RCSTA_ADEN_MASK                          equ 0008h
RCSTA_CREN_POSN                          equ 0004h
RCSTA_CREN_POSITION                      equ 0004h
RCSTA_CREN_SIZE                          equ 0001h
RCSTA_CREN_LENGTH                        equ 0001h
RCSTA_CREN_MASK                          equ 0010h
RCSTA_SREN_POSN                          equ 0005h
RCSTA_SREN_POSITION                      equ 0005h
RCSTA_SREN_SIZE                          equ 0001h
RCSTA_SREN_LENGTH                        equ 0001h
RCSTA_SREN_MASK                          equ 0020h
RCSTA_RX9_POSN                           equ 0006h
RCSTA_RX9_POSITION                       equ 0006h
RCSTA_RX9_SIZE                           equ 0001h
RCSTA_RX9_LENGTH                         equ 0001h
RCSTA_RX9_MASK                           equ 0040h
RCSTA_SPEN_POSN                          equ 0007h
RCSTA_SPEN_POSITION                      equ 0007h
RCSTA_SPEN_SIZE                          equ 0001h
RCSTA_SPEN_LENGTH                        equ 0001h
RCSTA_SPEN_MASK                          equ 0080h
RCSTA_ADDEN_POSN                         equ 0003h
RCSTA_ADDEN_POSITION                     equ 0003h
RCSTA_ADDEN_SIZE                         equ 0001h
RCSTA_ADDEN_LENGTH                       equ 0001h
RCSTA_ADDEN_MASK                         equ 0008h
RCSTA_SRENA_POSN                         equ 0005h
RCSTA_SRENA_POSITION                     equ 0005h
RCSTA_SRENA_SIZE                         equ 0001h
RCSTA_SRENA_LENGTH                       equ 0001h
RCSTA_SRENA_MASK                         equ 0020h
RCSTA_RC8_9_POSN                         equ 0006h
RCSTA_RC8_9_POSITION                     equ 0006h
RCSTA_RC8_9_SIZE                         equ 0001h
RCSTA_RC8_9_LENGTH                       equ 0001h
RCSTA_RC8_9_MASK                         equ 0040h
RCSTA_RC9_POSN                           equ 0006h
RCSTA_RC9_POSITION                       equ 0006h
RCSTA_RC9_SIZE                           equ 0001h
RCSTA_RC9_LENGTH                         equ 0001h
RCSTA_RC9_MASK                           equ 0040h
RCSTA_RCD8_POSN                          equ 0000h
RCSTA_RCD8_POSITION                      equ 0000h
RCSTA_RCD8_SIZE                          equ 0001h
RCSTA_RCD8_LENGTH                        equ 0001h
RCSTA_RCD8_MASK                          equ 0001h

// Register: TXSTA
#define TXSTA TXSTA
TXSTA                                    equ 0FACh
// bitfield definitions
TXSTA_TX9D_POSN                          equ 0000h
TXSTA_TX9D_POSITION                      equ 0000h
TXSTA_TX9D_SIZE                          equ 0001h
TXSTA_TX9D_LENGTH                        equ 0001h
TXSTA_TX9D_MASK                          equ 0001h
TXSTA_TRMT_POSN                          equ 0001h
TXSTA_TRMT_POSITION                      equ 0001h
TXSTA_TRMT_SIZE                          equ 0001h
TXSTA_TRMT_LENGTH                        equ 0001h
TXSTA_TRMT_MASK                          equ 0002h
TXSTA_BRGH_POSN                          equ 0002h
TXSTA_BRGH_POSITION                      equ 0002h
TXSTA_BRGH_SIZE                          equ 0001h
TXSTA_BRGH_LENGTH                        equ 0001h
TXSTA_BRGH_MASK                          equ 0004h
TXSTA_SENDB_POSN                         equ 0003h
TXSTA_SENDB_POSITION                     equ 0003h
TXSTA_SENDB_SIZE                         equ 0001h
TXSTA_SENDB_LENGTH                       equ 0001h
TXSTA_SENDB_MASK                         equ 0008h
TXSTA_SYNC_POSN                          equ 0004h
TXSTA_SYNC_POSITION                      equ 0004h
TXSTA_SYNC_SIZE                          equ 0001h
TXSTA_SYNC_LENGTH                        equ 0001h
TXSTA_SYNC_MASK                          equ 0010h
TXSTA_TXEN_POSN                          equ 0005h
TXSTA_TXEN_POSITION                      equ 0005h
TXSTA_TXEN_SIZE                          equ 0001h
TXSTA_TXEN_LENGTH                        equ 0001h
TXSTA_TXEN_MASK                          equ 0020h
TXSTA_TX9_POSN                           equ 0006h
TXSTA_TX9_POSITION                       equ 0006h
TXSTA_TX9_SIZE                           equ 0001h
TXSTA_TX9_LENGTH                         equ 0001h
TXSTA_TX9_MASK                           equ 0040h
TXSTA_CSRC_POSN                          equ 0007h
TXSTA_CSRC_POSITION                      equ 0007h
TXSTA_CSRC_SIZE                          equ 0001h
TXSTA_CSRC_LENGTH                        equ 0001h
TXSTA_CSRC_MASK                          equ 0080h
TXSTA_TX9D1_POSN                         equ 0000h
TXSTA_TX9D1_POSITION                     equ 0000h
TXSTA_TX9D1_SIZE                         equ 0001h
TXSTA_TX9D1_LENGTH                       equ 0001h
TXSTA_TX9D1_MASK                         equ 0001h
TXSTA_TRMT1_POSN                         equ 0001h
TXSTA_TRMT1_POSITION                     equ 0001h
TXSTA_TRMT1_SIZE                         equ 0001h
TXSTA_TRMT1_LENGTH                       equ 0001h
TXSTA_TRMT1_MASK                         equ 0002h
TXSTA_BRGH1_POSN                         equ 0002h
TXSTA_BRGH1_POSITION                     equ 0002h
TXSTA_BRGH1_SIZE                         equ 0001h
TXSTA_BRGH1_LENGTH                       equ 0001h
TXSTA_BRGH1_MASK                         equ 0004h
TXSTA_SENDB1_POSN                        equ 0003h
TXSTA_SENDB1_POSITION                    equ 0003h
TXSTA_SENDB1_SIZE                        equ 0001h
TXSTA_SENDB1_LENGTH                      equ 0001h
TXSTA_SENDB1_MASK                        equ 0008h
TXSTA_SYNC1_POSN                         equ 0004h
TXSTA_SYNC1_POSITION                     equ 0004h
TXSTA_SYNC1_SIZE                         equ 0001h
TXSTA_SYNC1_LENGTH                       equ 0001h
TXSTA_SYNC1_MASK                         equ 0010h
TXSTA_TXEN1_POSN                         equ 0005h
TXSTA_TXEN1_POSITION                     equ 0005h
TXSTA_TXEN1_SIZE                         equ 0001h
TXSTA_TXEN1_LENGTH                       equ 0001h
TXSTA_TXEN1_MASK                         equ 0020h
TXSTA_TX91_POSN                          equ 0006h
TXSTA_TX91_POSITION                      equ 0006h
TXSTA_TX91_SIZE                          equ 0001h
TXSTA_TX91_LENGTH                        equ 0001h
TXSTA_TX91_MASK                          equ 0040h
TXSTA_CSRC1_POSN                         equ 0007h
TXSTA_CSRC1_POSITION                     equ 0007h
TXSTA_CSRC1_SIZE                         equ 0001h
TXSTA_CSRC1_LENGTH                       equ 0001h
TXSTA_CSRC1_MASK                         equ 0080h
TXSTA_TX8_9_POSN                         equ 0006h
TXSTA_TX8_9_POSITION                     equ 0006h
TXSTA_TX8_9_SIZE                         equ 0001h
TXSTA_TX8_9_LENGTH                       equ 0001h
TXSTA_TX8_9_MASK                         equ 0040h
TXSTA_TXD8_POSN                          equ 0000h
TXSTA_TXD8_POSITION                      equ 0000h
TXSTA_TXD8_SIZE                          equ 0001h
TXSTA_TXD8_LENGTH                        equ 0001h
TXSTA_TXD8_MASK                          equ 0001h

// Register: TXREG
#define TXREG TXREG
TXREG                                    equ 0FADh

// Register: RCREG
#define RCREG RCREG
RCREG                                    equ 0FAEh

// Register: SPBRG
#define SPBRG SPBRG
SPBRG                                    equ 0FAFh

// Register: SPBRGH
#define SPBRGH SPBRGH
SPBRGH                                   equ 0FB0h

// Register: CMCON
#define CMCON CMCON
CMCON                                    equ 0FB4h
// bitfield definitions
CMCON_CMEN_POSN                          equ 0000h
CMCON_CMEN_POSITION                      equ 0000h
CMCON_CMEN_SIZE                          equ 0003h
CMCON_CMEN_LENGTH                        equ 0003h
CMCON_CMEN_MASK                          equ 0007h
CMCON_C0OUT_POSN                         equ 0005h
CMCON_C0OUT_POSITION                     equ 0005h
CMCON_C0OUT_SIZE                         equ 0001h
CMCON_C0OUT_LENGTH                       equ 0001h
CMCON_C0OUT_MASK                         equ 0020h
CMCON_C1OUT_POSN                         equ 0006h
CMCON_C1OUT_POSITION                     equ 0006h
CMCON_C1OUT_SIZE                         equ 0001h
CMCON_C1OUT_LENGTH                       equ 0001h
CMCON_C1OUT_MASK                         equ 0040h
CMCON_C2OUT_POSN                         equ 0007h
CMCON_C2OUT_POSITION                     equ 0007h
CMCON_C2OUT_SIZE                         equ 0001h
CMCON_C2OUT_LENGTH                       equ 0001h
CMCON_C2OUT_MASK                         equ 0080h
CMCON_CMEN0_POSN                         equ 0000h
CMCON_CMEN0_POSITION                     equ 0000h
CMCON_CMEN0_SIZE                         equ 0001h
CMCON_CMEN0_LENGTH                       equ 0001h
CMCON_CMEN0_MASK                         equ 0001h
CMCON_CMEN1_POSN                         equ 0001h
CMCON_CMEN1_POSITION                     equ 0001h
CMCON_CMEN1_SIZE                         equ 0001h
CMCON_CMEN1_LENGTH                       equ 0001h
CMCON_CMEN1_MASK                         equ 0002h
CMCON_CMEN2_POSN                         equ 0002h
CMCON_CMEN2_POSITION                     equ 0002h
CMCON_CMEN2_SIZE                         equ 0001h
CMCON_CMEN2_LENGTH                       equ 0001h
CMCON_CMEN2_MASK                         equ 0004h
CMCON_CM0_POSN                           equ 0000h
CMCON_CM0_POSITION                       equ 0000h
CMCON_CM0_SIZE                           equ 0001h
CMCON_CM0_LENGTH                         equ 0001h
CMCON_CM0_MASK                           equ 0001h
CMCON_CM1_POSN                           equ 0001h
CMCON_CM1_POSITION                       equ 0001h
CMCON_CM1_SIZE                           equ 0001h
CMCON_CM1_LENGTH                         equ 0001h
CMCON_CM1_MASK                           equ 0002h
CMCON_CM2_POSN                           equ 0002h
CMCON_CM2_POSITION                       equ 0002h
CMCON_CM2_SIZE                           equ 0001h
CMCON_CM2_LENGTH                         equ 0001h
CMCON_CM2_MASK                           equ 0004h
CMCON_C2INV_POSN                         equ 0005h
CMCON_C2INV_POSITION                     equ 0005h
CMCON_C2INV_SIZE                         equ 0001h
CMCON_C2INV_LENGTH                       equ 0001h
CMCON_C2INV_MASK                         equ 0020h

// Register: CVRCON
#define CVRCON CVRCON
CVRCON                                   equ 0FB5h
// bitfield definitions
CVRCON_CVR_POSN                          equ 0000h
CVRCON_CVR_POSITION                      equ 0000h
CVRCON_CVR_SIZE                          equ 0004h
CVRCON_CVR_LENGTH                        equ 0004h
CVRCON_CVR_MASK                          equ 000Fh
CVRCON_CVRSS_POSN                        equ 0004h
CVRCON_CVRSS_POSITION                    equ 0004h
CVRCON_CVRSS_SIZE                        equ 0001h
CVRCON_CVRSS_LENGTH                      equ 0001h
CVRCON_CVRSS_MASK                        equ 0010h
CVRCON_CVRR_POSN                         equ 0005h
CVRCON_CVRR_POSITION                     equ 0005h
CVRCON_CVRR_SIZE                         equ 0001h
CVRCON_CVRR_LENGTH                       equ 0001h
CVRCON_CVRR_MASK                         equ 0020h
CVRCON_CVREN_POSN                        equ 0007h
CVRCON_CVREN_POSITION                    equ 0007h
CVRCON_CVREN_SIZE                        equ 0001h
CVRCON_CVREN_LENGTH                      equ 0001h
CVRCON_CVREN_MASK                        equ 0080h
CVRCON_CVR0_POSN                         equ 0000h
CVRCON_CVR0_POSITION                     equ 0000h
CVRCON_CVR0_SIZE                         equ 0001h
CVRCON_CVR0_LENGTH                       equ 0001h
CVRCON_CVR0_MASK                         equ 0001h
CVRCON_CVR1_POSN                         equ 0001h
CVRCON_CVR1_POSITION                     equ 0001h
CVRCON_CVR1_SIZE                         equ 0001h
CVRCON_CVR1_LENGTH                       equ 0001h
CVRCON_CVR1_MASK                         equ 0002h
CVRCON_CVR2_POSN                         equ 0002h
CVRCON_CVR2_POSITION                     equ 0002h
CVRCON_CVR2_SIZE                         equ 0001h
CVRCON_CVR2_LENGTH                       equ 0001h
CVRCON_CVR2_MASK                         equ 0004h
CVRCON_CVR3_POSN                         equ 0003h
CVRCON_CVR3_POSITION                     equ 0003h
CVRCON_CVR3_SIZE                         equ 0001h
CVRCON_CVR3_LENGTH                       equ 0001h
CVRCON_CVR3_MASK                         equ 0008h
CVRCON_CVREF_POSN                        equ 0004h
CVRCON_CVREF_POSITION                    equ 0004h
CVRCON_CVREF_SIZE                        equ 0001h
CVRCON_CVREF_LENGTH                      equ 0001h
CVRCON_CVREF_MASK                        equ 0010h

// Register: BAUDCON
#define BAUDCON BAUDCON
BAUDCON                                  equ 0FB8h
// bitfield definitions
BAUDCON_ABDEN_POSN                       equ 0000h
BAUDCON_ABDEN_POSITION                   equ 0000h
BAUDCON_ABDEN_SIZE                       equ 0001h
BAUDCON_ABDEN_LENGTH                     equ 0001h
BAUDCON_ABDEN_MASK                       equ 0001h
BAUDCON_WUE_POSN                         equ 0001h
BAUDCON_WUE_POSITION                     equ 0001h
BAUDCON_WUE_SIZE                         equ 0001h
BAUDCON_WUE_LENGTH                       equ 0001h
BAUDCON_WUE_MASK                         equ 0002h
BAUDCON_BRG16_POSN                       equ 0003h
BAUDCON_BRG16_POSITION                   equ 0003h
BAUDCON_BRG16_SIZE                       equ 0001h
BAUDCON_BRG16_LENGTH                     equ 0001h
BAUDCON_BRG16_MASK                       equ 0008h
BAUDCON_TXCKP_POSN                       equ 0004h
BAUDCON_TXCKP_POSITION                   equ 0004h
BAUDCON_TXCKP_SIZE                       equ 0001h
BAUDCON_TXCKP_LENGTH                     equ 0001h
BAUDCON_TXCKP_MASK                       equ 0010h
BAUDCON_RXDTP_POSN                       equ 0005h
BAUDCON_RXDTP_POSITION                   equ 0005h
BAUDCON_RXDTP_SIZE                       equ 0001h
BAUDCON_RXDTP_LENGTH                     equ 0001h
BAUDCON_RXDTP_MASK                       equ 0020h
BAUDCON_RCIDL_POSN                       equ 0006h
BAUDCON_RCIDL_POSITION                   equ 0006h
BAUDCON_RCIDL_SIZE                       equ 0001h
BAUDCON_RCIDL_LENGTH                     equ 0001h
BAUDCON_RCIDL_MASK                       equ 0040h
BAUDCON_ABDOVF_POSN                      equ 0007h
BAUDCON_ABDOVF_POSITION                  equ 0007h
BAUDCON_ABDOVF_SIZE                      equ 0001h
BAUDCON_ABDOVF_LENGTH                    equ 0001h
BAUDCON_ABDOVF_MASK                      equ 0080h
BAUDCON_SCKP_POSN                        equ 0004h
BAUDCON_SCKP_POSITION                    equ 0004h
BAUDCON_SCKP_SIZE                        equ 0001h
BAUDCON_SCKP_LENGTH                      equ 0001h
BAUDCON_SCKP_MASK                        equ 0010h
BAUDCON_RCMT_POSN                        equ 0006h
BAUDCON_RCMT_POSITION                    equ 0006h
BAUDCON_RCMT_SIZE                        equ 0001h
BAUDCON_RCMT_LENGTH                      equ 0001h
BAUDCON_RCMT_MASK                        equ 0040h
BAUDCON_RXCKP_POSN                       equ 0005h
BAUDCON_RXCKP_POSITION                   equ 0005h
BAUDCON_RXCKP_SIZE                       equ 0001h
BAUDCON_RXCKP_LENGTH                     equ 0001h
BAUDCON_RXCKP_MASK                       equ 0020h
BAUDCON_W4E_POSN                         equ 0001h
BAUDCON_W4E_POSITION                     equ 0001h
BAUDCON_W4E_SIZE                         equ 0001h
BAUDCON_W4E_LENGTH                       equ 0001h
BAUDCON_W4E_MASK                         equ 0002h

// Register: ADCON2
#define ADCON2 ADCON2
ADCON2                                   equ 0FC0h
// bitfield definitions
ADCON2_ADCS_POSN                         equ 0000h
ADCON2_ADCS_POSITION                     equ 0000h
ADCON2_ADCS_SIZE                         equ 0003h
ADCON2_ADCS_LENGTH                       equ 0003h
ADCON2_ADCS_MASK                         equ 0007h
ADCON2_ACQT_POSN                         equ 0003h
ADCON2_ACQT_POSITION                     equ 0003h
ADCON2_ACQT_SIZE                         equ 0003h
ADCON2_ACQT_LENGTH                       equ 0003h
ADCON2_ACQT_MASK                         equ 0038h
ADCON2_ADFM_POSN                         equ 0007h
ADCON2_ADFM_POSITION                     equ 0007h
ADCON2_ADFM_SIZE                         equ 0001h
ADCON2_ADFM_LENGTH                       equ 0001h
ADCON2_ADFM_MASK                         equ 0080h
ADCON2_ADCS0_POSN                        equ 0000h
ADCON2_ADCS0_POSITION                    equ 0000h
ADCON2_ADCS0_SIZE                        equ 0001h
ADCON2_ADCS0_LENGTH                      equ 0001h
ADCON2_ADCS0_MASK                        equ 0001h
ADCON2_ADCS1_POSN                        equ 0001h
ADCON2_ADCS1_POSITION                    equ 0001h
ADCON2_ADCS1_SIZE                        equ 0001h
ADCON2_ADCS1_LENGTH                      equ 0001h
ADCON2_ADCS1_MASK                        equ 0002h
ADCON2_ADCS2_POSN                        equ 0002h
ADCON2_ADCS2_POSITION                    equ 0002h
ADCON2_ADCS2_SIZE                        equ 0001h
ADCON2_ADCS2_LENGTH                      equ 0001h
ADCON2_ADCS2_MASK                        equ 0004h
ADCON2_ACQT0_POSN                        equ 0003h
ADCON2_ACQT0_POSITION                    equ 0003h
ADCON2_ACQT0_SIZE                        equ 0001h
ADCON2_ACQT0_LENGTH                      equ 0001h
ADCON2_ACQT0_MASK                        equ 0008h
ADCON2_ACQT1_POSN                        equ 0004h
ADCON2_ACQT1_POSITION                    equ 0004h
ADCON2_ACQT1_SIZE                        equ 0001h
ADCON2_ACQT1_LENGTH                      equ 0001h
ADCON2_ACQT1_MASK                        equ 0010h
ADCON2_ACQT2_POSN                        equ 0005h
ADCON2_ACQT2_POSITION                    equ 0005h
ADCON2_ACQT2_SIZE                        equ 0001h
ADCON2_ACQT2_LENGTH                      equ 0001h
ADCON2_ACQT2_MASK                        equ 0020h

// Register: ADCON1
#define ADCON1 ADCON1
ADCON1                                   equ 0FC1h
// bitfield definitions
ADCON1_PCFG_POSN                         equ 0000h
ADCON1_PCFG_POSITION                     equ 0000h
ADCON1_PCFG_SIZE                         equ 0004h
ADCON1_PCFG_LENGTH                       equ 0004h
ADCON1_PCFG_MASK                         equ 000Fh
ADCON1_VCFG_POSN                         equ 0004h
ADCON1_VCFG_POSITION                     equ 0004h
ADCON1_VCFG_SIZE                         equ 0001h
ADCON1_VCFG_LENGTH                       equ 0001h
ADCON1_VCFG_MASK                         equ 0010h
ADCON1_PCFG0_POSN                        equ 0000h
ADCON1_PCFG0_POSITION                    equ 0000h
ADCON1_PCFG0_SIZE                        equ 0001h
ADCON1_PCFG0_LENGTH                      equ 0001h
ADCON1_PCFG0_MASK                        equ 0001h
ADCON1_PCFG1_POSN                        equ 0001h
ADCON1_PCFG1_POSITION                    equ 0001h
ADCON1_PCFG1_SIZE                        equ 0001h
ADCON1_PCFG1_LENGTH                      equ 0001h
ADCON1_PCFG1_MASK                        equ 0002h
ADCON1_PCFG2_POSN                        equ 0002h
ADCON1_PCFG2_POSITION                    equ 0002h
ADCON1_PCFG2_SIZE                        equ 0001h
ADCON1_PCFG2_LENGTH                      equ 0001h
ADCON1_PCFG2_MASK                        equ 0004h
ADCON1_PCFG3_POSN                        equ 0003h
ADCON1_PCFG3_POSITION                    equ 0003h
ADCON1_PCFG3_SIZE                        equ 0001h
ADCON1_PCFG3_LENGTH                      equ 0001h
ADCON1_PCFG3_MASK                        equ 0008h
ADCON1_VCFG0_POSN                        equ 0004h
ADCON1_VCFG0_POSITION                    equ 0004h
ADCON1_VCFG0_SIZE                        equ 0001h
ADCON1_VCFG0_LENGTH                      equ 0001h
ADCON1_VCFG0_MASK                        equ 0010h
ADCON1_CHSN3_POSN                        equ 0003h
ADCON1_CHSN3_POSITION                    equ 0003h
ADCON1_CHSN3_SIZE                        equ 0001h
ADCON1_CHSN3_LENGTH                      equ 0001h
ADCON1_CHSN3_MASK                        equ 0008h
ADCON1_VCFG01_POSN                       equ 0004h
ADCON1_VCFG01_POSITION                   equ 0004h
ADCON1_VCFG01_SIZE                       equ 0001h
ADCON1_VCFG01_LENGTH                     equ 0001h
ADCON1_VCFG01_MASK                       equ 0010h

// Register: ADCON0
#define ADCON0 ADCON0
ADCON0                                   equ 0FC2h
// bitfield definitions
ADCON0_GO_NOT_DONE_POSN                  equ 0001h
ADCON0_GO_NOT_DONE_POSITION              equ 0001h
ADCON0_GO_NOT_DONE_SIZE                  equ 0001h
ADCON0_GO_NOT_DONE_LENGTH                equ 0001h
ADCON0_GO_NOT_DONE_MASK                  equ 0002h
ADCON0_ADON_POSN                         equ 0000h
ADCON0_ADON_POSITION                     equ 0000h
ADCON0_ADON_SIZE                         equ 0001h
ADCON0_ADON_LENGTH                       equ 0001h
ADCON0_ADON_MASK                         equ 0001h
ADCON0_GO_nDONE_POSN                     equ 0001h
ADCON0_GO_nDONE_POSITION                 equ 0001h
ADCON0_GO_nDONE_SIZE                     equ 0001h
ADCON0_GO_nDONE_LENGTH                   equ 0001h
ADCON0_GO_nDONE_MASK                     equ 0002h
ADCON0_CHS_POSN                          equ 0002h
ADCON0_CHS_POSITION                      equ 0002h
ADCON0_CHS_SIZE                          equ 0002h
ADCON0_CHS_LENGTH                        equ 0002h
ADCON0_CHS_MASK                          equ 000Ch
ADCON0_SEVTEN_POSN                       equ 0007h
ADCON0_SEVTEN_POSITION                   equ 0007h
ADCON0_SEVTEN_SIZE                       equ 0001h
ADCON0_SEVTEN_LENGTH                     equ 0001h
ADCON0_SEVTEN_MASK                       equ 0080h
ADCON0_GO_POSN                           equ 0001h
ADCON0_GO_POSITION                       equ 0001h
ADCON0_GO_SIZE                           equ 0001h
ADCON0_GO_LENGTH                         equ 0001h
ADCON0_GO_MASK                           equ 0002h
ADCON0_CHS0_POSN                         equ 0002h
ADCON0_CHS0_POSITION                     equ 0002h
ADCON0_CHS0_SIZE                         equ 0001h
ADCON0_CHS0_LENGTH                       equ 0001h
ADCON0_CHS0_MASK                         equ 0004h
ADCON0_CHS1_POSN                         equ 0003h
ADCON0_CHS1_POSITION                     equ 0003h
ADCON0_CHS1_SIZE                         equ 0001h
ADCON0_CHS1_LENGTH                       equ 0001h
ADCON0_CHS1_MASK                         equ 0008h
ADCON0_DONE_POSN                         equ 0001h
ADCON0_DONE_POSITION                     equ 0001h
ADCON0_DONE_SIZE                         equ 0001h
ADCON0_DONE_LENGTH                       equ 0001h
ADCON0_DONE_MASK                         equ 0002h
ADCON0_NOT_DONE_POSN                     equ 0001h
ADCON0_NOT_DONE_POSITION                 equ 0001h
ADCON0_NOT_DONE_SIZE                     equ 0001h
ADCON0_NOT_DONE_LENGTH                   equ 0001h
ADCON0_NOT_DONE_MASK                     equ 0002h
ADCON0_nDONE_POSN                        equ 0001h
ADCON0_nDONE_POSITION                    equ 0001h
ADCON0_nDONE_SIZE                        equ 0001h
ADCON0_nDONE_LENGTH                      equ 0001h
ADCON0_nDONE_MASK                        equ 0002h
ADCON0_GO_DONE_POSN                      equ 0001h
ADCON0_GO_DONE_POSITION                  equ 0001h
ADCON0_GO_DONE_SIZE                      equ 0001h
ADCON0_GO_DONE_LENGTH                    equ 0001h
ADCON0_GO_DONE_MASK                      equ 0002h
ADCON0_GODONE_POSN                       equ 0001h
ADCON0_GODONE_POSITION                   equ 0001h
ADCON0_GODONE_SIZE                       equ 0001h
ADCON0_GODONE_LENGTH                     equ 0001h
ADCON0_GODONE_MASK                       equ 0002h
ADCON0_ADCAL_POSN                        equ 0007h
ADCON0_ADCAL_POSITION                    equ 0007h
ADCON0_ADCAL_SIZE                        equ 0001h
ADCON0_ADCAL_LENGTH                      equ 0001h
ADCON0_ADCAL_MASK                        equ 0080h

// Register: ADRES
#define ADRES ADRES
ADRES                                    equ 0FC3h

// Register: ADRESL
#define ADRESL ADRESL
ADRESL                                   equ 0FC3h

// Register: ADRESH
#define ADRESH ADRESH
ADRESH                                   equ 0FC4h

// Register: T1CON
#define T1CON T1CON
T1CON                                    equ 0FCDh
// bitfield definitions
T1CON_NOT_T1SYNC_POSN                    equ 0002h
T1CON_NOT_T1SYNC_POSITION                equ 0002h
T1CON_NOT_T1SYNC_SIZE                    equ 0001h
T1CON_NOT_T1SYNC_LENGTH                  equ 0001h
T1CON_NOT_T1SYNC_MASK                    equ 0004h
T1CON_TMR1ON_POSN                        equ 0000h
T1CON_TMR1ON_POSITION                    equ 0000h
T1CON_TMR1ON_SIZE                        equ 0001h
T1CON_TMR1ON_LENGTH                      equ 0001h
T1CON_TMR1ON_MASK                        equ 0001h
T1CON_TMR1CS_POSN                        equ 0001h
T1CON_TMR1CS_POSITION                    equ 0001h
T1CON_TMR1CS_SIZE                        equ 0001h
T1CON_TMR1CS_LENGTH                      equ 0001h
T1CON_TMR1CS_MASK                        equ 0002h
T1CON_nT1SYNC_POSN                       equ 0002h
T1CON_nT1SYNC_POSITION                   equ 0002h
T1CON_nT1SYNC_SIZE                       equ 0001h
T1CON_nT1SYNC_LENGTH                     equ 0001h
T1CON_nT1SYNC_MASK                       equ 0004h
T1CON_T1OSCEN_POSN                       equ 0003h
T1CON_T1OSCEN_POSITION                   equ 0003h
T1CON_T1OSCEN_SIZE                       equ 0001h
T1CON_T1OSCEN_LENGTH                     equ 0001h
T1CON_T1OSCEN_MASK                       equ 0008h
T1CON_T1CKPS_POSN                        equ 0004h
T1CON_T1CKPS_POSITION                    equ 0004h
T1CON_T1CKPS_SIZE                        equ 0002h
T1CON_T1CKPS_LENGTH                      equ 0002h
T1CON_T1CKPS_MASK                        equ 0030h
T1CON_T1RUN_POSN                         equ 0006h
T1CON_T1RUN_POSITION                     equ 0006h
T1CON_T1RUN_SIZE                         equ 0001h
T1CON_T1RUN_LENGTH                       equ 0001h
T1CON_T1RUN_MASK                         equ 0040h
T1CON_RD16_POSN                          equ 0007h
T1CON_RD16_POSITION                      equ 0007h
T1CON_RD16_SIZE                          equ 0001h
T1CON_RD16_LENGTH                        equ 0001h
T1CON_RD16_MASK                          equ 0080h
T1CON_T1CKPS0_POSN                       equ 0004h
T1CON_T1CKPS0_POSITION                   equ 0004h
T1CON_T1CKPS0_SIZE                       equ 0001h
T1CON_T1CKPS0_LENGTH                     equ 0001h
T1CON_T1CKPS0_MASK                       equ 0010h
T1CON_T1CKPS1_POSN                       equ 0005h
T1CON_T1CKPS1_POSITION                   equ 0005h
T1CON_T1CKPS1_SIZE                       equ 0001h
T1CON_T1CKPS1_LENGTH                     equ 0001h
T1CON_T1CKPS1_MASK                       equ 0020h
T1CON_T1SYNC_POSN                        equ 0002h
T1CON_T1SYNC_POSITION                    equ 0002h
T1CON_T1SYNC_SIZE                        equ 0001h
T1CON_T1SYNC_LENGTH                      equ 0001h
T1CON_T1SYNC_MASK                        equ 0004h
T1CON_SOSCEN_POSN                        equ 0003h
T1CON_SOSCEN_POSITION                    equ 0003h
T1CON_SOSCEN_SIZE                        equ 0001h
T1CON_SOSCEN_LENGTH                      equ 0001h
T1CON_SOSCEN_MASK                        equ 0008h
T1CON_T1RD16_POSN                        equ 0007h
T1CON_T1RD16_POSITION                    equ 0007h
T1CON_T1RD16_SIZE                        equ 0001h
T1CON_T1RD16_LENGTH                      equ 0001h
T1CON_T1RD16_MASK                        equ 0080h

// Register: TMR1
#define TMR1 TMR1
TMR1                                     equ 0FCEh

// Register: TMR1L
#define TMR1L TMR1L
TMR1L                                    equ 0FCEh

// Register: TMR1H
#define TMR1H TMR1H
TMR1H                                    equ 0FCFh

// Register: RCON
#define RCON RCON
RCON                                     equ 0FD0h
// bitfield definitions
RCON_NOT_BOR_POSN                        equ 0000h
RCON_NOT_BOR_POSITION                    equ 0000h
RCON_NOT_BOR_SIZE                        equ 0001h
RCON_NOT_BOR_LENGTH                      equ 0001h
RCON_NOT_BOR_MASK                        equ 0001h
RCON_NOT_POR_POSN                        equ 0001h
RCON_NOT_POR_POSITION                    equ 0001h
RCON_NOT_POR_SIZE                        equ 0001h
RCON_NOT_POR_LENGTH                      equ 0001h
RCON_NOT_POR_MASK                        equ 0002h
RCON_NOT_PD_POSN                         equ 0002h
RCON_NOT_PD_POSITION                     equ 0002h
RCON_NOT_PD_SIZE                         equ 0001h
RCON_NOT_PD_LENGTH                       equ 0001h
RCON_NOT_PD_MASK                         equ 0004h
RCON_NOT_TO_POSN                         equ 0003h
RCON_NOT_TO_POSITION                     equ 0003h
RCON_NOT_TO_SIZE                         equ 0001h
RCON_NOT_TO_LENGTH                       equ 0001h
RCON_NOT_TO_MASK                         equ 0008h
RCON_NOT_RI_POSN                         equ 0004h
RCON_NOT_RI_POSITION                     equ 0004h
RCON_NOT_RI_SIZE                         equ 0001h
RCON_NOT_RI_LENGTH                       equ 0001h
RCON_NOT_RI_MASK                         equ 0010h
RCON_nBOR_POSN                           equ 0000h
RCON_nBOR_POSITION                       equ 0000h
RCON_nBOR_SIZE                           equ 0001h
RCON_nBOR_LENGTH                         equ 0001h
RCON_nBOR_MASK                           equ 0001h
RCON_nPOR_POSN                           equ 0001h
RCON_nPOR_POSITION                       equ 0001h
RCON_nPOR_SIZE                           equ 0001h
RCON_nPOR_LENGTH                         equ 0001h
RCON_nPOR_MASK                           equ 0002h
RCON_nPD_POSN                            equ 0002h
RCON_nPD_POSITION                        equ 0002h
RCON_nPD_SIZE                            equ 0001h
RCON_nPD_LENGTH                          equ 0001h
RCON_nPD_MASK                            equ 0004h
RCON_nTO_POSN                            equ 0003h
RCON_nTO_POSITION                        equ 0003h
RCON_nTO_SIZE                            equ 0001h
RCON_nTO_LENGTH                          equ 0001h
RCON_nTO_MASK                            equ 0008h
RCON_nRI_POSN                            equ 0004h
RCON_nRI_POSITION                        equ 0004h
RCON_nRI_SIZE                            equ 0001h
RCON_nRI_LENGTH                          equ 0001h
RCON_nRI_MASK                            equ 0010h
RCON_SBOREN_POSN                         equ 0006h
RCON_SBOREN_POSITION                     equ 0006h
RCON_SBOREN_SIZE                         equ 0001h
RCON_SBOREN_LENGTH                       equ 0001h
RCON_SBOREN_MASK                         equ 0040h
RCON_IPEN_POSN                           equ 0007h
RCON_IPEN_POSITION                       equ 0007h
RCON_IPEN_SIZE                           equ 0001h
RCON_IPEN_LENGTH                         equ 0001h
RCON_IPEN_MASK                           equ 0080h
RCON_BOR_POSN                            equ 0000h
RCON_BOR_POSITION                        equ 0000h
RCON_BOR_SIZE                            equ 0001h
RCON_BOR_LENGTH                          equ 0001h
RCON_BOR_MASK                            equ 0001h
RCON_POR_POSN                            equ 0001h
RCON_POR_POSITION                        equ 0001h
RCON_POR_SIZE                            equ 0001h
RCON_POR_LENGTH                          equ 0001h
RCON_POR_MASK                            equ 0002h
RCON_PD_POSN                             equ 0002h
RCON_PD_POSITION                         equ 0002h
RCON_PD_SIZE                             equ 0001h
RCON_PD_LENGTH                           equ 0001h
RCON_PD_MASK                             equ 0004h
RCON_TO_POSN                             equ 0003h
RCON_TO_POSITION                         equ 0003h
RCON_TO_SIZE                             equ 0001h
RCON_TO_LENGTH                           equ 0001h
RCON_TO_MASK                             equ 0008h
RCON_RI_POSN                             equ 0004h
RCON_RI_POSITION                         equ 0004h
RCON_RI_SIZE                             equ 0001h
RCON_RI_LENGTH                           equ 0001h
RCON_RI_MASK                             equ 0010h

// Register: WDTCON
#define WDTCON WDTCON
WDTCON                                   equ 0FD1h
// bitfield definitions
WDTCON_SWDTEN_POSN                       equ 0000h
WDTCON_SWDTEN_POSITION                   equ 0000h
WDTCON_SWDTEN_SIZE                       equ 0001h
WDTCON_SWDTEN_LENGTH                     equ 0001h
WDTCON_SWDTEN_MASK                       equ 0001h
WDTCON_SWDTE_POSN                        equ 0000h
WDTCON_SWDTE_POSITION                    equ 0000h
WDTCON_SWDTE_SIZE                        equ 0001h
WDTCON_SWDTE_LENGTH                      equ 0001h
WDTCON_SWDTE_MASK                        equ 0001h

// Register: LVDCON
#define LVDCON LVDCON
LVDCON                                   equ 0FD2h
// bitfield definitions
LVDCON_LVDL_POSN                         equ 0000h
LVDCON_LVDL_POSITION                     equ 0000h
LVDCON_LVDL_SIZE                         equ 0004h
LVDCON_LVDL_LENGTH                       equ 0004h
LVDCON_LVDL_MASK                         equ 000Fh
LVDCON_LVDEN_POSN                        equ 0004h
LVDCON_LVDEN_POSITION                    equ 0004h
LVDCON_LVDEN_SIZE                        equ 0001h
LVDCON_LVDEN_LENGTH                      equ 0001h
LVDCON_LVDEN_MASK                        equ 0010h
LVDCON_IRVST_POSN                        equ 0005h
LVDCON_IRVST_POSITION                    equ 0005h
LVDCON_IRVST_SIZE                        equ 0001h
LVDCON_IRVST_LENGTH                      equ 0001h
LVDCON_IRVST_MASK                        equ 0020h
LVDCON_LVDL0_POSN                        equ 0000h
LVDCON_LVDL0_POSITION                    equ 0000h
LVDCON_LVDL0_SIZE                        equ 0001h
LVDCON_LVDL0_LENGTH                      equ 0001h
LVDCON_LVDL0_MASK                        equ 0001h
LVDCON_LVDL1_POSN                        equ 0001h
LVDCON_LVDL1_POSITION                    equ 0001h
LVDCON_LVDL1_SIZE                        equ 0001h
LVDCON_LVDL1_LENGTH                      equ 0001h
LVDCON_LVDL1_MASK                        equ 0002h
LVDCON_LVDL2_POSN                        equ 0002h
LVDCON_LVDL2_POSITION                    equ 0002h
LVDCON_LVDL2_SIZE                        equ 0001h
LVDCON_LVDL2_LENGTH                      equ 0001h
LVDCON_LVDL2_MASK                        equ 0004h
LVDCON_LVDL3_POSN                        equ 0003h
LVDCON_LVDL3_POSITION                    equ 0003h
LVDCON_LVDL3_SIZE                        equ 0001h
LVDCON_LVDL3_LENGTH                      equ 0001h
LVDCON_LVDL3_MASK                        equ 0008h
LVDCON_IVRST_POSN                        equ 0005h
LVDCON_IVRST_POSITION                    equ 0005h
LVDCON_IVRST_SIZE                        equ 0001h
LVDCON_IVRST_LENGTH                      equ 0001h
LVDCON_IVRST_MASK                        equ 0020h

// Register: OSCCON
#define OSCCON OSCCON
OSCCON                                   equ 0FD3h
// bitfield definitions
OSCCON_SCS_POSN                          equ 0000h
OSCCON_SCS_POSITION                      equ 0000h
OSCCON_SCS_SIZE                          equ 0002h
OSCCON_SCS_LENGTH                        equ 0002h
OSCCON_SCS_MASK                          equ 0003h
OSCCON_IOFS_POSN                         equ 0002h
OSCCON_IOFS_POSITION                     equ 0002h
OSCCON_IOFS_SIZE                         equ 0001h
OSCCON_IOFS_LENGTH                       equ 0001h
OSCCON_IOFS_MASK                         equ 0004h
OSCCON_OSTS_POSN                         equ 0003h
OSCCON_OSTS_POSITION                     equ 0003h
OSCCON_OSTS_SIZE                         equ 0001h
OSCCON_OSTS_LENGTH                       equ 0001h
OSCCON_OSTS_MASK                         equ 0008h
OSCCON_IRCF_POSN                         equ 0004h
OSCCON_IRCF_POSITION                     equ 0004h
OSCCON_IRCF_SIZE                         equ 0003h
OSCCON_IRCF_LENGTH                       equ 0003h
OSCCON_IRCF_MASK                         equ 0070h
OSCCON_IDLEN_POSN                        equ 0007h
OSCCON_IDLEN_POSITION                    equ 0007h
OSCCON_IDLEN_SIZE                        equ 0001h
OSCCON_IDLEN_LENGTH                      equ 0001h
OSCCON_IDLEN_MASK                        equ 0080h
OSCCON_SCS0_POSN                         equ 0000h
OSCCON_SCS0_POSITION                     equ 0000h
OSCCON_SCS0_SIZE                         equ 0001h
OSCCON_SCS0_LENGTH                       equ 0001h
OSCCON_SCS0_MASK                         equ 0001h
OSCCON_SCS1_POSN                         equ 0001h
OSCCON_SCS1_POSITION                     equ 0001h
OSCCON_SCS1_SIZE                         equ 0001h
OSCCON_SCS1_LENGTH                       equ 0001h
OSCCON_SCS1_MASK                         equ 0002h
OSCCON_FLTS_POSN                         equ 0002h
OSCCON_FLTS_POSITION                     equ 0002h
OSCCON_FLTS_SIZE                         equ 0001h
OSCCON_FLTS_LENGTH                       equ 0001h
OSCCON_FLTS_MASK                         equ 0004h
OSCCON_IRCF0_POSN                        equ 0004h
OSCCON_IRCF0_POSITION                    equ 0004h
OSCCON_IRCF0_SIZE                        equ 0001h
OSCCON_IRCF0_LENGTH                      equ 0001h
OSCCON_IRCF0_MASK                        equ 0010h
OSCCON_IRCF1_POSN                        equ 0005h
OSCCON_IRCF1_POSITION                    equ 0005h
OSCCON_IRCF1_SIZE                        equ 0001h
OSCCON_IRCF1_LENGTH                      equ 0001h
OSCCON_IRCF1_MASK                        equ 0020h
OSCCON_IRCF2_POSN                        equ 0006h
OSCCON_IRCF2_POSITION                    equ 0006h
OSCCON_IRCF2_SIZE                        equ 0001h
OSCCON_IRCF2_LENGTH                      equ 0001h
OSCCON_IRCF2_MASK                        equ 0040h

// Register: T0CON
#define T0CON T0CON
T0CON                                    equ 0FD5h
// bitfield definitions
T0CON_T0PS_POSN                          equ 0000h
T0CON_T0PS_POSITION                      equ 0000h
T0CON_T0PS_SIZE                          equ 0003h
T0CON_T0PS_LENGTH                        equ 0003h
T0CON_T0PS_MASK                          equ 0007h
T0CON_PSA_POSN                           equ 0003h
T0CON_PSA_POSITION                       equ 0003h
T0CON_PSA_SIZE                           equ 0001h
T0CON_PSA_LENGTH                         equ 0001h
T0CON_PSA_MASK                           equ 0008h
T0CON_T0SE_POSN                          equ 0004h
T0CON_T0SE_POSITION                      equ 0004h
T0CON_T0SE_SIZE                          equ 0001h
T0CON_T0SE_LENGTH                        equ 0001h
T0CON_T0SE_MASK                          equ 0010h
T0CON_T0CS_POSN                          equ 0005h
T0CON_T0CS_POSITION                      equ 0005h
T0CON_T0CS_SIZE                          equ 0001h
T0CON_T0CS_LENGTH                        equ 0001h
T0CON_T0CS_MASK                          equ 0020h
T0CON_T016BIT_POSN                       equ 0006h
T0CON_T016BIT_POSITION                   equ 0006h
T0CON_T016BIT_SIZE                       equ 0001h
T0CON_T016BIT_LENGTH                     equ 0001h
T0CON_T016BIT_MASK                       equ 0040h
T0CON_TMR0ON_POSN                        equ 0007h
T0CON_TMR0ON_POSITION                    equ 0007h
T0CON_TMR0ON_SIZE                        equ 0001h
T0CON_TMR0ON_LENGTH                      equ 0001h
T0CON_TMR0ON_MASK                        equ 0080h
T0CON_T0PS0_POSN                         equ 0000h
T0CON_T0PS0_POSITION                     equ 0000h
T0CON_T0PS0_SIZE                         equ 0001h
T0CON_T0PS0_LENGTH                       equ 0001h
T0CON_T0PS0_MASK                         equ 0001h
T0CON_T0PS1_POSN                         equ 0001h
T0CON_T0PS1_POSITION                     equ 0001h
T0CON_T0PS1_SIZE                         equ 0001h
T0CON_T0PS1_LENGTH                       equ 0001h
T0CON_T0PS1_MASK                         equ 0002h
T0CON_T0PS2_POSN                         equ 0002h
T0CON_T0PS2_POSITION                     equ 0002h
T0CON_T0PS2_SIZE                         equ 0001h
T0CON_T0PS2_LENGTH                       equ 0001h
T0CON_T0PS2_MASK                         equ 0004h
T0CON_T08BIT_POSN                        equ 0006h
T0CON_T08BIT_POSITION                    equ 0006h
T0CON_T08BIT_SIZE                        equ 0001h
T0CON_T08BIT_LENGTH                      equ 0001h
T0CON_T08BIT_MASK                        equ 0040h

// Register: TMR0
#define TMR0 TMR0
TMR0                                     equ 0FD6h

// Register: TMR0L
#define TMR0L TMR0L
TMR0L                                    equ 0FD6h

// Register: TMR0H
#define TMR0H TMR0H
TMR0H                                    equ 0FD7h

// Register: STATUS
#define STATUS STATUS
STATUS                                   equ 0FD8h
// bitfield definitions
STATUS_C_POSN                            equ 0000h
STATUS_C_POSITION                        equ 0000h
STATUS_C_SIZE                            equ 0001h
STATUS_C_LENGTH                          equ 0001h
STATUS_C_MASK                            equ 0001h
STATUS_DC_POSN                           equ 0001h
STATUS_DC_POSITION                       equ 0001h
STATUS_DC_SIZE                           equ 0001h
STATUS_DC_LENGTH                         equ 0001h
STATUS_DC_MASK                           equ 0002h
STATUS_Z_POSN                            equ 0002h
STATUS_Z_POSITION                        equ 0002h
STATUS_Z_SIZE                            equ 0001h
STATUS_Z_LENGTH                          equ 0001h
STATUS_Z_MASK                            equ 0004h
STATUS_OV_POSN                           equ 0003h
STATUS_OV_POSITION                       equ 0003h
STATUS_OV_SIZE                           equ 0001h
STATUS_OV_LENGTH                         equ 0001h
STATUS_OV_MASK                           equ 0008h
STATUS_N_POSN                            equ 0004h
STATUS_N_POSITION                        equ 0004h
STATUS_N_SIZE                            equ 0001h
STATUS_N_LENGTH                          equ 0001h
STATUS_N_MASK                            equ 0010h
STATUS_CARRY_POSN                        equ 0000h
STATUS_CARRY_POSITION                    equ 0000h
STATUS_CARRY_SIZE                        equ 0001h
STATUS_CARRY_LENGTH                      equ 0001h
STATUS_CARRY_MASK                        equ 0001h
STATUS_ZERO_POSN                         equ 0002h
STATUS_ZERO_POSITION                     equ 0002h
STATUS_ZERO_SIZE                         equ 0001h
STATUS_ZERO_LENGTH                       equ 0001h
STATUS_ZERO_MASK                         equ 0004h
STATUS_OVERFLOW_POSN                     equ 0003h
STATUS_OVERFLOW_POSITION                 equ 0003h
STATUS_OVERFLOW_SIZE                     equ 0001h
STATUS_OVERFLOW_LENGTH                   equ 0001h
STATUS_OVERFLOW_MASK                     equ 0008h
STATUS_NEGATIVE_POSN                     equ 0004h
STATUS_NEGATIVE_POSITION                 equ 0004h
STATUS_NEGATIVE_SIZE                     equ 0001h
STATUS_NEGATIVE_LENGTH                   equ 0001h
STATUS_NEGATIVE_MASK                     equ 0010h

// Register: FSR2
#define FSR2 FSR2
FSR2                                     equ 0FD9h

// Register: FSR2L
#define FSR2L FSR2L
FSR2L                                    equ 0FD9h

// Register: FSR2H
#define FSR2H FSR2H
FSR2H                                    equ 0FDAh

// Register: PLUSW2
#define PLUSW2 PLUSW2
PLUSW2                                   equ 0FDBh

// Register: PREINC2
#define PREINC2 PREINC2
PREINC2                                  equ 0FDCh

// Register: POSTDEC2
#define POSTDEC2 POSTDEC2
POSTDEC2                                 equ 0FDDh

// Register: POSTINC2
#define POSTINC2 POSTINC2
POSTINC2                                 equ 0FDEh

// Register: INDF2
#define INDF2 INDF2
INDF2                                    equ 0FDFh

// Register: BSR
#define BSR BSR
BSR                                      equ 0FE0h

// Register: FSR1
#define FSR1 FSR1
FSR1                                     equ 0FE1h

// Register: FSR1L
#define FSR1L FSR1L
FSR1L                                    equ 0FE1h

// Register: FSR1H
#define FSR1H FSR1H
FSR1H                                    equ 0FE2h

// Register: PLUSW1
#define PLUSW1 PLUSW1
PLUSW1                                   equ 0FE3h

// Register: PREINC1
#define PREINC1 PREINC1
PREINC1                                  equ 0FE4h

// Register: POSTDEC1
#define POSTDEC1 POSTDEC1
POSTDEC1                                 equ 0FE5h

// Register: POSTINC1
#define POSTINC1 POSTINC1
POSTINC1                                 equ 0FE6h

// Register: INDF1
#define INDF1 INDF1
INDF1                                    equ 0FE7h

// Register: WREG
#define WREG WREG
WREG                                     equ 0FE8h

// Register: FSR0
#define FSR0 FSR0
FSR0                                     equ 0FE9h

// Register: FSR0L
#define FSR0L FSR0L
FSR0L                                    equ 0FE9h

// Register: FSR0H
#define FSR0H FSR0H
FSR0H                                    equ 0FEAh

// Register: PLUSW0
#define PLUSW0 PLUSW0
PLUSW0                                   equ 0FEBh

// Register: PREINC0
#define PREINC0 PREINC0
PREINC0                                  equ 0FECh

// Register: POSTDEC0
#define POSTDEC0 POSTDEC0
POSTDEC0                                 equ 0FEDh

// Register: POSTINC0
#define POSTINC0 POSTINC0
POSTINC0                                 equ 0FEEh

// Register: INDF0
#define INDF0 INDF0
INDF0                                    equ 0FEFh

// Register: INTCON3
#define INTCON3 INTCON3
INTCON3                                  equ 0FF0h
// bitfield definitions
INTCON3_INT1IF_POSN                      equ 0000h
INTCON3_INT1IF_POSITION                  equ 0000h
INTCON3_INT1IF_SIZE                      equ 0001h
INTCON3_INT1IF_LENGTH                    equ 0001h
INTCON3_INT1IF_MASK                      equ 0001h
INTCON3_INT2IF_POSN                      equ 0001h
INTCON3_INT2IF_POSITION                  equ 0001h
INTCON3_INT2IF_SIZE                      equ 0001h
INTCON3_INT2IF_LENGTH                    equ 0001h
INTCON3_INT2IF_MASK                      equ 0002h
INTCON3_INT3IF_POSN                      equ 0002h
INTCON3_INT3IF_POSITION                  equ 0002h
INTCON3_INT3IF_SIZE                      equ 0001h
INTCON3_INT3IF_LENGTH                    equ 0001h
INTCON3_INT3IF_MASK                      equ 0004h
INTCON3_INT1IE_POSN                      equ 0003h
INTCON3_INT1IE_POSITION                  equ 0003h
INTCON3_INT1IE_SIZE                      equ 0001h
INTCON3_INT1IE_LENGTH                    equ 0001h
INTCON3_INT1IE_MASK                      equ 0008h
INTCON3_INT2IE_POSN                      equ 0004h
INTCON3_INT2IE_POSITION                  equ 0004h
INTCON3_INT2IE_SIZE                      equ 0001h
INTCON3_INT2IE_LENGTH                    equ 0001h
INTCON3_INT2IE_MASK                      equ 0010h
INTCON3_INT3IE_POSN                      equ 0005h
INTCON3_INT3IE_POSITION                  equ 0005h
INTCON3_INT3IE_SIZE                      equ 0001h
INTCON3_INT3IE_LENGTH                    equ 0001h
INTCON3_INT3IE_MASK                      equ 0020h
INTCON3_INT1IP_POSN                      equ 0006h
INTCON3_INT1IP_POSITION                  equ 0006h
INTCON3_INT1IP_SIZE                      equ 0001h
INTCON3_INT1IP_LENGTH                    equ 0001h
INTCON3_INT1IP_MASK                      equ 0040h
INTCON3_INT2IP_POSN                      equ 0007h
INTCON3_INT2IP_POSITION                  equ 0007h
INTCON3_INT2IP_SIZE                      equ 0001h
INTCON3_INT2IP_LENGTH                    equ 0001h
INTCON3_INT2IP_MASK                      equ 0080h
INTCON3_INT1F_POSN                       equ 0000h
INTCON3_INT1F_POSITION                   equ 0000h
INTCON3_INT1F_SIZE                       equ 0001h
INTCON3_INT1F_LENGTH                     equ 0001h
INTCON3_INT1F_MASK                       equ 0001h
INTCON3_INT2F_POSN                       equ 0001h
INTCON3_INT2F_POSITION                   equ 0001h
INTCON3_INT2F_SIZE                       equ 0001h
INTCON3_INT2F_LENGTH                     equ 0001h
INTCON3_INT2F_MASK                       equ 0002h
INTCON3_INT3F_POSN                       equ 0002h
INTCON3_INT3F_POSITION                   equ 0002h
INTCON3_INT3F_SIZE                       equ 0001h
INTCON3_INT3F_LENGTH                     equ 0001h
INTCON3_INT3F_MASK                       equ 0004h
INTCON3_INT1E_POSN                       equ 0003h
INTCON3_INT1E_POSITION                   equ 0003h
INTCON3_INT1E_SIZE                       equ 0001h
INTCON3_INT1E_LENGTH                     equ 0001h
INTCON3_INT1E_MASK                       equ 0008h
INTCON3_INT2E_POSN                       equ 0004h
INTCON3_INT2E_POSITION                   equ 0004h
INTCON3_INT2E_SIZE                       equ 0001h
INTCON3_INT2E_LENGTH                     equ 0001h
INTCON3_INT2E_MASK                       equ 0010h
INTCON3_INT3E_POSN                       equ 0005h
INTCON3_INT3E_POSITION                   equ 0005h
INTCON3_INT3E_SIZE                       equ 0001h
INTCON3_INT3E_LENGTH                     equ 0001h
INTCON3_INT3E_MASK                       equ 0020h
INTCON3_INT1P_POSN                       equ 0006h
INTCON3_INT1P_POSITION                   equ 0006h
INTCON3_INT1P_SIZE                       equ 0001h
INTCON3_INT1P_LENGTH                     equ 0001h
INTCON3_INT1P_MASK                       equ 0040h
INTCON3_INT2P_POSN                       equ 0007h
INTCON3_INT2P_POSITION                   equ 0007h
INTCON3_INT2P_SIZE                       equ 0001h
INTCON3_INT2P_LENGTH                     equ 0001h
INTCON3_INT2P_MASK                       equ 0080h

// Register: INTCON2
#define INTCON2 INTCON2
INTCON2                                  equ 0FF1h
// bitfield definitions
INTCON2_NOT_RBPU_POSN                    equ 0007h
INTCON2_NOT_RBPU_POSITION                equ 0007h
INTCON2_NOT_RBPU_SIZE                    equ 0001h
INTCON2_NOT_RBPU_LENGTH                  equ 0001h
INTCON2_NOT_RBPU_MASK                    equ 0080h
INTCON2_RBIP_POSN                        equ 0000h
INTCON2_RBIP_POSITION                    equ 0000h
INTCON2_RBIP_SIZE                        equ 0001h
INTCON2_RBIP_LENGTH                      equ 0001h
INTCON2_RBIP_MASK                        equ 0001h
INTCON2_INT3IP_POSN                      equ 0001h
INTCON2_INT3IP_POSITION                  equ 0001h
INTCON2_INT3IP_SIZE                      equ 0001h
INTCON2_INT3IP_LENGTH                    equ 0001h
INTCON2_INT3IP_MASK                      equ 0002h
INTCON2_TMR0IP_POSN                      equ 0002h
INTCON2_TMR0IP_POSITION                  equ 0002h
INTCON2_TMR0IP_SIZE                      equ 0001h
INTCON2_TMR0IP_LENGTH                    equ 0001h
INTCON2_TMR0IP_MASK                      equ 0004h
INTCON2_INTEDG3_POSN                     equ 0003h
INTCON2_INTEDG3_POSITION                 equ 0003h
INTCON2_INTEDG3_SIZE                     equ 0001h
INTCON2_INTEDG3_LENGTH                   equ 0001h
INTCON2_INTEDG3_MASK                     equ 0008h
INTCON2_INTEDG2_POSN                     equ 0004h
INTCON2_INTEDG2_POSITION                 equ 0004h
INTCON2_INTEDG2_SIZE                     equ 0001h
INTCON2_INTEDG2_LENGTH                   equ 0001h
INTCON2_INTEDG2_MASK                     equ 0010h
INTCON2_INTEDG1_POSN                     equ 0005h
INTCON2_INTEDG1_POSITION                 equ 0005h
INTCON2_INTEDG1_SIZE                     equ 0001h
INTCON2_INTEDG1_LENGTH                   equ 0001h
INTCON2_INTEDG1_MASK                     equ 0020h
INTCON2_INTEDG0_POSN                     equ 0006h
INTCON2_INTEDG0_POSITION                 equ 0006h
INTCON2_INTEDG0_SIZE                     equ 0001h
INTCON2_INTEDG0_LENGTH                   equ 0001h
INTCON2_INTEDG0_MASK                     equ 0040h
INTCON2_nRBPU_POSN                       equ 0007h
INTCON2_nRBPU_POSITION                   equ 0007h
INTCON2_nRBPU_SIZE                       equ 0001h
INTCON2_nRBPU_LENGTH                     equ 0001h
INTCON2_nRBPU_MASK                       equ 0080h
INTCON2_INT3P_POSN                       equ 0001h
INTCON2_INT3P_POSITION                   equ 0001h
INTCON2_INT3P_SIZE                       equ 0001h
INTCON2_INT3P_LENGTH                     equ 0001h
INTCON2_INT3P_MASK                       equ 0002h
INTCON2_RBPU_POSN                        equ 0007h
INTCON2_RBPU_POSITION                    equ 0007h
INTCON2_RBPU_SIZE                        equ 0001h
INTCON2_RBPU_LENGTH                      equ 0001h
INTCON2_RBPU_MASK                        equ 0080h

// Register: INTCON
#define INTCON INTCON
INTCON                                   equ 0FF2h
// bitfield definitions
INTCON_RBIF_POSN                         equ 0000h
INTCON_RBIF_POSITION                     equ 0000h
INTCON_RBIF_SIZE                         equ 0001h
INTCON_RBIF_LENGTH                       equ 0001h
INTCON_RBIF_MASK                         equ 0001h
INTCON_INT0IF_POSN                       equ 0001h
INTCON_INT0IF_POSITION                   equ 0001h
INTCON_INT0IF_SIZE                       equ 0001h
INTCON_INT0IF_LENGTH                     equ 0001h
INTCON_INT0IF_MASK                       equ 0002h
INTCON_TMR0IF_POSN                       equ 0002h
INTCON_TMR0IF_POSITION                   equ 0002h
INTCON_TMR0IF_SIZE                       equ 0001h
INTCON_TMR0IF_LENGTH                     equ 0001h
INTCON_TMR0IF_MASK                       equ 0004h
INTCON_RBIE_POSN                         equ 0003h
INTCON_RBIE_POSITION                     equ 0003h
INTCON_RBIE_SIZE                         equ 0001h
INTCON_RBIE_LENGTH                       equ 0001h
INTCON_RBIE_MASK                         equ 0008h
INTCON_INT0IE_POSN                       equ 0004h
INTCON_INT0IE_POSITION                   equ 0004h
INTCON_INT0IE_SIZE                       equ 0001h
INTCON_INT0IE_LENGTH                     equ 0001h
INTCON_INT0IE_MASK                       equ 0010h
INTCON_TMR0IE_POSN                       equ 0005h
INTCON_TMR0IE_POSITION                   equ 0005h
INTCON_TMR0IE_SIZE                       equ 0001h
INTCON_TMR0IE_LENGTH                     equ 0001h
INTCON_TMR0IE_MASK                       equ 0020h
INTCON_PEIE_GIEL_POSN                    equ 0006h
INTCON_PEIE_GIEL_POSITION                equ 0006h
INTCON_PEIE_GIEL_SIZE                    equ 0001h
INTCON_PEIE_GIEL_LENGTH                  equ 0001h
INTCON_PEIE_GIEL_MASK                    equ 0040h
INTCON_GIE_GIEH_POSN                     equ 0007h
INTCON_GIE_GIEH_POSITION                 equ 0007h
INTCON_GIE_GIEH_SIZE                     equ 0001h
INTCON_GIE_GIEH_LENGTH                   equ 0001h
INTCON_GIE_GIEH_MASK                     equ 0080h
INTCON_INT0F_POSN                        equ 0001h
INTCON_INT0F_POSITION                    equ 0001h
INTCON_INT0F_SIZE                        equ 0001h
INTCON_INT0F_LENGTH                      equ 0001h
INTCON_INT0F_MASK                        equ 0002h
INTCON_T0IF_POSN                         equ 0002h
INTCON_T0IF_POSITION                     equ 0002h
INTCON_T0IF_SIZE                         equ 0001h
INTCON_T0IF_LENGTH                       equ 0001h
INTCON_T0IF_MASK                         equ 0004h
INTCON_INT0E_POSN                        equ 0004h
INTCON_INT0E_POSITION                    equ 0004h
INTCON_INT0E_SIZE                        equ 0001h
INTCON_INT0E_LENGTH                      equ 0001h
INTCON_INT0E_MASK                        equ 0010h
INTCON_T0IE_POSN                         equ 0005h
INTCON_T0IE_POSITION                     equ 0005h
INTCON_T0IE_SIZE                         equ 0001h
INTCON_T0IE_LENGTH                       equ 0001h
INTCON_T0IE_MASK                         equ 0020h
INTCON_PEIE_POSN                         equ 0006h
INTCON_PEIE_POSITION                     equ 0006h
INTCON_PEIE_SIZE                         equ 0001h
INTCON_PEIE_LENGTH                       equ 0001h
INTCON_PEIE_MASK                         equ 0040h
INTCON_GIE_POSN                          equ 0007h
INTCON_GIE_POSITION                      equ 0007h
INTCON_GIE_SIZE                          equ 0001h
INTCON_GIE_LENGTH                        equ 0001h
INTCON_GIE_MASK                          equ 0080h
INTCON_GIEL_POSN                         equ 0006h
INTCON_GIEL_POSITION                     equ 0006h
INTCON_GIEL_SIZE                         equ 0001h
INTCON_GIEL_LENGTH                       equ 0001h
INTCON_GIEL_MASK                         equ 0040h
INTCON_GIEH_POSN                         equ 0007h
INTCON_GIEH_POSITION                     equ 0007h
INTCON_GIEH_SIZE                         equ 0001h
INTCON_GIEH_LENGTH                       equ 0001h
INTCON_GIEH_MASK                         equ 0080h

// Register: PROD
#define PROD PROD
PROD                                     equ 0FF3h

// Register: PRODL
#define PRODL PRODL
PRODL                                    equ 0FF3h

// Register: PRODH
#define PRODH PRODH
PRODH                                    equ 0FF4h

// Register: TABLAT
#define TABLAT TABLAT
TABLAT                                   equ 0FF5h

// Register: TBLPTR
#define TBLPTR TBLPTR
TBLPTR                                   equ 0FF6h

// Register: TBLPTRL
#define TBLPTRL TBLPTRL
TBLPTRL                                  equ 0FF6h

// Register: TBLPTRH
#define TBLPTRH TBLPTRH
TBLPTRH                                  equ 0FF7h

// Register: TBLPTRU
#define TBLPTRU TBLPTRU
TBLPTRU                                  equ 0FF8h

// Register: PCLAT
#define PCLAT PCLAT
PCLAT                                    equ 0FF9h

// Register: PCL
#define PCL PCL
PCL                                      equ 0FF9h

// Register: PCLATH
#define PCLATH PCLATH
PCLATH                                   equ 0FFAh

// Register: PCLATU
#define PCLATU PCLATU
PCLATU                                   equ 0FFBh

// Register: STKPTR
#define STKPTR STKPTR
STKPTR                                   equ 0FFCh
// bitfield definitions
STKPTR_STKPTR_POSN                       equ 0000h
STKPTR_STKPTR_POSITION                   equ 0000h
STKPTR_STKPTR_SIZE                       equ 0005h
STKPTR_STKPTR_LENGTH                     equ 0005h
STKPTR_STKPTR_MASK                       equ 001Fh
STKPTR_STKUNF_POSN                       equ 0006h
STKPTR_STKUNF_POSITION                   equ 0006h
STKPTR_STKUNF_SIZE                       equ 0001h
STKPTR_STKUNF_LENGTH                     equ 0001h
STKPTR_STKUNF_MASK                       equ 0040h
STKPTR_STKFUL_POSN                       equ 0007h
STKPTR_STKFUL_POSITION                   equ 0007h
STKPTR_STKFUL_SIZE                       equ 0001h
STKPTR_STKFUL_LENGTH                     equ 0001h
STKPTR_STKFUL_MASK                       equ 0080h
STKPTR_SP0_POSN                          equ 0000h
STKPTR_SP0_POSITION                      equ 0000h
STKPTR_SP0_SIZE                          equ 0001h
STKPTR_SP0_LENGTH                        equ 0001h
STKPTR_SP0_MASK                          equ 0001h
STKPTR_SP1_POSN                          equ 0001h
STKPTR_SP1_POSITION                      equ 0001h
STKPTR_SP1_SIZE                          equ 0001h
STKPTR_SP1_LENGTH                        equ 0001h
STKPTR_SP1_MASK                          equ 0002h
STKPTR_SP2_POSN                          equ 0002h
STKPTR_SP2_POSITION                      equ 0002h
STKPTR_SP2_SIZE                          equ 0001h
STKPTR_SP2_LENGTH                        equ 0001h
STKPTR_SP2_MASK                          equ 0004h
STKPTR_SP3_POSN                          equ 0003h
STKPTR_SP3_POSITION                      equ 0003h
STKPTR_SP3_SIZE                          equ 0001h
STKPTR_SP3_LENGTH                        equ 0001h
STKPTR_SP3_MASK                          equ 0008h
STKPTR_SP4_POSN                          equ 0004h
STKPTR_SP4_POSITION                      equ 0004h
STKPTR_SP4_SIZE                          equ 0001h
STKPTR_SP4_LENGTH                        equ 0001h
STKPTR_SP4_MASK                          equ 0010h
STKPTR_STKOVF_POSN                       equ 0007h
STKPTR_STKOVF_POSITION                   equ 0007h
STKPTR_STKOVF_SIZE                       equ 0001h
STKPTR_STKOVF_LENGTH                     equ 0001h
STKPTR_STKOVF_MASK                       equ 0080h

// Register: TOS
#define TOS TOS
TOS                                      equ 0FFDh

// Register: TOSL
#define TOSL TOSL
TOSL                                     equ 0FFDh

// Register: TOSH
#define TOSH TOSH
TOSH                                     equ 0FFEh

// Register: TOSU
#define TOSU TOSU
TOSU                                     equ 0FFFh

/*
 * Bit Access Macros
 */

#ifndef PAGEMASK
#define PAGEMASK(addr) ((addr) and 0FFFFFh)
#endif
#ifndef BANKMASK
#define BANKMASK(addr) ((addr) and 0FFh)
#endif
#define ABDEN                            BANKMASK(BAUDCON), 0, a
#define ABDOVF                           BANKMASK(BAUDCON), 7, a
#define ACQT0                            BANKMASK(ADCON2), 3, a
#define ACQT1                            BANKMASK(ADCON2), 4, a
#define ACQT2                            BANKMASK(ADCON2), 5, a
#define ADCAL                            BANKMASK(ADCON0), 7, a
#define ADCS0                            BANKMASK(ADCON2), 0, a
#define ADCS1                            BANKMASK(ADCON2), 1, a
#define ADCS2                            BANKMASK(ADCON2), 2, a
#define ADDEN                            BANKMASK(RCSTA), 3, a
#define ADEN                             BANKMASK(RCSTA), 3, a
#define ADFM                             BANKMASK(ADCON2), 7, a
#define ADIE                             BANKMASK(PIE1), 6, a
#define ADIF                             BANKMASK(PIR1), 6, a
#define ADIP                             BANKMASK(IPR1), 6, a
#define ADON                             BANKMASK(ADCON0), 0, a
#define AN0                              BANKMASK(PORTA), 0, a
#define AN1                              BANKMASK(PORTA), 1, a
#define AN2                              BANKMASK(PORTA), 4, a
#define AN3                              BANKMASK(PORTA), 6, a
#define BOR                              BANKMASK(RCON), 0, a
#define BRFEN                            BANKMASK(FLTCONFIG), 7, a
#define BRG16                            BANKMASK(BAUDCON), 3, a
#define BRGH                             BANKMASK(TXSTA), 2, a
#define BRGH1                            BANKMASK(TXSTA), 2, a
#define C0OUT                            BANKMASK(CMCON), 5, a
#define C1OUT                            BANKMASK(CMCON), 6, a
#define C2INV                            BANKMASK(CMCON), 5, a
#define C2OUT                            BANKMASK(CMCON), 7, a
#define CARRY                            BANKMASK(STATUS), 0, a
#define CCP2_PA2                         BANKMASK(PORTB), 3, a
#define CFGS                             BANKMASK(EECON1), 6, a
#define CHS0                             BANKMASK(ADCON0), 2, a
#define CHS1                             BANKMASK(ADCON0), 3, a
#define CHSN3                            BANKMASK(ADCON1), 3, a
#define CK                               BANKMASK(PORTA), 2, a
#define CLKI                             BANKMASK(PORTA), 7, a
#define CLKO                             BANKMASK(PORTA), 6, a
#define CM0                              BANKMASK(CMCON), 0, a
#define CM1                              BANKMASK(CMCON), 1, a
#define CM2                              BANKMASK(CMCON), 2, a
#define CMEN0                            BANKMASK(CMCON), 0, a
#define CMEN1                            BANKMASK(CMCON), 1, a
#define CMEN2                            BANKMASK(CMCON), 2, a
#define CMP0                             BANKMASK(PORTA), 0, a
#define CMP0IE                           BANKMASK(PIE1), 1, a
#define CMP0IF                           BANKMASK(PIR1), 1, a
#define CMP0IP                           BANKMASK(IPR1), 1, a
#define CMP1                             BANKMASK(PORTB), 3, a
#define CMP1IE                           BANKMASK(PIE1), 2, a
#define CMP1IF                           BANKMASK(PIR1), 2, a
#define CMP1IP                           BANKMASK(IPR1), 2, a
#define CMP2                             BANKMASK(PORTB), 2, a
#define CMP2IE                           BANKMASK(PIE1), 3, a
#define CMP2IF                           BANKMASK(PIR1), 3, a
#define CMP2IP                           BANKMASK(IPR1), 3, a
#define CREN                             BANKMASK(RCSTA), 4, a
#define CSRC                             BANKMASK(TXSTA), 7, a
#define CSRC1                            BANKMASK(TXSTA), 7, a
#define CVR0                             BANKMASK(CVRCON), 0, a
#define CVR1                             BANKMASK(CVRCON), 1, a
#define CVR2                             BANKMASK(CVRCON), 2, a
#define CVR3                             BANKMASK(CVRCON), 3, a
#define CVREF                            BANKMASK(CVRCON), 4, a
#define CVREN                            BANKMASK(CVRCON), 7, a
#define CVRR                             BANKMASK(CVRCON), 5, a
#define CVRSS                            BANKMASK(CVRCON), 4, a
#define DC                               BANKMASK(STATUS), 1, a
#define DONE                             BANKMASK(ADCON0), 1, a
#define DT                               BANKMASK(PORTA), 3, a
#define DT0                              BANKMASK(DTCON), 0, a
#define DT1                              BANKMASK(DTCON), 1, a
#define DT2                              BANKMASK(DTCON), 2, a
#define DT3                              BANKMASK(DTCON), 3, a
#define DT4                              BANKMASK(DTCON), 4, a
#define DT5                              BANKMASK(DTCON), 5, a
#define DTPS0                            BANKMASK(DTCON), 6, a
#define DTPS1                            BANKMASK(DTCON), 7, a
#define EEFS                             BANKMASK(EECON1), 6, a
#define EEIE                             BANKMASK(PIE2), 4, a
#define EEIF                             BANKMASK(PIR2), 4, a
#define EEIP                             BANKMASK(IPR2), 4, a
#define EEPGD                            BANKMASK(EECON1), 7, a
#define FERR                             BANKMASK(RCSTA), 2, a
#define FLTAEN                           BANKMASK(FLTCONFIG), 0, a
#define FLTAMOD                          BANKMASK(FLTCONFIG), 1, a
#define FLTAS                            BANKMASK(FLTCONFIG), 2, a
#define FLTS                             BANKMASK(OSCCON), 2, a
#define FREE                             BANKMASK(EECON1), 4, a
#define GIE                              BANKMASK(INTCON), 7, a
#define GIEH                             BANKMASK(INTCON), 7, a
#define GIEL                             BANKMASK(INTCON), 6, a
#define GIE_GIEH                         BANKMASK(INTCON), 7, a
#define GO                               BANKMASK(ADCON0), 1, a
#define GODONE                           BANKMASK(ADCON0), 1, a
#define GO_DONE                          BANKMASK(ADCON0), 1, a
#define GO_NOT_DONE                      BANKMASK(ADCON0), 1, a
#define GO_nDONE                         BANKMASK(ADCON0), 1, a
#define IDLEN                            BANKMASK(OSCCON), 7, a
#define INT0                             BANKMASK(PORTA), 0, a
#define INT0E                            BANKMASK(INTCON), 4, a
#define INT0F                            BANKMASK(INTCON), 1, a
#define INT0IE                           BANKMASK(INTCON), 4, a
#define INT0IF                           BANKMASK(INTCON), 1, a
#define INT1                             BANKMASK(PORTA), 1, a
#define INT1E                            BANKMASK(INTCON3), 3, a
#define INT1F                            BANKMASK(INTCON3), 0, a
#define INT1IE                           BANKMASK(INTCON3), 3, a
#define INT1IF                           BANKMASK(INTCON3), 0, a
#define INT1IP                           BANKMASK(INTCON3), 6, a
#define INT1P                            BANKMASK(INTCON3), 6, a
#define INT2                             BANKMASK(PORTB), 2, a
#define INT2E                            BANKMASK(INTCON3), 4, a
#define INT2F                            BANKMASK(INTCON3), 1, a
#define INT2IE                           BANKMASK(INTCON3), 4, a
#define INT2IF                           BANKMASK(INTCON3), 1, a
#define INT2IP                           BANKMASK(INTCON3), 7, a
#define INT2P                            BANKMASK(INTCON3), 7, a
#define INT3                             BANKMASK(PORTB), 3, a
#define INT3E                            BANKMASK(INTCON3), 5, a
#define INT3F                            BANKMASK(INTCON3), 2, a
#define INT3IE                           BANKMASK(INTCON3), 5, a
#define INT3IF                           BANKMASK(INTCON3), 2, a
#define INT3IP                           BANKMASK(INTCON2), 1, a
#define INT3P                            BANKMASK(INTCON2), 1, a
#define INTEDG0                          BANKMASK(INTCON2), 6, a
#define INTEDG1                          BANKMASK(INTCON2), 5, a
#define INTEDG2                          BANKMASK(INTCON2), 4, a
#define INTEDG3                          BANKMASK(INTCON2), 3, a
#define INTSRC                           BANKMASK(OSCTUNE), 7, a
#define IOFS                             BANKMASK(OSCCON), 2, a
#define IPEN                             BANKMASK(RCON), 7, a
#define IRCF0                            BANKMASK(OSCCON), 4, a
#define IRCF1                            BANKMASK(OSCCON), 5, a
#define IRCF2                            BANKMASK(OSCCON), 6, a
#define IRVST                            BANKMASK(LVDCON), 5, a
#define IVRST                            BANKMASK(LVDCON), 5, a
#define KBI0                             BANKMASK(PORTA), 0, a
#define KBI1                             BANKMASK(PORTA), 1, a
#define KBI2                             BANKMASK(PORTB), 2, a
#define KBI3                             BANKMASK(PORTB), 3, a
#define LA0                              BANKMASK(LATA), 0, a
#define LA1                              BANKMASK(LATA), 1, a
#define LA2                              BANKMASK(LATA), 2, a
#define LA3                              BANKMASK(LATA), 3, a
#define LA4                              BANKMASK(LATA), 4, a
#define LA5                              BANKMASK(LATA), 5, a
#define LA6                              BANKMASK(LATA), 6, a
#define LA7                              BANKMASK(LATA), 7, a
#define LATA0                            BANKMASK(LATA), 0, a
#define LATA1                            BANKMASK(LATA), 1, a
#define LATA2                            BANKMASK(LATA), 2, a
#define LATA3                            BANKMASK(LATA), 3, a
#define LATA4                            BANKMASK(LATA), 4, a
#define LATA5                            BANKMASK(LATA), 5, a
#define LATA6                            BANKMASK(LATA), 6, a
#define LATA7                            BANKMASK(LATA), 7, a
#define LATB0                            BANKMASK(LATB), 0, a
#define LATB1                            BANKMASK(LATB), 1, a
#define LATB2                            BANKMASK(LATB), 2, a
#define LATB3                            BANKMASK(LATB), 3, a
#define LATB4                            BANKMASK(LATB), 4, a
#define LATB5                            BANKMASK(LATB), 5, a
#define LATB6                            BANKMASK(LATB), 6, a
#define LATB7                            BANKMASK(LATB), 7, a
#define LB0                              BANKMASK(LATB), 0, a
#define LB1                              BANKMASK(LATB), 1, a
#define LB2                              BANKMASK(LATB), 2, a
#define LB3                              BANKMASK(LATB), 3, a
#define LB4                              BANKMASK(LATB), 4, a
#define LB5                              BANKMASK(LATB), 5, a
#define LB6                              BANKMASK(LATB), 6, a
#define LB7                              BANKMASK(LATB), 7, a
#define LVDEN                            BANKMASK(LVDCON), 4, a
#define LVDIE                            BANKMASK(PIE2), 2, a
#define LVDIF                            BANKMASK(PIR2), 2, a
#define LVDIN                            BANKMASK(PORTA), 5, a
#define LVDIP                            BANKMASK(IPR2), 2, a
#define LVDL0                            BANKMASK(LVDCON), 0, a
#define LVDL1                            BANKMASK(LVDCON), 1, a
#define LVDL2                            BANKMASK(LVDCON), 2, a
#define LVDL3                            BANKMASK(LVDCON), 3, a
#define MCLR                             BANKMASK(PORTA), 5, a
#define NEGATIVE                         BANKMASK(STATUS), 4, a
#define NOT_BOR                          BANKMASK(RCON), 0, a
#define NOT_DONE                         BANKMASK(ADCON0), 1, a
#define NOT_MCLR                         BANKMASK(PORTA), 5, a
#define NOT_PD                           BANKMASK(RCON), 2, a
#define NOT_POR                          BANKMASK(RCON), 1, a
#define NOT_RBPU                         BANKMASK(INTCON2), 7, a
#define NOT_RI                           BANKMASK(RCON), 4, a
#define NOT_T1SYNC                       BANKMASK(T1CON), 2, a
#define NOT_TO                           BANKMASK(RCON), 3, a
#define OERR                             BANKMASK(RCSTA), 1, a
#define OSC1                             BANKMASK(PORTA), 7, a
#define OSC2                             BANKMASK(PORTA), 6, a
#define OSCFIE                           BANKMASK(PIE2), 7, a
#define OSCFIF                           BANKMASK(PIR2), 7, a
#define OSCFIP                           BANKMASK(IPR2), 7, a
#define OSTS                             BANKMASK(OSCCON), 3, a
#define OSYNC                            BANKMASK(PWMCON1), 0, a
#define OV                               BANKMASK(STATUS), 3, a
#define OVERFLOW                         BANKMASK(STATUS), 3, a
#define PCFG0                            BANKMASK(ADCON1), 0, a
#define PCFG1                            BANKMASK(ADCON1), 1, a
#define PCFG2                            BANKMASK(ADCON1), 2, a
#define PCFG3                            BANKMASK(ADCON1), 3, a
#define PD                               BANKMASK(RCON), 2, a
#define PEIE                             BANKMASK(INTCON), 6, a
#define PEIE_GIEL                        BANKMASK(INTCON), 6, a
#define PGC                              BANKMASK(PORTB), 6, a
#define PGD                              BANKMASK(PORTB), 7, a
#define PLLEN                            BANKMASK(OSCTUNE), 6, a
#define PMOD0                            BANKMASK(PWMCON0), 0, a
#define PMOD1                            BANKMASK(PWMCON0), 1, a
#define PMOD2                            BANKMASK(PWMCON0), 2, a
#define POR                              BANKMASK(RCON), 1, a
#define POUT0                            BANKMASK(OVDCONS), 0, a
#define POUT1                            BANKMASK(OVDCONS), 1, a
#define POUT2                            BANKMASK(OVDCONS), 2, a
#define POUT3                            BANKMASK(OVDCONS), 3, a
#define POUT4                            BANKMASK(OVDCONS), 4, a
#define POUT5                            BANKMASK(OVDCONS), 5, a
#define POVD0                            BANKMASK(OVDCOND), 0, a
#define POVD1                            BANKMASK(OVDCOND), 1, a
#define POVD2                            BANKMASK(OVDCOND), 2, a
#define POVD3                            BANKMASK(OVDCOND), 3, a
#define POVD4                            BANKMASK(OVDCOND), 4, a
#define POVD5                            BANKMASK(OVDCOND), 5, a
#define PSA                              BANKMASK(T0CON), 3, a
#define PTCKPS0                          BANKMASK(PTCON0), 2, a
#define PTCKPS1                          BANKMASK(PTCON0), 3, a
#define PTDIR                            BANKMASK(PTCON1), 6, a
#define PTEN                             BANKMASK(PTCON1), 7, a
#define PTIE                             BANKMASK(PIE3), 4, a
#define PTIF                             BANKMASK(PIR3), 4, a
#define PTIP                             BANKMASK(IPR3), 4, a
#define PTMOD0                           BANKMASK(PTCON0), 0, a
#define PTMOD1                           BANKMASK(PTCON0), 1, a
#define PTOPS0                           BANKMASK(PTCON0), 4, a
#define PTOPS1                           BANKMASK(PTCON0), 5, a
#define PTOPS2                           BANKMASK(PTCON0), 6, a
#define PTOPS3                           BANKMASK(PTCON0), 7, a
#define PWM0                             BANKMASK(PORTB), 0, a
#define PWM1                             BANKMASK(PORTB), 1, a
#define PWM2                             BANKMASK(PORTB), 4, a
#define PWM3                             BANKMASK(PORTB), 5, a
#define PWM4                             BANKMASK(PORTB), 6, a
#define PWM5                             BANKMASK(PORTB), 7, a
#define PWMEN0                           BANKMASK(PWMCON0), 4, a
#define PWMEN1                           BANKMASK(PWMCON0), 5, a
#define PWMEN2                           BANKMASK(PWMCON0), 6, a
#define RA0                              BANKMASK(PORTA), 0, a
#define RA1                              BANKMASK(PORTA), 1, a
#define RA2                              BANKMASK(PORTA), 2, a
#define RA3                              BANKMASK(PORTA), 3, a
#define RA4                              BANKMASK(PORTA), 4, a
#define RA5                              BANKMASK(PORTA), 5, a
#define RA6                              BANKMASK(PORTA), 6, a
#define RA7                              BANKMASK(PORTA), 7, a
#define RB0                              BANKMASK(PORTB), 0, a
#define RB1                              BANKMASK(PORTB), 1, a
#define RB2                              BANKMASK(PORTB), 2, a
#define RB3                              BANKMASK(PORTB), 3, a
#define RB4                              BANKMASK(PORTB), 4, a
#define RB5                              BANKMASK(PORTB), 5, a
#define RB6                              BANKMASK(PORTB), 6, a
#define RB7                              BANKMASK(PORTB), 7, a
#define RBIE                             BANKMASK(INTCON), 3, a
#define RBIF                             BANKMASK(INTCON), 0, a
#define RBIP                             BANKMASK(INTCON2), 0, a
#define RBPU                             BANKMASK(INTCON2), 7, a
#define RC1IE                            BANKMASK(PIE1), 5, a
#define RC1IF                            BANKMASK(PIR1), 5, a
#define RC1IP                            BANKMASK(IPR1), 5, a
#define RC8_9                            BANKMASK(RCSTA), 6, a
#define RC9                              BANKMASK(RCSTA), 6, a
#define RCD8                             BANKMASK(RCSTA), 0, a
#define RCIDL                            BANKMASK(BAUDCON), 6, a
#define RCIE                             BANKMASK(PIE1), 5, a
#define RCIF                             BANKMASK(PIR1), 5, a
#define RCIP                             BANKMASK(IPR1), 5, a
#define RCMT                             BANKMASK(BAUDCON), 6, a
#define RD                               BANKMASK(EECON1), 0, a
#define RD16                             BANKMASK(T1CON), 7, a
#define RI                               BANKMASK(RCON), 4, a
#define RJPU                             BANKMASK(PORTA), 7, a
#define RX                               BANKMASK(PORTA), 3, a
#define RX9                              BANKMASK(RCSTA), 6, a
#define RX9D                             BANKMASK(RCSTA), 0, a
#define RXCKP                            BANKMASK(BAUDCON), 5, a
#define RXDTP                            BANKMASK(BAUDCON), 5, a
#define SBOREN                           BANKMASK(RCON), 6, a
#define SCKP                             BANKMASK(BAUDCON), 4, a
#define SCS0                             BANKMASK(OSCCON), 0, a
#define SCS1                             BANKMASK(OSCCON), 1, a
#define SENDB                            BANKMASK(TXSTA), 3, a
#define SENDB1                           BANKMASK(TXSTA), 3, a
#define SEVOPS0                          BANKMASK(PWMCON1), 4, a
#define SEVOPS1                          BANKMASK(PWMCON1), 5, a
#define SEVOPS2                          BANKMASK(PWMCON1), 6, a
#define SEVOPS3                          BANKMASK(PWMCON1), 7, a
#define SEVTDIR                          BANKMASK(PWMCON1), 3, a
#define SEVTEN                           BANKMASK(ADCON0), 7, a
#define SOSCEN                           BANKMASK(T1CON), 3, a
#define SP0                              BANKMASK(STKPTR), 0, a
#define SP1                              BANKMASK(STKPTR), 1, a
#define SP2                              BANKMASK(STKPTR), 2, a
#define SP3                              BANKMASK(STKPTR), 3, a
#define SP4                              BANKMASK(STKPTR), 4, a
#define SPEN                             BANKMASK(RCSTA), 7, a
#define SREN                             BANKMASK(RCSTA), 5, a
#define SRENA                            BANKMASK(RCSTA), 5, a
#define STKFUL                           BANKMASK(STKPTR), 7, a
#define STKOVF                           BANKMASK(STKPTR), 7, a
#define STKUNF                           BANKMASK(STKPTR), 6, a
#define SWDTE                            BANKMASK(WDTCON), 0, a
#define SWDTEN                           BANKMASK(WDTCON), 0, a
#define SYNC                             BANKMASK(TXSTA), 4, a
#define SYNC1                            BANKMASK(TXSTA), 4, a
#define T016BIT                          BANKMASK(T0CON), 6, a
#define T08BIT                           BANKMASK(T0CON), 6, a
#define T0CKI                            BANKMASK(PORTA), 4, a
#define T0CS                             BANKMASK(T0CON), 5, a
#define T0IE                             BANKMASK(INTCON), 5, a
#define T0IF                             BANKMASK(INTCON), 2, a
#define T0PS0                            BANKMASK(T0CON), 0, a
#define T0PS1                            BANKMASK(T0CON), 1, a
#define T0PS2                            BANKMASK(T0CON), 2, a
#define T0SE                             BANKMASK(T0CON), 4, a
#define T1CKPS0                          BANKMASK(T1CON), 4, a
#define T1CKPS1                          BANKMASK(T1CON), 5, a
#define T1OSCEN                          BANKMASK(T1CON), 3, a
#define T1RD16                           BANKMASK(T1CON), 7, a
#define T1RUN                            BANKMASK(T1CON), 6, a
#define T1SYNC                           BANKMASK(T1CON), 2, a
#define TMR0IE                           BANKMASK(INTCON), 5, a
#define TMR0IF                           BANKMASK(INTCON), 2, a
#define TMR0IP                           BANKMASK(INTCON2), 2, a
#define TMR0ON                           BANKMASK(T0CON), 7, a
#define TMR1CS                           BANKMASK(T1CON), 1, a
#define TMR1IE                           BANKMASK(PIE1), 0, a
#define TMR1IF                           BANKMASK(PIR1), 0, a
#define TMR1IP                           BANKMASK(IPR1), 0, a
#define TMR1ON                           BANKMASK(T1CON), 0, a
#define TO                               BANKMASK(RCON), 3, a
#define TRISA0                           BANKMASK(TRISA), 0, a
#define TRISA1                           BANKMASK(TRISA), 1, a
#define TRISA2                           BANKMASK(TRISA), 2, a
#define TRISA3                           BANKMASK(TRISA), 3, a
#define TRISA4                           BANKMASK(TRISA), 4, a
#define TRISA5                           BANKMASK(TRISA), 5, a
#define TRISA6                           BANKMASK(TRISA), 6, a
#define TRISA7                           BANKMASK(TRISA), 7, a
#define TRISB0                           BANKMASK(TRISB), 0, a
#define TRISB1                           BANKMASK(TRISB), 1, a
#define TRISB2                           BANKMASK(TRISB), 2, a
#define TRISB3                           BANKMASK(TRISB), 3, a
#define TRISB4                           BANKMASK(TRISB), 4, a
#define TRISB5                           BANKMASK(TRISB), 5, a
#define TRISB6                           BANKMASK(TRISB), 6, a
#define TRISB7                           BANKMASK(TRISB), 7, a
#define TRMT                             BANKMASK(TXSTA), 1, a
#define TRMT1                            BANKMASK(TXSTA), 1, a
#define TUN0                             BANKMASK(OSCTUNE), 0, a
#define TUN1                             BANKMASK(OSCTUNE), 1, a
#define TUN2                             BANKMASK(OSCTUNE), 2, a
#define TUN3                             BANKMASK(OSCTUNE), 3, a
#define TUN4                             BANKMASK(OSCTUNE), 4, a
#define TX                               BANKMASK(PORTA), 2, a
#define TX1IE                            BANKMASK(PIE1), 4, a
#define TX1IF                            BANKMASK(PIR1), 4, a
#define TX1IP                            BANKMASK(IPR1), 4, a
#define TX8_9                            BANKMASK(TXSTA), 6, a
#define TX9                              BANKMASK(TXSTA), 6, a
#define TX91                             BANKMASK(TXSTA), 6, a
#define TX9D                             BANKMASK(TXSTA), 0, a
#define TX9D1                            BANKMASK(TXSTA), 0, a
#define TXB2IE                           BANKMASK(PIE3), 4, a
#define TXBNIE                           BANKMASK(PIE3), 4, a
#define TXBNIF                           BANKMASK(PIR3), 4, a
#define TXBNIP                           BANKMASK(IPR3), 4, a
#define TXCKP                            BANKMASK(BAUDCON), 4, a
#define TXD8                             BANKMASK(TXSTA), 0, a
#define TXEN                             BANKMASK(TXSTA), 5, a
#define TXEN1                            BANKMASK(TXSTA), 5, a
#define TXIE                             BANKMASK(PIE1), 4, a
#define TXIF                             BANKMASK(PIR1), 4, a
#define TXIP                             BANKMASK(IPR1), 4, a
#define UDIS                             BANKMASK(PWMCON1), 1, a
#define ULPWUIN                          BANKMASK(PORTA), 0, a
#define VCFG                             BANKMASK(ADCON1), 4, a
#define VCFG0                            BANKMASK(ADCON1), 4, a
#define VCFG01                           BANKMASK(ADCON1), 4, a
#define VREFP                            BANKMASK(PORTA), 4, a
#define W4E                              BANKMASK(BAUDCON), 1, a
#define WR                               BANKMASK(EECON1), 1, a
#define WREN                             BANKMASK(EECON1), 2, a
#define WRERR                            BANKMASK(EECON1), 3, a
#define WUE                              BANKMASK(BAUDCON), 1, a
#define ZERO                             BANKMASK(STATUS), 2, a
#define nBOR                             BANKMASK(RCON), 0, a
#define nDONE                            BANKMASK(ADCON0), 1, a
#define nMCLR                            BANKMASK(PORTA), 5, a
#define nPD                              BANKMASK(RCON), 2, a
#define nPOR                             BANKMASK(RCON), 1, a
#define nRBPU                            BANKMASK(INTCON2), 7, a
#define nRI                              BANKMASK(RCON), 4, a
#define nT1SYNC                          BANKMASK(T1CON), 2, a
#define nTO                              BANKMASK(RCON), 3, a

/*
 * Device Psects
 */

#ifdef _XC_INC_

// Memory Spaces
#define SPACE_CODE   0
#define SPACE_DATA   1
#define SPACE_EEPROM 3

#if _COMMON_SIZE_
psect udata_acs,class=COMRAM,space=SPACE_DATA,noexec,lowdata
#endif
psect udata_bank0,class=BANK0,space=SPACE_DATA,noexec,lowdata
psect udata,class=RAM,space=SPACE_DATA,noexec
psect code,class=CODE,space=SPACE_CODE,reloc=2
psect data,class=CONST,space=SPACE_CODE,reloc=2,noexec
psect edata,class=EEDATA,space=SPACE_EEPROM,delta=1,noexec

#endif // _XC_INC_

#endif // _PIC18F1330_INC_
