#define FLT_EVAL_METHOD 0

#define LDBL_TRUE_MIN FLT_TRUE_MIN
#define LDBL_MIN FLT_MIN
#define LDBL_MAX FLT_MAX
#define LDBL_EPSILON FLT_EPSILON

#define LDBL_MANT_DIG FLT_MANT_DIG
#define LDBL_MIN_EXP FLT_MIN_EXP
#define LDBL_MAX_EXP FLT_MAX_EXP

#define LDBL_DIG FLT_DIG
#define LDBL_MIN_10_EXP FLT_MIN_10_EXP
#define LDBL_MAX_10_EXP FLT_MAX_10_EXP

#define DECIMAL_DIG FLT_DECIMAL_DIG
