// Version 2.41
// Generated 09/02/2023 GMT

/*
 * Copyright © 2023, Microchip Technology Inc. and its subsidiaries ("Microchip")
 * All rights reserved.
 * 
 * This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 *     1. Redistributions of source code must retain the above copyright notice, this list of
 *        conditions and the following disclaimer.
 * 
 *     2. Redistributions in binary form must reproduce the above copyright notice, this list
 *        of conditions and the following disclaimer in the documentation and/or other
 *        materials provided with the distribution. Publication is not required when
 *        this file is used in an embedded application.
 * 
 *     3. Microchip's name may not be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _PIC18_CHIP_SELECT_INC_
#define _PIC18_CHIP_SELECT_INC_

#define _HEADER_NOT_FOUND

#ifdef _18C242
#include <pic18c242.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18C252
#include <pic18c252.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18C442
#include <pic18c442.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18C452
#include <pic18c452.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18C601
#include <pic18c601.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18C658
#include <pic18c658.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18C801
#include <pic18c801.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18C858
#include <pic18c858.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F04Q40
#include <pic18f04q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F04Q41
#include <pic18f04q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F05Q40
#include <pic18f05q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F05Q41
#include <pic18f05q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F06Q40
#include <pic18f06q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F06Q41
#include <pic18f06q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F1220
#include <pic18f1220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F1230
#include <pic18f1230.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F1320
#include <pic18f1320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F1330
#include <pic18f1330.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F13K22
#include <pic18f13k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F13K50
#include <pic18f13k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F14K22
#include <pic18f14k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F14K22LIN
#include <pic18f14k22lin.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F14K50
#include <pic18f14k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F14Q40
#include <pic18f14q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F14Q41
#include <pic18f14q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F15Q40
#include <pic18f15q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F15Q41
#include <pic18f15q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F16Q40
#include <pic18f16q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F16Q41
#include <pic18f16q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2220
#include <pic18f2220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2221
#include <pic18f2221.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2320
#include <pic18f2320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2321
#include <pic18f2321.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2331
#include <pic18f2331.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F23K20
#include <pic18f23k20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F23K22
#include <pic18f23k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2410
#include <pic18f2410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F242
#include <pic18f242.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2420
#include <pic18f2420.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2423
#include <pic18f2423.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2431
#include <pic18f2431.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2439
#include <pic18f2439.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2450
#include <pic18f2450.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2455
#include <pic18f2455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2458
#include <pic18f2458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F248
#include <pic18f248.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2480
#include <pic18f2480.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24J10
#include <pic18f24j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24J11
#include <pic18f24j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24J50
#include <pic18f24j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24K20
#include <pic18f24k20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24K22
#include <pic18f24k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24K40
#include <pic18f24k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24K42
#include <pic18f24k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24K50
#include <pic18f24k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24Q10
#include <pic18f24q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2510
#include <pic18f2510.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2515
#include <pic18f2515.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F252
#include <pic18f252.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2520
#include <pic18f2520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2523
#include <pic18f2523.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2525
#include <pic18f2525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2539
#include <pic18f2539.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2550
#include <pic18f2550.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2553
#include <pic18f2553.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F258
#include <pic18f258.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2580
#include <pic18f2580.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2585
#include <pic18f2585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25J10
#include <pic18f25j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25J11
#include <pic18f25j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25J50
#include <pic18f25j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25K20
#include <pic18f25k20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25K22
#include <pic18f25k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25K40
#include <pic18f25k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25K42
#include <pic18f25k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25K50
#include <pic18f25k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25K80
#include <pic18f25k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25K83
#include <pic18f25k83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25Q10
#include <pic18f25q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25Q43
#include <pic18f25q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2610
#include <pic18f2610.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2620
#include <pic18f2620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2680
#include <pic18f2680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2682
#include <pic18f2682.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2685
#include <pic18f2685.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26J11
#include <pic18f26j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26J13
#include <pic18f26j13.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26J50
#include <pic18f26j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26J53
#include <pic18f26j53.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26K20
#include <pic18f26k20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26K22
#include <pic18f26k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26K40
#include <pic18f26k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26K42
#include <pic18f26k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26K80
#include <pic18f26k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26K83
#include <pic18f26k83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q10
#include <pic18f26q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q43
#include <pic18f26q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q71
#include <pic18f26q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q83
#include <pic18f26q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q84
#include <pic18f26q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27J13
#include <pic18f27j13.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27J53
#include <pic18f27j53.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27K40
#include <pic18f27k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27K42
#include <pic18f27k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27Q10
#include <pic18f27q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27Q43
#include <pic18f27q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27Q83
#include <pic18f27q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27Q84
#include <pic18f27q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4220
#include <pic18f4220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4221
#include <pic18f4221.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4320
#include <pic18f4320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4321
#include <pic18f4321.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4331
#include <pic18f4331.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F43K20
#include <pic18f43k20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F43K22
#include <pic18f43k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4410
#include <pic18f4410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F442
#include <pic18f442.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4420
#include <pic18f4420.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4423
#include <pic18f4423.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4431
#include <pic18f4431.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4439
#include <pic18f4439.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4450
#include <pic18f4450.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4455
#include <pic18f4455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4458
#include <pic18f4458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F448
#include <pic18f448.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4480
#include <pic18f4480.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F44J10
#include <pic18f44j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F44J11
#include <pic18f44j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F44J50
#include <pic18f44j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F44K20
#include <pic18f44k20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F44K22
#include <pic18f44k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4510
#include <pic18f4510.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4515
#include <pic18f4515.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F452
#include <pic18f452.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4520
#include <pic18f4520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4523
#include <pic18f4523.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4525
#include <pic18f4525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4539
#include <pic18f4539.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4550
#include <pic18f4550.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4553
#include <pic18f4553.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F458
#include <pic18f458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4580
#include <pic18f4580.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4585
#include <pic18f4585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45J10
#include <pic18f45j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45J11
#include <pic18f45j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45J50
#include <pic18f45j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45K20
#include <pic18f45k20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45K22
#include <pic18f45k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45K40
#include <pic18f45k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45K42
#include <pic18f45k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45K50
#include <pic18f45k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45K80
#include <pic18f45k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45Q10
#include <pic18f45q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45Q43
#include <pic18f45q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4610
#include <pic18f4610.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4620
#include <pic18f4620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4680
#include <pic18f4680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4682
#include <pic18f4682.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4685
#include <pic18f4685.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46J11
#include <pic18f46j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46J13
#include <pic18f46j13.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46J50
#include <pic18f46j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46J53
#include <pic18f46j53.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46K20
#include <pic18f46k20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46K22
#include <pic18f46k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46K40
#include <pic18f46k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46K42
#include <pic18f46k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46K80
#include <pic18f46k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q10
#include <pic18f46q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q43
#include <pic18f46q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q71
#include <pic18f46q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q83
#include <pic18f46q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q84
#include <pic18f46q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47J13
#include <pic18f47j13.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47J53
#include <pic18f47j53.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47K40
#include <pic18f47k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47K42
#include <pic18f47k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47Q10
#include <pic18f47q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47Q43
#include <pic18f47q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47Q83
#include <pic18f47q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47Q84
#include <pic18f47q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F55K42
#include <pic18f55k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F55Q43
#include <pic18f55q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56K42
#include <pic18f56k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q43
#include <pic18f56q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q71
#include <pic18f56q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q83
#include <pic18f56q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q84
#include <pic18f56q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F57K42
#include <pic18f57k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F57Q43
#include <pic18f57q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F57Q83
#include <pic18f57q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F57Q84
#include <pic18f57q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6310
#include <pic18f6310.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6390
#include <pic18f6390.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6393
#include <pic18f6393.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F63J11
#include <pic18f63j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F63J90
#include <pic18f63j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6410
#include <pic18f6410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6490
#include <pic18f6490.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6493
#include <pic18f6493.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F64J11
#include <pic18f64j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F64J90
#include <pic18f64j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6520
#include <pic18f6520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6525
#include <pic18f6525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6527
#include <pic18f6527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6585
#include <pic18f6585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65J10
#include <pic18f65j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65J11
#include <pic18f65j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65J15
#include <pic18f65j15.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65J50
#include <pic18f65j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65J90
#include <pic18f65j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65J94
#include <pic18f65j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65K22
#include <pic18f65k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65K40
#include <pic18f65k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65K80
#include <pic18f65k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F65K90
#include <pic18f65k90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6620
#include <pic18f6620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6621
#include <pic18f6621.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6622
#include <pic18f6622.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6627
#include <pic18f6627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6628
#include <pic18f6628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6680
#include <pic18f6680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J10
#include <pic18f66j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J11
#include <pic18f66j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J15
#include <pic18f66j15.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J16
#include <pic18f66j16.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J50
#include <pic18f66j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J55
#include <pic18f66j55.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J60
#include <pic18f66j60.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J65
#include <pic18f66j65.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J90
#include <pic18f66j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J93
#include <pic18f66j93.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J94
#include <pic18f66j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66J99
#include <pic18f66j99.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66K22
#include <pic18f66k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66K40
#include <pic18f66k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66K80
#include <pic18f66k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F66K90
#include <pic18f66k90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6720
#include <pic18f6720.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6722
#include <pic18f6722.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6723
#include <pic18f6723.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67J10
#include <pic18f67j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67J11
#include <pic18f67j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67J50
#include <pic18f67j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67J60
#include <pic18f67j60.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67J90
#include <pic18f67j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67J93
#include <pic18f67j93.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67J94
#include <pic18f67j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67K22
#include <pic18f67k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67K40
#include <pic18f67k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F67K90
#include <pic18f67k90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8310
#include <pic18f8310.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8390
#include <pic18f8390.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8393
#include <pic18f8393.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F83J11
#include <pic18f83j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F83J90
#include <pic18f83j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8410
#include <pic18f8410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8490
#include <pic18f8490.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8493
#include <pic18f8493.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F84J11
#include <pic18f84j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F84J90
#include <pic18f84j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8520
#include <pic18f8520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8525
#include <pic18f8525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8527
#include <pic18f8527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8585
#include <pic18f8585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F85J10
#include <pic18f85j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F85J11
#include <pic18f85j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F85J15
#include <pic18f85j15.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F85J50
#include <pic18f85j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F85J90
#include <pic18f85j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F85J94
#include <pic18f85j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F85K22
#include <pic18f85k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F85K90
#include <pic18f85k90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8620
#include <pic18f8620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8621
#include <pic18f8621.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8622
#include <pic18f8622.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8627
#include <pic18f8627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8628
#include <pic18f8628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8680
#include <pic18f8680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J10
#include <pic18f86j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J11
#include <pic18f86j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J15
#include <pic18f86j15.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J16
#include <pic18f86j16.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J50
#include <pic18f86j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J55
#include <pic18f86j55.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J60
#include <pic18f86j60.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J65
#include <pic18f86j65.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J72
#include <pic18f86j72.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J90
#include <pic18f86j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J93
#include <pic18f86j93.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J94
#include <pic18f86j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86J99
#include <pic18f86j99.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86K22
#include <pic18f86k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F86K90
#include <pic18f86k90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8720
#include <pic18f8720.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8722
#include <pic18f8722.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8723
#include <pic18f8723.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87J10
#include <pic18f87j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87J11
#include <pic18f87j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87J50
#include <pic18f87j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87J60
#include <pic18f87j60.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87J72
#include <pic18f87j72.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87J90
#include <pic18f87j90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87J93
#include <pic18f87j93.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87J94
#include <pic18f87j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87K22
#include <pic18f87k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F87K90
#include <pic18f87k90.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F95J94
#include <pic18f95j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F96J60
#include <pic18f96j60.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F96J65
#include <pic18f96j65.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F96J94
#include <pic18f96j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F96J99
#include <pic18f96j99.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F97J60
#include <pic18f97j60.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F97J94
#include <pic18f97j94.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF1220
#include <pic18lf1220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF1230
#include <pic18lf1230.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF1320
#include <pic18lf1320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF1330
#include <pic18lf1330.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF13K22
#include <pic18lf13k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF13K50
#include <pic18lf13k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF14K22
#include <pic18lf14k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF14K50
#include <pic18lf14k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2220
#include <pic18lf2220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2221
#include <pic18lf2221.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2320
#include <pic18lf2320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2321
#include <pic18lf2321.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2331
#include <pic18lf2331.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF23K22
#include <pic18lf23k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2410
#include <pic18lf2410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF242
#include <pic18lf242.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2420
#include <pic18lf2420.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2423
#include <pic18lf2423.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2431
#include <pic18lf2431.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2439
#include <pic18lf2439.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2450
#include <pic18lf2450.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2455
#include <pic18lf2455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2458
#include <pic18lf2458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF248
#include <pic18lf248.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2480
#include <pic18lf2480.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF24J10
#include <pic18lf24j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF24J11
#include <pic18lf24j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF24J50
#include <pic18lf24j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF24K22
#include <pic18lf24k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF24K40
#include <pic18lf24k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF24K42
#include <pic18lf24k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF24K50
#include <pic18lf24k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2510
#include <pic18lf2510.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2515
#include <pic18lf2515.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF252
#include <pic18lf252.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2520
#include <pic18lf2520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2523
#include <pic18lf2523.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2525
#include <pic18lf2525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2539
#include <pic18lf2539.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2550
#include <pic18lf2550.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2553
#include <pic18lf2553.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF258
#include <pic18lf258.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2580
#include <pic18lf2580.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2585
#include <pic18lf2585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25J10
#include <pic18lf25j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25J11
#include <pic18lf25j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25J50
#include <pic18lf25j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25K22
#include <pic18lf25k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25K40
#include <pic18lf25k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25K42
#include <pic18lf25k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25K50
#include <pic18lf25k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25K80
#include <pic18lf25k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF25K83
#include <pic18lf25k83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2610
#include <pic18lf2610.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2620
#include <pic18lf2620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2680
#include <pic18lf2680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2682
#include <pic18lf2682.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2685
#include <pic18lf2685.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26J11
#include <pic18lf26j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26J13
#include <pic18lf26j13.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26J50
#include <pic18lf26j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26J53
#include <pic18lf26j53.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26K22
#include <pic18lf26k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26K40
#include <pic18lf26k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26K42
#include <pic18lf26k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26K80
#include <pic18lf26k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF26K83
#include <pic18lf26k83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF27J13
#include <pic18lf27j13.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF27J53
#include <pic18lf27j53.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF27K40
#include <pic18lf27k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF27K42
#include <pic18lf27k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4220
#include <pic18lf4220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4221
#include <pic18lf4221.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4320
#include <pic18lf4320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4321
#include <pic18lf4321.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4331
#include <pic18lf4331.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF43K22
#include <pic18lf43k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4410
#include <pic18lf4410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF442
#include <pic18lf442.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4420
#include <pic18lf4420.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4423
#include <pic18lf4423.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4431
#include <pic18lf4431.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4439
#include <pic18lf4439.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4450
#include <pic18lf4450.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4455
#include <pic18lf4455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4458
#include <pic18lf4458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF448
#include <pic18lf448.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4480
#include <pic18lf4480.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF44J10
#include <pic18lf44j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF44J11
#include <pic18lf44j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF44J50
#include <pic18lf44j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF44K22
#include <pic18lf44k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4510
#include <pic18lf4510.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4515
#include <pic18lf4515.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF452
#include <pic18lf452.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4520
#include <pic18lf4520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4523
#include <pic18lf4523.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4525
#include <pic18lf4525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4539
#include <pic18lf4539.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4550
#include <pic18lf4550.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4553
#include <pic18lf4553.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF458
#include <pic18lf458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4580
#include <pic18lf4580.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4585
#include <pic18lf4585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF45J10
#include <pic18lf45j10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF45J11
#include <pic18lf45j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF45J50
#include <pic18lf45j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF45K22
#include <pic18lf45k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF45K40
#include <pic18lf45k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF45K42
#include <pic18lf45k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF45K50
#include <pic18lf45k50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF45K80
#include <pic18lf45k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4610
#include <pic18lf4610.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4620
#include <pic18lf4620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4680
#include <pic18lf4680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4682
#include <pic18lf4682.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4685
#include <pic18lf4685.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF46J11
#include <pic18lf46j11.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF46J13
#include <pic18lf46j13.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF46J50
#include <pic18lf46j50.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF46J53
#include <pic18lf46j53.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF46K22
#include <pic18lf46k22.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF46K40
#include <pic18lf46k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF46K42
#include <pic18lf46k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF46K80
#include <pic18lf46k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF47J13
#include <pic18lf47j13.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF47J53
#include <pic18lf47j53.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF47K40
#include <pic18lf47k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF47K42
#include <pic18lf47k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF55K42
#include <pic18lf55k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF56K42
#include <pic18lf56k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF57K42
#include <pic18lf57k42.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6310
#include <pic18lf6310.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6390
#include <pic18lf6390.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6393
#include <pic18lf6393.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6410
#include <pic18lf6410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6490
#include <pic18lf6490.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6493
#include <pic18lf6493.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6520
#include <pic18lf6520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6525
#include <pic18lf6525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6527
#include <pic18lf6527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6585
#include <pic18lf6585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF65K40
#include <pic18lf65k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF65K80
#include <pic18lf65k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6620
#include <pic18lf6620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6621
#include <pic18lf6621.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6622
#include <pic18lf6622.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6627
#include <pic18lf6627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6628
#include <pic18lf6628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6680
#include <pic18lf6680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF66K40
#include <pic18lf66k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF66K80
#include <pic18lf66k80.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6720
#include <pic18lf6720.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6722
#include <pic18lf6722.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6723
#include <pic18lf6723.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF67K40
#include <pic18lf67k40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8310
#include <pic18lf8310.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8390
#include <pic18lf8390.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8393
#include <pic18lf8393.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8410
#include <pic18lf8410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8490
#include <pic18lf8490.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8493
#include <pic18lf8493.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8520
#include <pic18lf8520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8525
#include <pic18lf8525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8527
#include <pic18lf8527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8585
#include <pic18lf8585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8620
#include <pic18lf8620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8621
#include <pic18lf8621.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8622
#include <pic18lf8622.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8627
#include <pic18lf8627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8628
#include <pic18lf8628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8680
#include <pic18lf8680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8720
#include <pic18lf8720.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8722
#include <pic18lf8722.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8723
#include <pic18lf8723.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _TEST_CHIP_
#undef _HEADER_NOT_FOUND
#endif

#ifdef _HEADER_NOT_FOUND
#error Device-specific header could not be found for target chip
#endif

#endif // _PIC18_CHIP_SELECT_INC_
