// Generated 09/02/2023 GMT

/*
 * Copyright © 2023, Microchip Technology Inc. and its subsidiaries ("Microchip")
 * All rights reserved.
 * 
 * This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 *     1. Redistributions of source code must retain the above copyright notice, this list of
 *        conditions and the following disclaimer.
 * 
 *     2. Redistributions in binary form must reproduce the above copyright notice, this list
 *        of conditions and the following disclaimer in the documentation and/or other
 *        materials provided with the distribution. Publication is not required when
 *        this file is used in an embedded application.
 * 
 *     3. Microchip's name may not be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _PIC_AS_CHIP_SELECT_INC_
#define _PIC_AS_CHIP_SELECT_INC_

#define _HEADER_NOT_FOUND

#ifdef _MCP19110
#include <mcp19110.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19111
#include <mcp19111.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19114
#include <mcp19114.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19115
#include <mcp19115.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19116
#include <mcp19116.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19117
#include <mcp19117.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19118
#include <mcp19118.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19119
#include <mcp19119.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19120
#include <mcp19120.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19121
#include <mcp19121.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19122
#include <mcp19122.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19123
#include <mcp19123.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19124
#include <mcp19124.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19125
#include <mcp19125.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19126
#include <mcp19126.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19128
#include <mcp19128.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19132
#include <mcp19132.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19133
#include <mcp19133.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19214
#include <mcp19214.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19215
#include <mcp19215.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCP19625
#include <mcp19625.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCV08A
#ifdef _LEGACY_HEADERS
#include <asmcv08a_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <mcv08a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _MCV14A
#ifdef _LEGACY_HEADERS
#include <asmcv14a_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <mcv14a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _MCV18A
#ifdef _LEGACY_HEADERS
#include <asmcv28a_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <mcv18a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _MCV18E
#include <mcv18e.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _MCV28A
#ifdef _LEGACY_HEADERS
#include <asmcv28a_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <mcv28a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _10F200
#ifdef _LEGACY_HEADERS
#include <as10f20x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic10f200.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _10F202
#ifdef _LEGACY_HEADERS
#include <as10f20x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic10f202.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _10F204
#ifdef _LEGACY_HEADERS
#include <as10f20x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic10f204.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _10F206
#ifdef _LEGACY_HEADERS
#include <as10f20x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic10f206.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _10F220
#ifdef _LEGACY_HEADERS
#include <as10f22x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic10f220.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _10F222
#ifdef _LEGACY_HEADERS
#include <as10f22x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic10f222.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _10F320
#include <pic10f320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _10F322
#include <pic10f322.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _10LF320
#include <pic10lf320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _10LF322
#include <pic10lf322.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12C508
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12c508.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12C508A
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12c508a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12C509
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12c509.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12C509A
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12c509a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12C671
#ifdef _LEGACY_HEADERS
#include <as1267x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12c671.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12C672
#ifdef _LEGACY_HEADERS
#include <as1267x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12c672.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12CE518
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12ce518.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12CE519
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12ce519.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12CE673
#ifdef _LEGACY_HEADERS
#include <as1267x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12ce673.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12CE674
#ifdef _LEGACY_HEADERS
#include <as1267x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12ce674.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12CR509A
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12cr509a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F1501
#include <pic12f1501.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1571
#include <pic12f1571.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1572
#include <pic12f1572.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1612
#include <pic12f1612.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1822
#include <pic12f1822.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1840
#include <pic12f1840.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F508
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f508.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F509
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f509.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F510
#ifdef _LEGACY_HEADERS
#include <as12f510_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f510.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F519
#ifdef _LEGACY_HEADERS
#include <as12f519_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f519.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F529T39A
#include <pic12f529t39a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F529T48A
#include <pic12f529t48a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F609
#ifdef _LEGACY_HEADERS
#include <as12f615_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f609.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F615
#ifdef _LEGACY_HEADERS
#include <as12f615_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f615.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F617
#ifdef _LEGACY_HEADERS
#include <as12f617_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f617.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F629
#ifdef _LEGACY_HEADERS
#include <as12f6x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f629.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F635
#ifdef _LEGACY_HEADERS
#include <as16f636_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f635.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F675
#ifdef _LEGACY_HEADERS
#include <as12f6x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f675.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F683
#ifdef _LEGACY_HEADERS
#include <as12f683_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f683.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12F752
#include <pic12f752.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12HV609
#ifdef _LEGACY_HEADERS
#include <as12f615_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12hv609.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12HV615
#ifdef _LEGACY_HEADERS
#include <as12f615_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12hv615.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _12HV752
#include <pic12hv752.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1501
#include <pic12lf1501.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1552
#include <pic12lf1552.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1571
#include <pic12lf1571.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1572
#include <pic12lf1572.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1612
#include <pic12lf1612.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1822
#include <pic12lf1822.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1840
#include <pic12lf1840.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1840T39A
#include <pic12lf1840t39a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1840T48A
#include <pic12lf1840t48a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16C432
#ifdef _LEGACY_HEADERS
#include <as1643x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c432.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C433
#ifdef _LEGACY_HEADERS
#include <as1643x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c433.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C505
#ifdef _LEGACY_HEADERS
#include <as16505_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c505.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C54
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c54.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C54A
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c54a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C54C
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c54c.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C55
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c55.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C554
#ifdef _LEGACY_HEADERS
#include <as1655x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c554.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C557
#ifdef _LEGACY_HEADERS
#include <as1655x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c557.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C558
#ifdef _LEGACY_HEADERS
#include <as1655x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c558.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C55A
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c55a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C56
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c56.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C56A
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c56a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C57
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c57.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C57C
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c57c.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C58A
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c58a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C58B
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c58b.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C620
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c620.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C620A
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c620a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C621
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c621.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C621A
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c621a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C622
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c622.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C622A
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c622a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C62A
#ifdef _LEGACY_HEADERS
#include <as1662_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c62a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C62B
#ifdef _LEGACY_HEADERS
#include <as1662_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c62b.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C63
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c63.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C63A
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c63a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C642
#ifdef _LEGACY_HEADERS
#include <as166xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c642.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C64A
#ifdef _LEGACY_HEADERS
#include <as1664_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c64a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C65A
#ifdef _LEGACY_HEADERS
#include <as1665_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c65a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C65B
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c65b.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C66
#ifdef _LEGACY_HEADERS
#include <as166x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c66.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C662
#ifdef _LEGACY_HEADERS
#include <as166xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c662.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C67
#ifdef _LEGACY_HEADERS
#include <as166x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c67.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C71
#ifdef _LEGACY_HEADERS
#include <as1671x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c71.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C710
#ifdef _LEGACY_HEADERS
#include <as1671x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c710.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C711
#ifdef _LEGACY_HEADERS
#include <as1671x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c711.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C712
#ifdef _LEGACY_HEADERS
#include <as16715_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c712.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C715
#ifdef _LEGACY_HEADERS
#include <as16715_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c715.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C716
#ifdef _LEGACY_HEADERS
#include <as16715_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c716.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C717
#ifdef _LEGACY_HEADERS
#include <as1677x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c717.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C72
#ifdef _LEGACY_HEADERS
#include <as1672_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c72.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C72A
#ifdef _LEGACY_HEADERS
#include <as1672_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c72a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C73A
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c73a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C73B
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c73b.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C745
#ifdef _LEGACY_HEADERS
#include <as1677x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c745.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C74A
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c74a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C74B
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c74b.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C76
#ifdef _LEGACY_HEADERS
#include <as1677_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c76.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C765
#ifdef _LEGACY_HEADERS
#include <as1677x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c765.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C77
#ifdef _LEGACY_HEADERS
#include <as1677_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c77.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C770
#ifdef _LEGACY_HEADERS
#include <as1677x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c770.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C771
#ifdef _LEGACY_HEADERS
#include <as1677x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c771.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C773
#ifdef _LEGACY_HEADERS
#include <as1677x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c773.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C774
#ifdef _LEGACY_HEADERS
#include <as1677x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c774.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C781
#ifdef _LEGACY_HEADERS
#include <as1678x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c781.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C782
#ifdef _LEGACY_HEADERS
#include <as1678x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c782.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C923
#ifdef _LEGACY_HEADERS
#include <as169xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c923.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C924
#ifdef _LEGACY_HEADERS
#include <as169xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c924.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C925
#ifdef _LEGACY_HEADERS
#include <as169xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c925.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16C926
#ifdef _LEGACY_HEADERS
#include <as169xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16c926.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CE623
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16ce623.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CE624
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16ce624.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CE625
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16ce625.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR54
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr54.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR54A
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr54a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR54C
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr54c.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR56A
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr56a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR57B
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr57b.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR57C
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr57c.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR58A
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr58a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR58B
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr58b.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR62
#ifdef _LEGACY_HEADERS
#include <as1662_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr62.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR620A
#ifdef _LEGACY_HEADERS
#include <as1662x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr620a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR63
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr63.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR64
#ifdef _LEGACY_HEADERS
#include <as1664_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr64.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR65
#ifdef _LEGACY_HEADERS
#include <as1665_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr65.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR72
#ifdef _LEGACY_HEADERS
#include <as1672_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr72.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR73
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr73.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR74
#ifdef _LEGACY_HEADERS
#include <as1674_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr74.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR76
#ifdef _LEGACY_HEADERS
#include <as1677_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr76.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR77
#ifdef _LEGACY_HEADERS
#include <as1677_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr77.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR83
#ifdef _LEGACY_HEADERS
#include <as1684_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr83.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR84
#ifdef _LEGACY_HEADERS
#include <as1684_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr84.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16CR926
#ifdef _LEGACY_HEADERS
#include <as169xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16cr926.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F1454
#include <pic16f1454.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1455
#include <pic16f1455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1459
#include <pic16f1459.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1503
#include <pic16f1503.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1507
#include <pic16f1507.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1508
#include <pic16f1508.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1509
#include <pic16f1509.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1512
#include <pic16f1512.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1513
#include <pic16f1513.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1516
#include <pic16f1516.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1517
#include <pic16f1517.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1518
#include <pic16f1518.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1519
#include <pic16f1519.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15213
#include <pic16f15213.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15214
#include <pic16f15214.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15223
#include <pic16f15223.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15224
#include <pic16f15224.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15225
#include <pic16f15225.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15243
#include <pic16f15243.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15244
#include <pic16f15244.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15245
#include <pic16f15245.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15254
#include <pic16f15254.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15255
#include <pic16f15255.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15256
#include <pic16f15256.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1526
#include <pic16f1526.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1527
#include <pic16f1527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15274
#include <pic16f15274.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15275
#include <pic16f15275.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15276
#include <pic16f15276.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15313
#include <pic16f15313.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15323
#include <pic16f15323.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15324
#include <pic16f15324.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15325
#include <pic16f15325.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15344
#include <pic16f15344.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15345
#include <pic16f15345.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15354
#include <pic16f15354.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15355
#include <pic16f15355.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15356
#include <pic16f15356.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15375
#include <pic16f15375.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15376
#include <pic16f15376.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15385
#include <pic16f15385.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F15386
#include <pic16f15386.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1574
#include <pic16f1574.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1575
#include <pic16f1575.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1578
#include <pic16f1578.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1579
#include <pic16f1579.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1613
#include <pic16f1613.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1614
#include <pic16f1614.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1615
#include <pic16f1615.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1618
#include <pic16f1618.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1619
#include <pic16f1619.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1703
#include <pic16f1703.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1704
#include <pic16f1704.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1705
#include <pic16f1705.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1707
#include <pic16f1707.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1708
#include <pic16f1708.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1709
#include <pic16f1709.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F17114
#include <pic16f17114.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F17115
#include <pic16f17115.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F17124
#include <pic16f17124.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F17125
#include <pic16f17125.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F17126
#include <pic16f17126.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1713
#include <pic16f1713.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F17144
#include <pic16f17144.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F17145
#include <pic16f17145.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F17146
#include <pic16f17146.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1716
#include <pic16f1716.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1717
#include <pic16f1717.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1718
#include <pic16f1718.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1719
#include <pic16f1719.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1764
#include <pic16f1764.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1765
#include <pic16f1765.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1768
#include <pic16f1768.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1769
#include <pic16f1769.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1773
#include <pic16f1773.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1776
#include <pic16f1776.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1777
#include <pic16f1777.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1778
#include <pic16f1778.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1779
#include <pic16f1779.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1782
#include <pic16f1782.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1783
#include <pic16f1783.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1784
#include <pic16f1784.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1786
#include <pic16f1786.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1787
#include <pic16f1787.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1788
#include <pic16f1788.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1789
#include <pic16f1789.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18015
#include <pic16f18015.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18025
#include <pic16f18025.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18026
#include <pic16f18026.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18044
#include <pic16f18044.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18045
#include <pic16f18045.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18046
#include <pic16f18046.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18054
#include <pic16f18054.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18055
#include <pic16f18055.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18056
#include <pic16f18056.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18074
#include <pic16f18074.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18075
#include <pic16f18075.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18076
#include <pic16f18076.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18114
#include <pic16f18114.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18115
#include <pic16f18115.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18124
#include <pic16f18124.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18125
#include <pic16f18125.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18126
#include <pic16f18126.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18144
#include <pic16f18144.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18145
#include <pic16f18145.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18146
#include <pic16f18146.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1823
#include <pic16f1823.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1824
#include <pic16f1824.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1825
#include <pic16f1825.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1826
#include <pic16f1826.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1827
#include <pic16f1827.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1828
#include <pic16f1828.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1829
#include <pic16f1829.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1829LIN
#include <pic16f1829lin.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18313
#include <pic16f18313.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18323
#include <pic16f18323.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18324
#include <pic16f18324.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18325
#include <pic16f18325.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18326
#include <pic16f18326.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18344
#include <pic16f18344.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18345
#include <pic16f18345.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18346
#include <pic16f18346.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18424
#include <pic16f18424.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18425
#include <pic16f18425.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18426
#include <pic16f18426.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18444
#include <pic16f18444.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18445
#include <pic16f18445.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18446
#include <pic16f18446.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18455
#include <pic16f18455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18456
#include <pic16f18456.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1847
#include <pic16f1847.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18854
#include <pic16f18854.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18855
#include <pic16f18855.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18856
#include <pic16f18856.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18857
#include <pic16f18857.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18875
#include <pic16f18875.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18876
#include <pic16f18876.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F18877
#include <pic16f18877.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19155
#include <pic16f19155.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19156
#include <pic16f19156.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19175
#include <pic16f19175.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19176
#include <pic16f19176.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19185
#include <pic16f19185.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19186
#include <pic16f19186.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19195
#include <pic16f19195.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19196
#include <pic16f19196.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F19197
#include <pic16f19197.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1933
#include <pic16f1933.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1934
#include <pic16f1934.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1936
#include <pic16f1936.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1937
#include <pic16f1937.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1938
#include <pic16f1938.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1939
#include <pic16f1939.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1946
#include <pic16f1946.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1947
#include <pic16f1947.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F505
#ifdef _LEGACY_HEADERS
#include <as16505_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f505.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F506
#ifdef _LEGACY_HEADERS
#include <as16f506_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f506.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F526
#ifdef _LEGACY_HEADERS
#include <as16f526_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f526.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F527
#include <pic16f527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F54
#ifdef _LEGACY_HEADERS
#include <as16f5x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f54.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F57
#ifdef _LEGACY_HEADERS
#include <as16f5x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f57.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F570
#include <pic16f570.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F59
#ifdef _LEGACY_HEADERS
#include <as16f5x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f59.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F610
#ifdef _LEGACY_HEADERS
#include <as16f616_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f610.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F616
#ifdef _LEGACY_HEADERS
#include <as16f616_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f616.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F627
#ifdef _LEGACY_HEADERS
#include <as16f6x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f627.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F627A
#ifdef _LEGACY_HEADERS
#include <as16f62xa_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f627a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F628
#ifdef _LEGACY_HEADERS
#include <as16f6x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f628.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F628A
#ifdef _LEGACY_HEADERS
#include <as16f62xa_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f628a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F630
#ifdef _LEGACY_HEADERS
#include <as16630_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f630.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F631
#ifdef _LEGACY_HEADERS
#include <as16f685_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f631.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F636
#ifdef _LEGACY_HEADERS
#include <as16f636_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f636.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F639
#ifdef _LEGACY_HEADERS
#include <as16f636_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f639.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F648A
#ifdef _LEGACY_HEADERS
#include <as16f62xa_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f648a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F676
#ifdef _LEGACY_HEADERS
#include <as16630_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f676.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F677
#ifdef _LEGACY_HEADERS
#include <as16f685_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f677.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F684
#ifdef _LEGACY_HEADERS
#include <as16f684_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f684.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F685
#ifdef _LEGACY_HEADERS
#include <as16f685_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f685.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F687
#ifdef _LEGACY_HEADERS
#include <as16f685_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f687.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F688
#ifdef _LEGACY_HEADERS
#include <as16f688_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f688.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F689
#ifdef _LEGACY_HEADERS
#include <as16f685_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f689.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F690
#ifdef _LEGACY_HEADERS
#include <as16f685_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f690.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F707
#include <pic16f707.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F716
#ifdef _LEGACY_HEADERS
#include <as16f716_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f716.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F72
#ifdef _LEGACY_HEADERS
#include <as16f7x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f72.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F720
#ifdef _LEGACY_HEADERS
#include <as16f720_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f720.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F721
#ifdef _LEGACY_HEADERS
#include <as16f721_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f721.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F722
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f722.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F722A
#include <pic16f722a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F723
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f723.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F723A
#include <pic16f723a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F724
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f724.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F726
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f726.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F727
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f727.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F73
#ifdef _LEGACY_HEADERS
#include <as16f7x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f73.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F737
#ifdef _LEGACY_HEADERS
#include <as16f7x7_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f737.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F74
#ifdef _LEGACY_HEADERS
#include <as16f7x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f74.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F747
#ifdef _LEGACY_HEADERS
#include <as16f7x7_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f747.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F753
#include <pic16f753.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F76
#ifdef _LEGACY_HEADERS
#include <as16f7x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f76.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F767
#ifdef _LEGACY_HEADERS
#include <as16f7x7_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f767.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F77
#ifdef _LEGACY_HEADERS
#include <as16f7x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f77.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F777
#ifdef _LEGACY_HEADERS
#include <as16f7x7_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f777.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F785
#ifdef _LEGACY_HEADERS
#include <as16f785_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f785.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F818
#ifdef _LEGACY_HEADERS
#include <as16f81x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f818.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F819
#ifdef _LEGACY_HEADERS
#include <as16f81x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f819.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F83
#ifdef _LEGACY_HEADERS
#include <as1684_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f83.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F84
#ifdef _LEGACY_HEADERS
#include <as1684_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f84.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F84A
#ifdef _LEGACY_HEADERS
#include <as1684_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f84a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F87
#ifdef _LEGACY_HEADERS
#include <as16f87_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f87.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F870
#ifdef _LEGACY_HEADERS
#include <as1687x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f870.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F871
#ifdef _LEGACY_HEADERS
#include <as1687x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f871.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F872
#ifdef _LEGACY_HEADERS
#include <as1687x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f872.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F873
#ifdef _LEGACY_HEADERS
#include <as1687x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f873.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F873A
#ifdef _LEGACY_HEADERS
#include <as168xa_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f873a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F874
#ifdef _LEGACY_HEADERS
#include <as1687x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f874.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F874A
#ifdef _LEGACY_HEADERS
#include <as168xa_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f874a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F876
#ifdef _LEGACY_HEADERS
#include <as1687x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f876.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F876A
#ifdef _LEGACY_HEADERS
#include <as168xa_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f876a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F877
#ifdef _LEGACY_HEADERS
#include <as1687x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f877.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F877A
#ifdef _LEGACY_HEADERS
#include <as168xa_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f877a.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F88
#ifdef _LEGACY_HEADERS
#include <as16f87_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f88.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F882
#ifdef _LEGACY_HEADERS
#include <as16f887_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f882.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F883
#ifdef _LEGACY_HEADERS
#include <as16f887_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f883.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F884
#ifdef _LEGACY_HEADERS
#include <as16f887_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f884.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F886
#ifdef _LEGACY_HEADERS
#include <as16f887_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f886.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F887
#ifdef _LEGACY_HEADERS
#include <as16f887_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f887.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F913
#ifdef _LEGACY_HEADERS
#include <as16f91x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f913.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F914
#ifdef _LEGACY_HEADERS
#include <as16f91x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f914.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F916
#ifdef _LEGACY_HEADERS
#include <as16f91x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f916.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F917
#ifdef _LEGACY_HEADERS
#include <as16f91x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f917.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16F946
#ifdef _LEGACY_HEADERS
#include <as16f946_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16f946.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16HV540
#ifdef _LEGACY_HEADERS
#include <as165x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16hv540.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16HV610
#ifdef _LEGACY_HEADERS
#include <as16f616_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16hv610.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16HV616
#ifdef _LEGACY_HEADERS
#include <as16f616_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16hv616.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16HV753
#include <pic16hv753.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16HV785
#ifdef _LEGACY_HEADERS
#include <as16f785_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16hv785.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16LF1454
#include <pic16lf1454.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1455
#include <pic16lf1455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1459
#include <pic16lf1459.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1503
#include <pic16lf1503.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1507
#include <pic16lf1507.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1508
#include <pic16lf1508.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1509
#include <pic16lf1509.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1512
#include <pic16lf1512.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1513
#include <pic16lf1513.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1516
#include <pic16lf1516.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1517
#include <pic16lf1517.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1518
#include <pic16lf1518.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1519
#include <pic16lf1519.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1526
#include <pic16lf1526.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1527
#include <pic16lf1527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15313
#include <pic16lf15313.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15323
#include <pic16lf15323.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15324
#include <pic16lf15324.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15325
#include <pic16lf15325.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15344
#include <pic16lf15344.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15345
#include <pic16lf15345.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15354
#include <pic16lf15354.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15355
#include <pic16lf15355.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15356
#include <pic16lf15356.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15375
#include <pic16lf15375.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15376
#include <pic16lf15376.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15385
#include <pic16lf15385.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF15386
#include <pic16lf15386.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1554
#include <pic16lf1554.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1559
#include <pic16lf1559.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1566
#include <pic16lf1566.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1567
#include <pic16lf1567.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1574
#include <pic16lf1574.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1575
#include <pic16lf1575.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1578
#include <pic16lf1578.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1579
#include <pic16lf1579.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1613
#include <pic16lf1613.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1614
#include <pic16lf1614.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1615
#include <pic16lf1615.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1618
#include <pic16lf1618.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1619
#include <pic16lf1619.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1703
#include <pic16lf1703.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1704
#include <pic16lf1704.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1705
#include <pic16lf1705.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1707
#include <pic16lf1707.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1708
#include <pic16lf1708.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1709
#include <pic16lf1709.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1713
#include <pic16lf1713.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1716
#include <pic16lf1716.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1717
#include <pic16lf1717.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1718
#include <pic16lf1718.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1719
#include <pic16lf1719.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1764
#include <pic16lf1764.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1765
#include <pic16lf1765.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1768
#include <pic16lf1768.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1769
#include <pic16lf1769.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1773
#include <pic16lf1773.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1776
#include <pic16lf1776.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1777
#include <pic16lf1777.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1778
#include <pic16lf1778.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1779
#include <pic16lf1779.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1782
#include <pic16lf1782.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1783
#include <pic16lf1783.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1784
#include <pic16lf1784.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1786
#include <pic16lf1786.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1787
#include <pic16lf1787.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1788
#include <pic16lf1788.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1789
#include <pic16lf1789.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1823
#include <pic16lf1823.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1824
#include <pic16lf1824.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1824T39A
#include <pic16lf1824t39a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1825
#include <pic16lf1825.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1826
#include <pic16lf1826.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1827
#include <pic16lf1827.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1828
#include <pic16lf1828.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1829
#include <pic16lf1829.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18313
#include <pic16lf18313.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18323
#include <pic16lf18323.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18324
#include <pic16lf18324.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18325
#include <pic16lf18325.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18326
#include <pic16lf18326.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18344
#include <pic16lf18344.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18345
#include <pic16lf18345.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18346
#include <pic16lf18346.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18424
#include <pic16lf18424.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18425
#include <pic16lf18425.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18426
#include <pic16lf18426.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18444
#include <pic16lf18444.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18445
#include <pic16lf18445.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18446
#include <pic16lf18446.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18455
#include <pic16lf18455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18456
#include <pic16lf18456.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1847
#include <pic16lf1847.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18854
#include <pic16lf18854.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18855
#include <pic16lf18855.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18856
#include <pic16lf18856.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18857
#include <pic16lf18857.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18875
#include <pic16lf18875.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18876
#include <pic16lf18876.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF18877
#include <pic16lf18877.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1902
#include <pic16lf1902.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1903
#include <pic16lf1903.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1904
#include <pic16lf1904.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1906
#include <pic16lf1906.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1907
#include <pic16lf1907.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19155
#include <pic16lf19155.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19156
#include <pic16lf19156.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19175
#include <pic16lf19175.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19176
#include <pic16lf19176.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19185
#include <pic16lf19185.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19186
#include <pic16lf19186.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19195
#include <pic16lf19195.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19196
#include <pic16lf19196.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF19197
#include <pic16lf19197.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1933
#include <pic16lf1933.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1934
#include <pic16lf1934.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1936
#include <pic16lf1936.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1937
#include <pic16lf1937.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1938
#include <pic16lf1938.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1939
#include <pic16lf1939.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1946
#include <pic16lf1946.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1947
#include <pic16lf1947.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF627
#include <pic16lf627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF627A
#include <pic16lf627a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF628
#include <pic16lf628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF628A
#include <pic16lf628a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF648A
#include <pic16lf648a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF707
#include <pic16lf707.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF720
#ifdef _LEGACY_HEADERS
#include <as16lf720_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16lf720.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16LF721
#ifdef _LEGACY_HEADERS
#include <as16lf721_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16lf721.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16LF722
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16lf722.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16LF722A
#include <pic16lf722a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF723
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16lf723.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16LF723A
#include <pic16lf723a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF724
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16lf724.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16LF726
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16lf726.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16LF727
#ifdef _LEGACY_HEADERS
#include <as16f72x_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic16lf727.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _16LF73
#include <pic16lf73.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF74
#include <pic16lf74.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF747
#include <pic16lf747.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF76
#include <pic16lf76.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF767
#include <pic16lf767.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF77
#include <pic16lf77.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF777
#include <pic16lf777.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF818
#include <pic16lf818.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF819
#include <pic16lf819.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF83
#include <pic16lf83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF84
#include <pic16lf84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF84A
#include <pic16lf84a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF87
#include <pic16lf87.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF870
#include <pic16lf870.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF871
#include <pic16lf871.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF872
#include <pic16lf872.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF873
#include <pic16lf873.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF873A
#include <pic16lf873a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF874
#include <pic16lf874.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF874A
#include <pic16lf874a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF876
#include <pic16lf876.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF876A
#include <pic16lf876a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF877
#include <pic16lf877.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF877A
#include <pic16lf877a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF88
#include <pic16lf88.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _RF509AF
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <picrf509af.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _RF509AG
#ifdef _LEGACY_HEADERS
#include <as125xx_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <picrf509ag.inc>
#undef _HEADER_NOT_FOUND
#endif
#endif

#ifdef _RF675F
#include <picrf675f.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _RF675H
#include <picrf675h.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _RF675K
#include <picrf675k.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _TEST_CHIP_
#undef _HEADER_NOT_FOUND
#endif

#ifdef _HEADER_NOT_FOUND
#error Device-specific header could not be found for target chip
#endif

#endif // _PIC_AS_CHIP_SELECT_INC_
